// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: management_net.proto

package managementnetpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleProtocol int32

const (
	RuleProtocol_UNKNOWN RuleProtocol = 0
	RuleProtocol_ALL     RuleProtocol = 1
	RuleProtocol_TCP     RuleProtocol = 2
	RuleProtocol_UDP     RuleProtocol = 3
	RuleProtocol_ICMP    RuleProtocol = 4
	RuleProtocol_CUSTOM  RuleProtocol = 5
)

// Enum value maps for RuleProtocol.
var (
	RuleProtocol_name = map[int32]string{
		0: "UNKNOWN",
		1: "ALL",
		2: "TCP",
		3: "UDP",
		4: "ICMP",
		5: "CUSTOM",
	}
	RuleProtocol_value = map[string]int32{
		"UNKNOWN": 0,
		"ALL":     1,
		"TCP":     2,
		"UDP":     3,
		"ICMP":    4,
		"CUSTOM":  5,
	}
)

func (x RuleProtocol) Enum() *RuleProtocol {
	p := new(RuleProtocol)
	*p = x
	return p
}

func (x RuleProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_management_net_proto_enumTypes[0].Descriptor()
}

func (RuleProtocol) Type() protoreflect.EnumType {
	return &file_management_net_proto_enumTypes[0]
}

func (x RuleProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleProtocol.Descriptor instead.
func (RuleProtocol) EnumDescriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{0}
}

type RuleDirection int32

const (
	RuleDirection_IN  RuleDirection = 0
	RuleDirection_OUT RuleDirection = 1
)

// Enum value maps for RuleDirection.
var (
	RuleDirection_name = map[int32]string{
		0: "IN",
		1: "OUT",
	}
	RuleDirection_value = map[string]int32{
		"IN":  0,
		"OUT": 1,
	}
)

func (x RuleDirection) Enum() *RuleDirection {
	p := new(RuleDirection)
	*p = x
	return p
}

func (x RuleDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_management_net_proto_enumTypes[1].Descriptor()
}

func (RuleDirection) Type() protoreflect.EnumType {
	return &file_management_net_proto_enumTypes[1]
}

func (x RuleDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleDirection.Descriptor instead.
func (RuleDirection) EnumDescriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{1}
}

type RuleAction int32

const (
	RuleAction_ACCEPT RuleAction = 0
	RuleAction_DROP   RuleAction = 1
)

// Enum value maps for RuleAction.
var (
	RuleAction_name = map[int32]string{
		0: "ACCEPT",
		1: "DROP",
	}
	RuleAction_value = map[string]int32{
		"ACCEPT": 0,
		"DROP":   1,
	}
)

func (x RuleAction) Enum() *RuleAction {
	p := new(RuleAction)
	*p = x
	return p
}

func (x RuleAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleAction) Descriptor() protoreflect.EnumDescriptor {
	return file_management_net_proto_enumTypes[2].Descriptor()
}

func (RuleAction) Type() protoreflect.EnumType {
	return &file_management_net_proto_enumTypes[2]
}

func (x RuleAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleAction.Descriptor instead.
func (RuleAction) EnumDescriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{2}
}

type PeerCapability int32

const (
	PeerCapability_PeerCapabilityUnknown        PeerCapability = 0
	PeerCapability_PeerCapabilitySourcePrefixes PeerCapability = 1
	PeerCapability_PeerCapabilityIPv6Overlay    PeerCapability = 2
)

// Enum value maps for PeerCapability.
var (
	PeerCapability_name = map[int32]string{
		0: "PeerCapabilityUnknown",
		1: "PeerCapabilitySourcePrefixes",
		2: "PeerCapabilityIPv6Overlay",
	}
	PeerCapability_value = map[string]int32{
		"PeerCapabilityUnknown":        0,
		"PeerCapabilitySourcePrefixes": 1,
		"PeerCapabilityIPv6Overlay":    2,
	}
)

func (x PeerCapability) Enum() *PeerCapability {
	p := new(PeerCapability)
	*p = x
	return p
}

func (x PeerCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PeerCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_management_net_proto_enumTypes[3].Descriptor()
}

func (PeerCapability) Type() protoreflect.EnumType {
	return &file_management_net_proto_enumTypes[3]
}

func (x PeerCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PeerCapability.Descriptor instead.
func (PeerCapability) EnumDescriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{3}
}

type HostConfig_Protocol int32

const (
	HostConfig_UDP   HostConfig_Protocol = 0
	HostConfig_TCP   HostConfig_Protocol = 1
	HostConfig_HTTP  HostConfig_Protocol = 2
	HostConfig_HTTPS HostConfig_Protocol = 3
	HostConfig_DTLS  HostConfig_Protocol = 4
)

// Enum value maps for HostConfig_Protocol.
var (
	HostConfig_Protocol_name = map[int32]string{
		0: "UDP",
		1: "TCP",
		2: "HTTP",
		3: "HTTPS",
		4: "DTLS",
	}
	HostConfig_Protocol_value = map[string]int32{
		"UDP":   0,
		"TCP":   1,
		"HTTP":  2,
		"HTTPS": 3,
		"DTLS":  4,
	}
)

func (x HostConfig_Protocol) Enum() *HostConfig_Protocol {
	p := new(HostConfig_Protocol)
	*p = x
	return p
}

func (x HostConfig_Protocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HostConfig_Protocol) Descriptor() protoreflect.EnumDescriptor {
	return file_management_net_proto_enumTypes[4].Descriptor()
}

func (HostConfig_Protocol) Type() protoreflect.EnumType {
	return &file_management_net_proto_enumTypes[4]
}

func (x HostConfig_Protocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HostConfig_Protocol.Descriptor instead.
func (HostConfig_Protocol) EnumDescriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{2, 0}
}

type SyncResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NetbirdConfig    *NetbirdConfig         `protobuf:"bytes,1,opt,name=netbirdConfig,proto3" json:"netbirdConfig,omitempty"`
	NetworkMap       *NetworkMap            `protobuf:"bytes,5,opt,name=NetworkMap,proto3" json:"NetworkMap,omitempty"`
	SessionExpiresAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=sessionExpiresAt,proto3" json:"sessionExpiresAt,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_management_net_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{0}
}

func (x *SyncResponse) GetNetbirdConfig() *NetbirdConfig {
	if x != nil {
		return x.NetbirdConfig
	}
	return nil
}

func (x *SyncResponse) GetNetworkMap() *NetworkMap {
	if x != nil {
		return x.NetworkMap
	}
	return nil
}

func (x *SyncResponse) GetSessionExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionExpiresAt
	}
	return nil
}

type NetbirdConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stuns         []*HostConfig          `protobuf:"bytes,1,rep,name=stuns,proto3" json:"stuns,omitempty"`
	Turns         []*ProtectedHostConfig `protobuf:"bytes,2,rep,name=turns,proto3" json:"turns,omitempty"`
	Signal        *HostConfig            `protobuf:"bytes,3,opt,name=signal,proto3" json:"signal,omitempty"`
	Relay         *RelayConfig           `protobuf:"bytes,4,opt,name=relay,proto3" json:"relay,omitempty"`
	Flow          *FlowConfig            `protobuf:"bytes,5,opt,name=flow,proto3" json:"flow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetbirdConfig) Reset() {
	*x = NetbirdConfig{}
	mi := &file_management_net_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetbirdConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetbirdConfig) ProtoMessage() {}

func (x *NetbirdConfig) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetbirdConfig.ProtoReflect.Descriptor instead.
func (*NetbirdConfig) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{1}
}

func (x *NetbirdConfig) GetStuns() []*HostConfig {
	if x != nil {
		return x.Stuns
	}
	return nil
}

func (x *NetbirdConfig) GetTurns() []*ProtectedHostConfig {
	if x != nil {
		return x.Turns
	}
	return nil
}

func (x *NetbirdConfig) GetSignal() *HostConfig {
	if x != nil {
		return x.Signal
	}
	return nil
}

func (x *NetbirdConfig) GetRelay() *RelayConfig {
	if x != nil {
		return x.Relay
	}
	return nil
}

func (x *NetbirdConfig) GetFlow() *FlowConfig {
	if x != nil {
		return x.Flow
	}
	return nil
}

type HostConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Protocol      HostConfig_Protocol    `protobuf:"varint,2,opt,name=protocol,proto3,enum=managementnetfixture.HostConfig_Protocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostConfig) Reset() {
	*x = HostConfig{}
	mi := &file_management_net_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostConfig) ProtoMessage() {}

func (x *HostConfig) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostConfig.ProtoReflect.Descriptor instead.
func (*HostConfig) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{2}
}

func (x *HostConfig) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *HostConfig) GetProtocol() HostConfig_Protocol {
	if x != nil {
		return x.Protocol
	}
	return HostConfig_UDP
}

type ProtectedHostConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostConfig    *HostConfig            `protobuf:"bytes,1,opt,name=hostConfig,proto3" json:"hostConfig,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtectedHostConfig) Reset() {
	*x = ProtectedHostConfig{}
	mi := &file_management_net_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtectedHostConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtectedHostConfig) ProtoMessage() {}

func (x *ProtectedHostConfig) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtectedHostConfig.ProtoReflect.Descriptor instead.
func (*ProtectedHostConfig) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{3}
}

func (x *ProtectedHostConfig) GetHostConfig() *HostConfig {
	if x != nil {
		return x.HostConfig
	}
	return nil
}

func (x *ProtectedHostConfig) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProtectedHostConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RelayConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Urls           []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	TokenPayload   string                 `protobuf:"bytes,2,opt,name=tokenPayload,proto3" json:"tokenPayload,omitempty"`
	TokenSignature string                 `protobuf:"bytes,3,opt,name=tokenSignature,proto3" json:"tokenSignature,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RelayConfig) Reset() {
	*x = RelayConfig{}
	mi := &file_management_net_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayConfig) ProtoMessage() {}

func (x *RelayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayConfig.ProtoReflect.Descriptor instead.
func (*RelayConfig) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{4}
}

func (x *RelayConfig) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *RelayConfig) GetTokenPayload() string {
	if x != nil {
		return x.TokenPayload
	}
	return ""
}

func (x *RelayConfig) GetTokenSignature() string {
	if x != nil {
		return x.TokenSignature
	}
	return ""
}

type FlowConfig struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Url                string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	TokenPayload       string                 `protobuf:"bytes,2,opt,name=tokenPayload,proto3" json:"tokenPayload,omitempty"`
	TokenSignature     string                 `protobuf:"bytes,3,opt,name=tokenSignature,proto3" json:"tokenSignature,omitempty"`
	Interval           *durationpb.Duration   `protobuf:"bytes,4,opt,name=interval,proto3" json:"interval,omitempty"`
	Enabled            bool                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Counters           bool                   `protobuf:"varint,6,opt,name=counters,proto3" json:"counters,omitempty"`
	ExitNodeCollection bool                   `protobuf:"varint,7,opt,name=exitNodeCollection,proto3" json:"exitNodeCollection,omitempty"`
	DnsCollection      bool                   `protobuf:"varint,8,opt,name=dnsCollection,proto3" json:"dnsCollection,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FlowConfig) Reset() {
	*x = FlowConfig{}
	mi := &file_management_net_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowConfig) ProtoMessage() {}

func (x *FlowConfig) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowConfig.ProtoReflect.Descriptor instead.
func (*FlowConfig) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{5}
}

func (x *FlowConfig) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FlowConfig) GetTokenPayload() string {
	if x != nil {
		return x.TokenPayload
	}
	return ""
}

func (x *FlowConfig) GetTokenSignature() string {
	if x != nil {
		return x.TokenSignature
	}
	return ""
}

func (x *FlowConfig) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *FlowConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FlowConfig) GetCounters() bool {
	if x != nil {
		return x.Counters
	}
	return false
}

func (x *FlowConfig) GetExitNodeCollection() bool {
	if x != nil {
		return x.ExitNodeCollection
	}
	return false
}

func (x *FlowConfig) GetDnsCollection() bool {
	if x != nil {
		return x.DnsCollection
	}
	return false
}

type NetworkMap struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Serial                     uint64                 `protobuf:"varint,1,opt,name=Serial,proto3" json:"Serial,omitempty"`
	PeerConfig                 *PeerConfig            `protobuf:"bytes,2,opt,name=peerConfig,proto3" json:"peerConfig,omitempty"`
	RemotePeers                []*RemotePeerConfig    `protobuf:"bytes,3,rep,name=remotePeers,proto3" json:"remotePeers,omitempty"`
	RemotePeersIsEmpty         bool                   `protobuf:"varint,4,opt,name=remotePeersIsEmpty,proto3" json:"remotePeersIsEmpty,omitempty"`
	Routes                     []*Route               `protobuf:"bytes,5,rep,name=Routes,proto3" json:"Routes,omitempty"`
	DNSConfig                  *DNSConfig             `protobuf:"bytes,6,opt,name=DNSConfig,proto3" json:"DNSConfig,omitempty"`
	OfflinePeers               []*RemotePeerConfig    `protobuf:"bytes,7,rep,name=offlinePeers,proto3" json:"offlinePeers,omitempty"`
	FirewallRules              []*FirewallRule        `protobuf:"bytes,8,rep,name=FirewallRules,proto3" json:"FirewallRules,omitempty"`
	FirewallRulesIsEmpty       bool                   `protobuf:"varint,9,opt,name=firewallRulesIsEmpty,proto3" json:"firewallRulesIsEmpty,omitempty"`
	RoutesFirewallRules        []*RouteFirewallRule   `protobuf:"bytes,10,rep,name=routesFirewallRules,proto3" json:"routesFirewallRules,omitempty"`
	RoutesFirewallRulesIsEmpty bool                   `protobuf:"varint,11,opt,name=routesFirewallRulesIsEmpty,proto3" json:"routesFirewallRulesIsEmpty,omitempty"`
	ForwardingRules            []*ForwardingRule      `protobuf:"bytes,12,rep,name=forwardingRules,proto3" json:"forwardingRules,omitempty"`
	SshAuth                    *SSHAuth               `protobuf:"bytes,13,opt,name=sshAuth,proto3" json:"sshAuth,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *NetworkMap) Reset() {
	*x = NetworkMap{}
	mi := &file_management_net_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMap) ProtoMessage() {}

func (x *NetworkMap) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMap.ProtoReflect.Descriptor instead.
func (*NetworkMap) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkMap) GetSerial() uint64 {
	if x != nil {
		return x.Serial
	}
	return 0
}

func (x *NetworkMap) GetPeerConfig() *PeerConfig {
	if x != nil {
		return x.PeerConfig
	}
	return nil
}

func (x *NetworkMap) GetRemotePeers() []*RemotePeerConfig {
	if x != nil {
		return x.RemotePeers
	}
	return nil
}

func (x *NetworkMap) GetRemotePeersIsEmpty() bool {
	if x != nil {
		return x.RemotePeersIsEmpty
	}
	return false
}

func (x *NetworkMap) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *NetworkMap) GetDNSConfig() *DNSConfig {
	if x != nil {
		return x.DNSConfig
	}
	return nil
}

func (x *NetworkMap) GetOfflinePeers() []*RemotePeerConfig {
	if x != nil {
		return x.OfflinePeers
	}
	return nil
}

func (x *NetworkMap) GetFirewallRules() []*FirewallRule {
	if x != nil {
		return x.FirewallRules
	}
	return nil
}

func (x *NetworkMap) GetFirewallRulesIsEmpty() bool {
	if x != nil {
		return x.FirewallRulesIsEmpty
	}
	return false
}

func (x *NetworkMap) GetRoutesFirewallRules() []*RouteFirewallRule {
	if x != nil {
		return x.RoutesFirewallRules
	}
	return nil
}

func (x *NetworkMap) GetRoutesFirewallRulesIsEmpty() bool {
	if x != nil {
		return x.RoutesFirewallRulesIsEmpty
	}
	return false
}

func (x *NetworkMap) GetForwardingRules() []*ForwardingRule {
	if x != nil {
		return x.ForwardingRules
	}
	return nil
}

func (x *NetworkMap) GetSshAuth() *SSHAuth {
	if x != nil {
		return x.SshAuth
	}
	return nil
}

type PeerConfig struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	Address                         string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Dns                             string                 `protobuf:"bytes,2,opt,name=dns,proto3" json:"dns,omitempty"`
	SshConfig                       *SSHConfig             `protobuf:"bytes,3,opt,name=sshConfig,proto3" json:"sshConfig,omitempty"`
	Fqdn                            string                 `protobuf:"bytes,4,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	RoutingPeerDnsResolutionEnabled bool                   `protobuf:"varint,5,opt,name=RoutingPeerDnsResolutionEnabled,proto3" json:"RoutingPeerDnsResolutionEnabled,omitempty"`
	LazyConnectionEnabled           bool                   `protobuf:"varint,6,opt,name=LazyConnectionEnabled,proto3" json:"LazyConnectionEnabled,omitempty"`
	Mtu                             int32                  `protobuf:"varint,7,opt,name=mtu,proto3" json:"mtu,omitempty"`
	AutoUpdate                      *AutoUpdateSettings    `protobuf:"bytes,8,opt,name=autoUpdate,proto3" json:"autoUpdate,omitempty"`
	AddressV6                       []byte                 `protobuf:"bytes,9,opt,name=address_v6,json=addressV6,proto3" json:"address_v6,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *PeerConfig) Reset() {
	*x = PeerConfig{}
	mi := &file_management_net_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerConfig) ProtoMessage() {}

func (x *PeerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerConfig.ProtoReflect.Descriptor instead.
func (*PeerConfig) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{7}
}

func (x *PeerConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerConfig) GetDns() string {
	if x != nil {
		return x.Dns
	}
	return ""
}

func (x *PeerConfig) GetSshConfig() *SSHConfig {
	if x != nil {
		return x.SshConfig
	}
	return nil
}

func (x *PeerConfig) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *PeerConfig) GetRoutingPeerDnsResolutionEnabled() bool {
	if x != nil {
		return x.RoutingPeerDnsResolutionEnabled
	}
	return false
}

func (x *PeerConfig) GetLazyConnectionEnabled() bool {
	if x != nil {
		return x.LazyConnectionEnabled
	}
	return false
}

func (x *PeerConfig) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *PeerConfig) GetAutoUpdate() *AutoUpdateSettings {
	if x != nil {
		return x.AutoUpdate
	}
	return nil
}

func (x *PeerConfig) GetAddressV6() []byte {
	if x != nil {
		return x.AddressV6
	}
	return nil
}

type AutoUpdateSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	AlwaysUpdate  bool                   `protobuf:"varint,2,opt,name=alwaysUpdate,proto3" json:"alwaysUpdate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoUpdateSettings) Reset() {
	*x = AutoUpdateSettings{}
	mi := &file_management_net_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoUpdateSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoUpdateSettings) ProtoMessage() {}

func (x *AutoUpdateSettings) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoUpdateSettings.ProtoReflect.Descriptor instead.
func (*AutoUpdateSettings) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{8}
}

func (x *AutoUpdateSettings) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AutoUpdateSettings) GetAlwaysUpdate() bool {
	if x != nil {
		return x.AlwaysUpdate
	}
	return false
}

type RemotePeerConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WgPubKey      string                 `protobuf:"bytes,1,opt,name=wgPubKey,proto3" json:"wgPubKey,omitempty"`
	AllowedIps    []string               `protobuf:"bytes,2,rep,name=allowedIps,proto3" json:"allowedIps,omitempty"`
	SshConfig     *SSHConfig             `protobuf:"bytes,3,opt,name=sshConfig,proto3" json:"sshConfig,omitempty"`
	Fqdn          string                 `protobuf:"bytes,4,opt,name=fqdn,proto3" json:"fqdn,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,5,opt,name=agentVersion,proto3" json:"agentVersion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemotePeerConfig) Reset() {
	*x = RemotePeerConfig{}
	mi := &file_management_net_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemotePeerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemotePeerConfig) ProtoMessage() {}

func (x *RemotePeerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemotePeerConfig.ProtoReflect.Descriptor instead.
func (*RemotePeerConfig) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{9}
}

func (x *RemotePeerConfig) GetWgPubKey() string {
	if x != nil {
		return x.WgPubKey
	}
	return ""
}

func (x *RemotePeerConfig) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *RemotePeerConfig) GetSshConfig() *SSHConfig {
	if x != nil {
		return x.SshConfig
	}
	return nil
}

func (x *RemotePeerConfig) GetFqdn() string {
	if x != nil {
		return x.Fqdn
	}
	return ""
}

func (x *RemotePeerConfig) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

type SSHConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SshEnabled    bool                   `protobuf:"varint,1,opt,name=sshEnabled,proto3" json:"sshEnabled,omitempty"`
	SshPubKey     []byte                 `protobuf:"bytes,2,opt,name=sshPubKey,proto3" json:"sshPubKey,omitempty"`
	JwtConfig     *JWTConfig             `protobuf:"bytes,3,opt,name=jwtConfig,proto3" json:"jwtConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHConfig) Reset() {
	*x = SSHConfig{}
	mi := &file_management_net_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHConfig) ProtoMessage() {}

func (x *SSHConfig) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHConfig.ProtoReflect.Descriptor instead.
func (*SSHConfig) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{10}
}

func (x *SSHConfig) GetSshEnabled() bool {
	if x != nil {
		return x.SshEnabled
	}
	return false
}

func (x *SSHConfig) GetSshPubKey() []byte {
	if x != nil {
		return x.SshPubKey
	}
	return nil
}

func (x *SSHConfig) GetJwtConfig() *JWTConfig {
	if x != nil {
		return x.JwtConfig
	}
	return nil
}

type JWTConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Audience      string                 `protobuf:"bytes,2,opt,name=audience,proto3" json:"audience,omitempty"`
	KeysLocation  string                 `protobuf:"bytes,3,opt,name=keysLocation,proto3" json:"keysLocation,omitempty"`
	MaxTokenAge   int64                  `protobuf:"varint,4,opt,name=maxTokenAge,proto3" json:"maxTokenAge,omitempty"`
	Audiences     []string               `protobuf:"bytes,5,rep,name=audiences,proto3" json:"audiences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWTConfig) Reset() {
	*x = JWTConfig{}
	mi := &file_management_net_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWTConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWTConfig) ProtoMessage() {}

func (x *JWTConfig) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWTConfig.ProtoReflect.Descriptor instead.
func (*JWTConfig) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{11}
}

func (x *JWTConfig) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *JWTConfig) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *JWTConfig) GetKeysLocation() string {
	if x != nil {
		return x.KeysLocation
	}
	return ""
}

func (x *JWTConfig) GetMaxTokenAge() int64 {
	if x != nil {
		return x.MaxTokenAge
	}
	return 0
}

func (x *JWTConfig) GetAudiences() []string {
	if x != nil {
		return x.Audiences
	}
	return nil
}

type SSHAuth struct {
	state           protoimpl.MessageState         `protogen:"open.v1"`
	UserIDClaim     string                         `protobuf:"bytes,1,opt,name=UserIDClaim,proto3" json:"UserIDClaim,omitempty"`
	AuthorizedUsers [][]byte                       `protobuf:"bytes,2,rep,name=AuthorizedUsers,proto3" json:"AuthorizedUsers,omitempty"`
	MachineUsers    map[string]*MachineUserIndexes `protobuf:"bytes,3,rep,name=machine_users,json=machineUsers,proto3" json:"machine_users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SSHAuth) Reset() {
	*x = SSHAuth{}
	mi := &file_management_net_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHAuth) ProtoMessage() {}

func (x *SSHAuth) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHAuth.ProtoReflect.Descriptor instead.
func (*SSHAuth) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{12}
}

func (x *SSHAuth) GetUserIDClaim() string {
	if x != nil {
		return x.UserIDClaim
	}
	return ""
}

func (x *SSHAuth) GetAuthorizedUsers() [][]byte {
	if x != nil {
		return x.AuthorizedUsers
	}
	return nil
}

func (x *SSHAuth) GetMachineUsers() map[string]*MachineUserIndexes {
	if x != nil {
		return x.MachineUsers
	}
	return nil
}

type MachineUserIndexes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Indexes       []uint32               `protobuf:"varint,1,rep,packed,name=indexes,proto3" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineUserIndexes) Reset() {
	*x = MachineUserIndexes{}
	mi := &file_management_net_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineUserIndexes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineUserIndexes) ProtoMessage() {}

func (x *MachineUserIndexes) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineUserIndexes.ProtoReflect.Descriptor instead.
func (*MachineUserIndexes) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{13}
}

func (x *MachineUserIndexes) GetIndexes() []uint32 {
	if x != nil {
		return x.Indexes
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=Network,proto3" json:"Network,omitempty"`
	NetworkType   int64                  `protobuf:"varint,3,opt,name=NetworkType,proto3" json:"NetworkType,omitempty"`
	Peer          string                 `protobuf:"bytes,4,opt,name=Peer,proto3" json:"Peer,omitempty"`
	Metric        int64                  `protobuf:"varint,5,opt,name=Metric,proto3" json:"Metric,omitempty"`
	Masquerade    bool                   `protobuf:"varint,6,opt,name=Masquerade,proto3" json:"Masquerade,omitempty"`
	NetID         string                 `protobuf:"bytes,7,opt,name=NetID,proto3" json:"NetID,omitempty"`
	Domains       []string               `protobuf:"bytes,8,rep,name=Domains,proto3" json:"Domains,omitempty"`
	KeepRoute     bool                   `protobuf:"varint,9,opt,name=keepRoute,proto3" json:"keepRoute,omitempty"`
	SkipAutoApply bool                   `protobuf:"varint,10,opt,name=skipAutoApply,proto3" json:"skipAutoApply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_management_net_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{14}
}

func (x *Route) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Route) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Route) GetNetworkType() int64 {
	if x != nil {
		return x.NetworkType
	}
	return 0
}

func (x *Route) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *Route) GetMetric() int64 {
	if x != nil {
		return x.Metric
	}
	return 0
}

func (x *Route) GetMasquerade() bool {
	if x != nil {
		return x.Masquerade
	}
	return false
}

func (x *Route) GetNetID() string {
	if x != nil {
		return x.NetID
	}
	return ""
}

func (x *Route) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *Route) GetKeepRoute() bool {
	if x != nil {
		return x.KeepRoute
	}
	return false
}

func (x *Route) GetSkipAutoApply() bool {
	if x != nil {
		return x.SkipAutoApply
	}
	return false
}

type DNSConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServiceEnable    bool                   `protobuf:"varint,1,opt,name=ServiceEnable,proto3" json:"ServiceEnable,omitempty"`
	NameServerGroups []*NameServerGroup     `protobuf:"bytes,2,rep,name=NameServerGroups,proto3" json:"NameServerGroups,omitempty"`
	CustomZones      []*CustomZone          `protobuf:"bytes,3,rep,name=CustomZones,proto3" json:"CustomZones,omitempty"`
	// Deprecated: Marked as deprecated in management_net.proto.
	ForwarderPort int64 `protobuf:"varint,4,opt,name=ForwarderPort,proto3" json:"ForwarderPort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSConfig) Reset() {
	*x = DNSConfig{}
	mi := &file_management_net_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSConfig) ProtoMessage() {}

func (x *DNSConfig) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSConfig.ProtoReflect.Descriptor instead.
func (*DNSConfig) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{15}
}

func (x *DNSConfig) GetServiceEnable() bool {
	if x != nil {
		return x.ServiceEnable
	}
	return false
}

func (x *DNSConfig) GetNameServerGroups() []*NameServerGroup {
	if x != nil {
		return x.NameServerGroups
	}
	return nil
}

func (x *DNSConfig) GetCustomZones() []*CustomZone {
	if x != nil {
		return x.CustomZones
	}
	return nil
}

// Deprecated: Marked as deprecated in management_net.proto.
func (x *DNSConfig) GetForwarderPort() int64 {
	if x != nil {
		return x.ForwarderPort
	}
	return 0
}

type CustomZone struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Domain               string                 `protobuf:"bytes,1,opt,name=Domain,proto3" json:"Domain,omitempty"`
	Records              []*SimpleRecord        `protobuf:"bytes,2,rep,name=Records,proto3" json:"Records,omitempty"`
	SearchDomainDisabled bool                   `protobuf:"varint,3,opt,name=SearchDomainDisabled,proto3" json:"SearchDomainDisabled,omitempty"`
	NonAuthoritative     bool                   `protobuf:"varint,4,opt,name=NonAuthoritative,proto3" json:"NonAuthoritative,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CustomZone) Reset() {
	*x = CustomZone{}
	mi := &file_management_net_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomZone) ProtoMessage() {}

func (x *CustomZone) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomZone.ProtoReflect.Descriptor instead.
func (*CustomZone) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{16}
}

func (x *CustomZone) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *CustomZone) GetRecords() []*SimpleRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *CustomZone) GetSearchDomainDisabled() bool {
	if x != nil {
		return x.SearchDomainDisabled
	}
	return false
}

func (x *CustomZone) GetNonAuthoritative() bool {
	if x != nil {
		return x.NonAuthoritative
	}
	return false
}

type SimpleRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type          int64                  `protobuf:"varint,2,opt,name=Type,proto3" json:"Type,omitempty"`
	Class         string                 `protobuf:"bytes,3,opt,name=Class,proto3" json:"Class,omitempty"`
	TTL           int64                  `protobuf:"varint,4,opt,name=TTL,proto3" json:"TTL,omitempty"`
	RData         string                 `protobuf:"bytes,5,opt,name=RData,proto3" json:"RData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleRecord) Reset() {
	*x = SimpleRecord{}
	mi := &file_management_net_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleRecord) ProtoMessage() {}

func (x *SimpleRecord) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleRecord.ProtoReflect.Descriptor instead.
func (*SimpleRecord) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{17}
}

func (x *SimpleRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimpleRecord) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *SimpleRecord) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *SimpleRecord) GetTTL() int64 {
	if x != nil {
		return x.TTL
	}
	return 0
}

func (x *SimpleRecord) GetRData() string {
	if x != nil {
		return x.RData
	}
	return ""
}

type NameServerGroup struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	NameServers          []*NameServer          `protobuf:"bytes,1,rep,name=NameServers,proto3" json:"NameServers,omitempty"`
	Primary              bool                   `protobuf:"varint,2,opt,name=Primary,proto3" json:"Primary,omitempty"`
	Domains              []string               `protobuf:"bytes,3,rep,name=Domains,proto3" json:"Domains,omitempty"`
	SearchDomainsEnabled bool                   `protobuf:"varint,4,opt,name=SearchDomainsEnabled,proto3" json:"SearchDomainsEnabled,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NameServerGroup) Reset() {
	*x = NameServerGroup{}
	mi := &file_management_net_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameServerGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameServerGroup) ProtoMessage() {}

func (x *NameServerGroup) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameServerGroup.ProtoReflect.Descriptor instead.
func (*NameServerGroup) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{18}
}

func (x *NameServerGroup) GetNameServers() []*NameServer {
	if x != nil {
		return x.NameServers
	}
	return nil
}

func (x *NameServerGroup) GetPrimary() bool {
	if x != nil {
		return x.Primary
	}
	return false
}

func (x *NameServerGroup) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *NameServerGroup) GetSearchDomainsEnabled() bool {
	if x != nil {
		return x.SearchDomainsEnabled
	}
	return false
}

type NameServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IP            string                 `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	NSType        int64                  `protobuf:"varint,2,opt,name=NSType,proto3" json:"NSType,omitempty"`
	Port          int64                  `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NameServer) Reset() {
	*x = NameServer{}
	mi := &file_management_net_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NameServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NameServer) ProtoMessage() {}

func (x *NameServer) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NameServer.ProtoReflect.Descriptor instead.
func (*NameServer) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{19}
}

func (x *NameServer) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *NameServer) GetNSType() int64 {
	if x != nil {
		return x.NSType
	}
	return 0
}

func (x *NameServer) GetPort() int64 {
	if x != nil {
		return x.Port
	}
	return 0
}

type FirewallRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Deprecated: Marked as deprecated in management_net.proto.
	PeerIP         string        `protobuf:"bytes,1,opt,name=PeerIP,proto3" json:"PeerIP,omitempty"`
	Direction      RuleDirection `protobuf:"varint,2,opt,name=Direction,proto3,enum=managementnetfixture.RuleDirection" json:"Direction,omitempty"`
	Action         RuleAction    `protobuf:"varint,3,opt,name=Action,proto3,enum=managementnetfixture.RuleAction" json:"Action,omitempty"`
	Protocol       RuleProtocol  `protobuf:"varint,4,opt,name=Protocol,proto3,enum=managementnetfixture.RuleProtocol" json:"Protocol,omitempty"`
	Port           string        `protobuf:"bytes,5,opt,name=Port,proto3" json:"Port,omitempty"`
	PortInfo       *PortInfo     `protobuf:"bytes,6,opt,name=PortInfo,proto3" json:"PortInfo,omitempty"`
	PolicyID       []byte        `protobuf:"bytes,7,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	CustomProtocol uint32        `protobuf:"varint,8,opt,name=customProtocol,proto3" json:"customProtocol,omitempty"`
	SourcePrefixes [][]byte      `protobuf:"bytes,9,rep,name=sourcePrefixes,proto3" json:"sourcePrefixes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FirewallRule) Reset() {
	*x = FirewallRule{}
	mi := &file_management_net_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FirewallRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirewallRule) ProtoMessage() {}

func (x *FirewallRule) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirewallRule.ProtoReflect.Descriptor instead.
func (*FirewallRule) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{20}
}

// Deprecated: Marked as deprecated in management_net.proto.
func (x *FirewallRule) GetPeerIP() string {
	if x != nil {
		return x.PeerIP
	}
	return ""
}

func (x *FirewallRule) GetDirection() RuleDirection {
	if x != nil {
		return x.Direction
	}
	return RuleDirection_IN
}

func (x *FirewallRule) GetAction() RuleAction {
	if x != nil {
		return x.Action
	}
	return RuleAction_ACCEPT
}

func (x *FirewallRule) GetProtocol() RuleProtocol {
	if x != nil {
		return x.Protocol
	}
	return RuleProtocol_UNKNOWN
}

func (x *FirewallRule) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *FirewallRule) GetPortInfo() *PortInfo {
	if x != nil {
		return x.PortInfo
	}
	return nil
}

func (x *FirewallRule) GetPolicyID() []byte {
	if x != nil {
		return x.PolicyID
	}
	return nil
}

func (x *FirewallRule) GetCustomProtocol() uint32 {
	if x != nil {
		return x.CustomProtocol
	}
	return 0
}

func (x *FirewallRule) GetSourcePrefixes() [][]byte {
	if x != nil {
		return x.SourcePrefixes
	}
	return nil
}

type PortInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to PortSelection:
	//
	//	*PortInfo_Port
	//	*PortInfo_Range_
	PortSelection isPortInfo_PortSelection `protobuf_oneof:"portSelection"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortInfo) Reset() {
	*x = PortInfo{}
	mi := &file_management_net_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortInfo) ProtoMessage() {}

func (x *PortInfo) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortInfo.ProtoReflect.Descriptor instead.
func (*PortInfo) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{21}
}

func (x *PortInfo) GetPortSelection() isPortInfo_PortSelection {
	if x != nil {
		return x.PortSelection
	}
	return nil
}

func (x *PortInfo) GetPort() uint32 {
	if x != nil {
		if x, ok := x.PortSelection.(*PortInfo_Port); ok {
			return x.Port
		}
	}
	return 0
}

func (x *PortInfo) GetRange() *PortInfo_Range {
	if x != nil {
		if x, ok := x.PortSelection.(*PortInfo_Range_); ok {
			return x.Range
		}
	}
	return nil
}

type isPortInfo_PortSelection interface {
	isPortInfo_PortSelection()
}

type PortInfo_Port struct {
	Port uint32 `protobuf:"varint,1,opt,name=port,proto3,oneof"`
}

type PortInfo_Range_ struct {
	Range *PortInfo_Range `protobuf:"bytes,2,opt,name=range,proto3,oneof"`
}

func (*PortInfo_Port) isPortInfo_PortSelection() {}

func (*PortInfo_Range_) isPortInfo_PortSelection() {}

type RouteFirewallRule struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SourceRanges   []string               `protobuf:"bytes,1,rep,name=sourceRanges,proto3" json:"sourceRanges,omitempty"`
	Action         RuleAction             `protobuf:"varint,2,opt,name=action,proto3,enum=managementnetfixture.RuleAction" json:"action,omitempty"`
	Destination    string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	Protocol       RuleProtocol           `protobuf:"varint,4,opt,name=protocol,proto3,enum=managementnetfixture.RuleProtocol" json:"protocol,omitempty"`
	PortInfo       *PortInfo              `protobuf:"bytes,5,opt,name=portInfo,proto3" json:"portInfo,omitempty"`
	IsDynamic      bool                   `protobuf:"varint,6,opt,name=isDynamic,proto3" json:"isDynamic,omitempty"`
	Domains        []string               `protobuf:"bytes,7,rep,name=domains,proto3" json:"domains,omitempty"`
	CustomProtocol uint32                 `protobuf:"varint,8,opt,name=customProtocol,proto3" json:"customProtocol,omitempty"`
	PolicyID       []byte                 `protobuf:"bytes,9,opt,name=PolicyID,proto3" json:"PolicyID,omitempty"`
	RouteID        string                 `protobuf:"bytes,10,opt,name=RouteID,proto3" json:"RouteID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RouteFirewallRule) Reset() {
	*x = RouteFirewallRule{}
	mi := &file_management_net_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteFirewallRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteFirewallRule) ProtoMessage() {}

func (x *RouteFirewallRule) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteFirewallRule.ProtoReflect.Descriptor instead.
func (*RouteFirewallRule) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{22}
}

func (x *RouteFirewallRule) GetSourceRanges() []string {
	if x != nil {
		return x.SourceRanges
	}
	return nil
}

func (x *RouteFirewallRule) GetAction() RuleAction {
	if x != nil {
		return x.Action
	}
	return RuleAction_ACCEPT
}

func (x *RouteFirewallRule) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *RouteFirewallRule) GetProtocol() RuleProtocol {
	if x != nil {
		return x.Protocol
	}
	return RuleProtocol_UNKNOWN
}

func (x *RouteFirewallRule) GetPortInfo() *PortInfo {
	if x != nil {
		return x.PortInfo
	}
	return nil
}

func (x *RouteFirewallRule) GetIsDynamic() bool {
	if x != nil {
		return x.IsDynamic
	}
	return false
}

func (x *RouteFirewallRule) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

func (x *RouteFirewallRule) GetCustomProtocol() uint32 {
	if x != nil {
		return x.CustomProtocol
	}
	return 0
}

func (x *RouteFirewallRule) GetPolicyID() []byte {
	if x != nil {
		return x.PolicyID
	}
	return nil
}

func (x *RouteFirewallRule) GetRouteID() string {
	if x != nil {
		return x.RouteID
	}
	return ""
}

type ForwardingRule struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Protocol          RuleProtocol           `protobuf:"varint,1,opt,name=protocol,proto3,enum=managementnetfixture.RuleProtocol" json:"protocol,omitempty"`
	DestinationPort   *PortInfo              `protobuf:"bytes,2,opt,name=destinationPort,proto3" json:"destinationPort,omitempty"`
	TranslatedAddress []byte                 `protobuf:"bytes,3,opt,name=translatedAddress,proto3" json:"translatedAddress,omitempty"`
	TranslatedPort    *PortInfo              `protobuf:"bytes,4,opt,name=translatedPort,proto3" json:"translatedPort,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ForwardingRule) Reset() {
	*x = ForwardingRule{}
	mi := &file_management_net_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardingRule) ProtoMessage() {}

func (x *ForwardingRule) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardingRule.ProtoReflect.Descriptor instead.
func (*ForwardingRule) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{23}
}

func (x *ForwardingRule) GetProtocol() RuleProtocol {
	if x != nil {
		return x.Protocol
	}
	return RuleProtocol_UNKNOWN
}

func (x *ForwardingRule) GetDestinationPort() *PortInfo {
	if x != nil {
		return x.DestinationPort
	}
	return nil
}

func (x *ForwardingRule) GetTranslatedAddress() []byte {
	if x != nil {
		return x.TranslatedAddress
	}
	return nil
}

func (x *ForwardingRule) GetTranslatedPort() *PortInfo {
	if x != nil {
		return x.TranslatedPort
	}
	return nil
}

type NetworkAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NetIP         string                 `protobuf:"bytes,1,opt,name=netIP,proto3" json:"netIP,omitempty"`
	Mac           string                 `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkAddress) Reset() {
	*x = NetworkAddress{}
	mi := &file_management_net_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAddress) ProtoMessage() {}

func (x *NetworkAddress) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAddress.ProtoReflect.Descriptor instead.
func (*NetworkAddress) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{24}
}

func (x *NetworkAddress) GetNetIP() string {
	if x != nil {
		return x.NetIP
	}
	return ""
}

func (x *NetworkAddress) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

type Checks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []string               `protobuf:"bytes,1,rep,name=Files,proto3" json:"Files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checks) Reset() {
	*x = Checks{}
	mi := &file_management_net_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checks) ProtoMessage() {}

func (x *Checks) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checks.ProtoReflect.Descriptor instead.
func (*Checks) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{25}
}

func (x *Checks) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cloud         string                 `protobuf:"bytes,1,opt,name=cloud,proto3" json:"cloud,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_management_net_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{26}
}

func (x *Environment) GetCloud() string {
	if x != nil {
		return x.Cloud
	}
	return ""
}

func (x *Environment) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type File struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Path             string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Exist            bool                   `protobuf:"varint,2,opt,name=exist,proto3" json:"exist,omitempty"`
	ProcessIsRunning bool                   `protobuf:"varint,3,opt,name=processIsRunning,proto3" json:"processIsRunning,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_management_net_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{27}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetExist() bool {
	if x != nil {
		return x.Exist
	}
	return false
}

func (x *File) GetProcessIsRunning() bool {
	if x != nil {
		return x.ProcessIsRunning
	}
	return false
}

type Flags struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	RosenpassEnabled              bool                   `protobuf:"varint,1,opt,name=rosenpassEnabled,proto3" json:"rosenpassEnabled,omitempty"`
	RosenpassPermissive           bool                   `protobuf:"varint,2,opt,name=rosenpassPermissive,proto3" json:"rosenpassPermissive,omitempty"`
	ServerSSHAllowed              bool                   `protobuf:"varint,3,opt,name=serverSSHAllowed,proto3" json:"serverSSHAllowed,omitempty"`
	DisableClientRoutes           bool                   `protobuf:"varint,4,opt,name=disableClientRoutes,proto3" json:"disableClientRoutes,omitempty"`
	DisableServerRoutes           bool                   `protobuf:"varint,5,opt,name=disableServerRoutes,proto3" json:"disableServerRoutes,omitempty"`
	DisableDNS                    bool                   `protobuf:"varint,6,opt,name=disableDNS,proto3" json:"disableDNS,omitempty"`
	DisableFirewall               bool                   `protobuf:"varint,7,opt,name=disableFirewall,proto3" json:"disableFirewall,omitempty"`
	BlockLANAccess                bool                   `protobuf:"varint,8,opt,name=blockLANAccess,proto3" json:"blockLANAccess,omitempty"`
	BlockInbound                  bool                   `protobuf:"varint,9,opt,name=blockInbound,proto3" json:"blockInbound,omitempty"`
	LazyConnectionEnabled         bool                   `protobuf:"varint,10,opt,name=lazyConnectionEnabled,proto3" json:"lazyConnectionEnabled,omitempty"`
	EnableSSHRoot                 bool                   `protobuf:"varint,11,opt,name=enableSSHRoot,proto3" json:"enableSSHRoot,omitempty"`
	EnableSSHSFTP                 bool                   `protobuf:"varint,12,opt,name=enableSSHSFTP,proto3" json:"enableSSHSFTP,omitempty"`
	EnableSSHLocalPortForwarding  bool                   `protobuf:"varint,13,opt,name=enableSSHLocalPortForwarding,proto3" json:"enableSSHLocalPortForwarding,omitempty"`
	EnableSSHRemotePortForwarding bool                   `protobuf:"varint,14,opt,name=enableSSHRemotePortForwarding,proto3" json:"enableSSHRemotePortForwarding,omitempty"`
	DisableSSHAuth                bool                   `protobuf:"varint,15,opt,name=disableSSHAuth,proto3" json:"disableSSHAuth,omitempty"`
	DisableIPv6                   bool                   `protobuf:"varint,16,opt,name=disableIPv6,proto3" json:"disableIPv6,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Flags) Reset() {
	*x = Flags{}
	mi := &file_management_net_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flags) ProtoMessage() {}

func (x *Flags) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flags.ProtoReflect.Descriptor instead.
func (*Flags) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{28}
}

func (x *Flags) GetRosenpassEnabled() bool {
	if x != nil {
		return x.RosenpassEnabled
	}
	return false
}

func (x *Flags) GetRosenpassPermissive() bool {
	if x != nil {
		return x.RosenpassPermissive
	}
	return false
}

func (x *Flags) GetServerSSHAllowed() bool {
	if x != nil {
		return x.ServerSSHAllowed
	}
	return false
}

func (x *Flags) GetDisableClientRoutes() bool {
	if x != nil {
		return x.DisableClientRoutes
	}
	return false
}

func (x *Flags) GetDisableServerRoutes() bool {
	if x != nil {
		return x.DisableServerRoutes
	}
	return false
}

func (x *Flags) GetDisableDNS() bool {
	if x != nil {
		return x.DisableDNS
	}
	return false
}

func (x *Flags) GetDisableFirewall() bool {
	if x != nil {
		return x.DisableFirewall
	}
	return false
}

func (x *Flags) GetBlockLANAccess() bool {
	if x != nil {
		return x.BlockLANAccess
	}
	return false
}

func (x *Flags) GetBlockInbound() bool {
	if x != nil {
		return x.BlockInbound
	}
	return false
}

func (x *Flags) GetLazyConnectionEnabled() bool {
	if x != nil {
		return x.LazyConnectionEnabled
	}
	return false
}

func (x *Flags) GetEnableSSHRoot() bool {
	if x != nil {
		return x.EnableSSHRoot
	}
	return false
}

func (x *Flags) GetEnableSSHSFTP() bool {
	if x != nil {
		return x.EnableSSHSFTP
	}
	return false
}

func (x *Flags) GetEnableSSHLocalPortForwarding() bool {
	if x != nil {
		return x.EnableSSHLocalPortForwarding
	}
	return false
}

func (x *Flags) GetEnableSSHRemotePortForwarding() bool {
	if x != nil {
		return x.EnableSSHRemotePortForwarding
	}
	return false
}

func (x *Flags) GetDisableSSHAuth() bool {
	if x != nil {
		return x.DisableSSHAuth
	}
	return false
}

func (x *Flags) GetDisableIPv6() bool {
	if x != nil {
		return x.DisableIPv6
	}
	return false
}

type PeerSystemMeta struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Hostname         string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	GoOS             string                 `protobuf:"bytes,2,opt,name=goOS,proto3" json:"goOS,omitempty"`
	Kernel           string                 `protobuf:"bytes,3,opt,name=kernel,proto3" json:"kernel,omitempty"`
	Core             string                 `protobuf:"bytes,4,opt,name=core,proto3" json:"core,omitempty"`
	Platform         string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	OS               string                 `protobuf:"bytes,6,opt,name=OS,proto3" json:"OS,omitempty"`
	NetbirdVersion   string                 `protobuf:"bytes,7,opt,name=netbirdVersion,proto3" json:"netbirdVersion,omitempty"`
	UiVersion        string                 `protobuf:"bytes,8,opt,name=uiVersion,proto3" json:"uiVersion,omitempty"`
	KernelVersion    string                 `protobuf:"bytes,9,opt,name=kernelVersion,proto3" json:"kernelVersion,omitempty"`
	OSVersion        string                 `protobuf:"bytes,10,opt,name=OSVersion,proto3" json:"OSVersion,omitempty"`
	NetworkAddresses []*NetworkAddress      `protobuf:"bytes,11,rep,name=networkAddresses,proto3" json:"networkAddresses,omitempty"`
	SysSerialNumber  string                 `protobuf:"bytes,12,opt,name=sysSerialNumber,proto3" json:"sysSerialNumber,omitempty"`
	SysProductName   string                 `protobuf:"bytes,13,opt,name=sysProductName,proto3" json:"sysProductName,omitempty"`
	SysManufacturer  string                 `protobuf:"bytes,14,opt,name=sysManufacturer,proto3" json:"sysManufacturer,omitempty"`
	Environment      *Environment           `protobuf:"bytes,15,opt,name=environment,proto3" json:"environment,omitempty"`
	Files            []*File                `protobuf:"bytes,16,rep,name=files,proto3" json:"files,omitempty"`
	Flags            *Flags                 `protobuf:"bytes,17,opt,name=flags,proto3" json:"flags,omitempty"`
	Capabilities     []PeerCapability       `protobuf:"varint,18,rep,packed,name=capabilities,proto3,enum=managementnetfixture.PeerCapability" json:"capabilities,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeerSystemMeta) Reset() {
	*x = PeerSystemMeta{}
	mi := &file_management_net_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerSystemMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerSystemMeta) ProtoMessage() {}

func (x *PeerSystemMeta) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerSystemMeta.ProtoReflect.Descriptor instead.
func (*PeerSystemMeta) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{29}
}

func (x *PeerSystemMeta) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *PeerSystemMeta) GetGoOS() string {
	if x != nil {
		return x.GoOS
	}
	return ""
}

func (x *PeerSystemMeta) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *PeerSystemMeta) GetCore() string {
	if x != nil {
		return x.Core
	}
	return ""
}

func (x *PeerSystemMeta) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PeerSystemMeta) GetOS() string {
	if x != nil {
		return x.OS
	}
	return ""
}

func (x *PeerSystemMeta) GetNetbirdVersion() string {
	if x != nil {
		return x.NetbirdVersion
	}
	return ""
}

func (x *PeerSystemMeta) GetUiVersion() string {
	if x != nil {
		return x.UiVersion
	}
	return ""
}

func (x *PeerSystemMeta) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *PeerSystemMeta) GetOSVersion() string {
	if x != nil {
		return x.OSVersion
	}
	return ""
}

func (x *PeerSystemMeta) GetNetworkAddresses() []*NetworkAddress {
	if x != nil {
		return x.NetworkAddresses
	}
	return nil
}

func (x *PeerSystemMeta) GetSysSerialNumber() string {
	if x != nil {
		return x.SysSerialNumber
	}
	return ""
}

func (x *PeerSystemMeta) GetSysProductName() string {
	if x != nil {
		return x.SysProductName
	}
	return ""
}

func (x *PeerSystemMeta) GetSysManufacturer() string {
	if x != nil {
		return x.SysManufacturer
	}
	return ""
}

func (x *PeerSystemMeta) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *PeerSystemMeta) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *PeerSystemMeta) GetFlags() *Flags {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *PeerSystemMeta) GetCapabilities() []PeerCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type PortInfo_Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         uint32                 `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           uint32                 `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortInfo_Range) Reset() {
	*x = PortInfo_Range{}
	mi := &file_management_net_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortInfo_Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortInfo_Range) ProtoMessage() {}

func (x *PortInfo_Range) ProtoReflect() protoreflect.Message {
	mi := &file_management_net_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortInfo_Range.ProtoReflect.Descriptor instead.
func (*PortInfo_Range) Descriptor() ([]byte, []int) {
	return file_management_net_proto_rawDescGZIP(), []int{21, 0}
}

func (x *PortInfo_Range) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *PortInfo_Range) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

var File_management_net_proto protoreflect.FileDescriptor

const file_management_net_proto_rawDesc = "" +
	"\n" +
	"\x14management_net.proto\x12\x14managementnetfixture\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe3\x01\n" +
	"\fSyncResponse\x12I\n" +
	"\rnetbirdConfig\x18\x01 \x01(\v2#.managementnetfixture.NetbirdConfigR\rnetbirdConfig\x12@\n" +
	"\n" +
	"NetworkMap\x18\x05 \x01(\v2 .managementnetfixture.NetworkMapR\n" +
	"NetworkMap\x12F\n" +
	"\x10sessionExpiresAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x10sessionExpiresAt\"\xb1\x02\n" +
	"\rNetbirdConfig\x126\n" +
	"\x05stuns\x18\x01 \x03(\v2 .managementnetfixture.HostConfigR\x05stuns\x12?\n" +
	"\x05turns\x18\x02 \x03(\v2).managementnetfixture.ProtectedHostConfigR\x05turns\x128\n" +
	"\x06signal\x18\x03 \x01(\v2 .managementnetfixture.HostConfigR\x06signal\x127\n" +
	"\x05relay\x18\x04 \x01(\v2!.managementnetfixture.RelayConfigR\x05relay\x124\n" +
	"\x04flow\x18\x05 \x01(\v2 .managementnetfixture.FlowConfigR\x04flow\"\xa2\x01\n" +
	"\n" +
	"HostConfig\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12E\n" +
	"\bprotocol\x18\x02 \x01(\x0e2).managementnetfixture.HostConfig.ProtocolR\bprotocol\";\n" +
	"\bProtocol\x12\a\n" +
	"\x03UDP\x10\x00\x12\a\n" +
	"\x03TCP\x10\x01\x12\b\n" +
	"\x04HTTP\x10\x02\x12\t\n" +
	"\x05HTTPS\x10\x03\x12\b\n" +
	"\x04DTLS\x10\x04\"\x87\x01\n" +
	"\x13ProtectedHostConfig\x12@\n" +
	"\n" +
	"hostConfig\x18\x01 \x01(\v2 .managementnetfixture.HostConfigR\n" +
	"hostConfig\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"m\n" +
	"\vRelayConfig\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\x12\"\n" +
	"\ftokenPayload\x18\x02 \x01(\tR\ftokenPayload\x12&\n" +
	"\x0etokenSignature\x18\x03 \x01(\tR\x0etokenSignature\"\xad\x02\n" +
	"\n" +
	"FlowConfig\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\"\n" +
	"\ftokenPayload\x18\x02 \x01(\tR\ftokenPayload\x12&\n" +
	"\x0etokenSignature\x18\x03 \x01(\tR\x0etokenSignature\x125\n" +
	"\binterval\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\binterval\x12\x18\n" +
	"\aenabled\x18\x05 \x01(\bR\aenabled\x12\x1a\n" +
	"\bcounters\x18\x06 \x01(\bR\bcounters\x12.\n" +
	"\x12exitNodeCollection\x18\a \x01(\bR\x12exitNodeCollection\x12$\n" +
	"\rdnsCollection\x18\b \x01(\bR\rdnsCollection\"\xc2\x06\n" +
	"\n" +
	"NetworkMap\x12\x16\n" +
	"\x06Serial\x18\x01 \x01(\x04R\x06Serial\x12@\n" +
	"\n" +
	"peerConfig\x18\x02 \x01(\v2 .managementnetfixture.PeerConfigR\n" +
	"peerConfig\x12H\n" +
	"\vremotePeers\x18\x03 \x03(\v2&.managementnetfixture.RemotePeerConfigR\vremotePeers\x12.\n" +
	"\x12remotePeersIsEmpty\x18\x04 \x01(\bR\x12remotePeersIsEmpty\x123\n" +
	"\x06Routes\x18\x05 \x03(\v2\x1b.managementnetfixture.RouteR\x06Routes\x12=\n" +
	"\tDNSConfig\x18\x06 \x01(\v2\x1f.managementnetfixture.DNSConfigR\tDNSConfig\x12J\n" +
	"\fofflinePeers\x18\a \x03(\v2&.managementnetfixture.RemotePeerConfigR\fofflinePeers\x12H\n" +
	"\rFirewallRules\x18\b \x03(\v2\".managementnetfixture.FirewallRuleR\rFirewallRules\x122\n" +
	"\x14firewallRulesIsEmpty\x18\t \x01(\bR\x14firewallRulesIsEmpty\x12Y\n" +
	"\x13routesFirewallRules\x18\n" +
	" \x03(\v2'.managementnetfixture.RouteFirewallRuleR\x13routesFirewallRules\x12>\n" +
	"\x1aroutesFirewallRulesIsEmpty\x18\v \x01(\bR\x1aroutesFirewallRulesIsEmpty\x12N\n" +
	"\x0fforwardingRules\x18\f \x03(\v2$.managementnetfixture.ForwardingRuleR\x0fforwardingRules\x127\n" +
	"\asshAuth\x18\r \x01(\v2\x1d.managementnetfixture.SSHAuthR\asshAuth\"\x86\x03\n" +
	"\n" +
	"PeerConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x10\n" +
	"\x03dns\x18\x02 \x01(\tR\x03dns\x12=\n" +
	"\tsshConfig\x18\x03 \x01(\v2\x1f.managementnetfixture.SSHConfigR\tsshConfig\x12\x12\n" +
	"\x04fqdn\x18\x04 \x01(\tR\x04fqdn\x12H\n" +
	"\x1fRoutingPeerDnsResolutionEnabled\x18\x05 \x01(\bR\x1fRoutingPeerDnsResolutionEnabled\x124\n" +
	"\x15LazyConnectionEnabled\x18\x06 \x01(\bR\x15LazyConnectionEnabled\x12\x10\n" +
	"\x03mtu\x18\a \x01(\x05R\x03mtu\x12H\n" +
	"\n" +
	"autoUpdate\x18\b \x01(\v2(.managementnetfixture.AutoUpdateSettingsR\n" +
	"autoUpdate\x12\x1d\n" +
	"\n" +
	"address_v6\x18\t \x01(\fR\taddressV6\"R\n" +
	"\x12AutoUpdateSettings\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\"\n" +
	"\falwaysUpdate\x18\x02 \x01(\bR\falwaysUpdate\"\xc5\x01\n" +
	"\x10RemotePeerConfig\x12\x1a\n" +
	"\bwgPubKey\x18\x01 \x01(\tR\bwgPubKey\x12\x1e\n" +
	"\n" +
	"allowedIps\x18\x02 \x03(\tR\n" +
	"allowedIps\x12=\n" +
	"\tsshConfig\x18\x03 \x01(\v2\x1f.managementnetfixture.SSHConfigR\tsshConfig\x12\x12\n" +
	"\x04fqdn\x18\x04 \x01(\tR\x04fqdn\x12\"\n" +
	"\fagentVersion\x18\x05 \x01(\tR\fagentVersion\"\x88\x01\n" +
	"\tSSHConfig\x12\x1e\n" +
	"\n" +
	"sshEnabled\x18\x01 \x01(\bR\n" +
	"sshEnabled\x12\x1c\n" +
	"\tsshPubKey\x18\x02 \x01(\fR\tsshPubKey\x12=\n" +
	"\tjwtConfig\x18\x03 \x01(\v2\x1f.managementnetfixture.JWTConfigR\tjwtConfig\"\xa3\x01\n" +
	"\tJWTConfig\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x1a\n" +
	"\baudience\x18\x02 \x01(\tR\baudience\x12\"\n" +
	"\fkeysLocation\x18\x03 \x01(\tR\fkeysLocation\x12 \n" +
	"\vmaxTokenAge\x18\x04 \x01(\x03R\vmaxTokenAge\x12\x1c\n" +
	"\taudiences\x18\x05 \x03(\tR\taudiences\"\x96\x02\n" +
	"\aSSHAuth\x12 \n" +
	"\vUserIDClaim\x18\x01 \x01(\tR\vUserIDClaim\x12(\n" +
	"\x0fAuthorizedUsers\x18\x02 \x03(\fR\x0fAuthorizedUsers\x12T\n" +
	"\rmachine_users\x18\x03 \x03(\v2/.managementnetfixture.SSHAuth.MachineUsersEntryR\fmachineUsers\x1ai\n" +
	"\x11MachineUsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12>\n" +
	"\x05value\x18\x02 \x01(\v2(.managementnetfixture.MachineUserIndexesR\x05value:\x028\x01\".\n" +
	"\x12MachineUserIndexes\x12\x18\n" +
	"\aindexes\x18\x01 \x03(\rR\aindexes\"\x93\x02\n" +
	"\x05Route\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x18\n" +
	"\aNetwork\x18\x02 \x01(\tR\aNetwork\x12 \n" +
	"\vNetworkType\x18\x03 \x01(\x03R\vNetworkType\x12\x12\n" +
	"\x04Peer\x18\x04 \x01(\tR\x04Peer\x12\x16\n" +
	"\x06Metric\x18\x05 \x01(\x03R\x06Metric\x12\x1e\n" +
	"\n" +
	"Masquerade\x18\x06 \x01(\bR\n" +
	"Masquerade\x12\x14\n" +
	"\x05NetID\x18\a \x01(\tR\x05NetID\x12\x18\n" +
	"\aDomains\x18\b \x03(\tR\aDomains\x12\x1c\n" +
	"\tkeepRoute\x18\t \x01(\bR\tkeepRoute\x12$\n" +
	"\rskipAutoApply\x18\n" +
	" \x01(\bR\rskipAutoApply\"\xf2\x01\n" +
	"\tDNSConfig\x12$\n" +
	"\rServiceEnable\x18\x01 \x01(\bR\rServiceEnable\x12Q\n" +
	"\x10NameServerGroups\x18\x02 \x03(\v2%.managementnetfixture.NameServerGroupR\x10NameServerGroups\x12B\n" +
	"\vCustomZones\x18\x03 \x03(\v2 .managementnetfixture.CustomZoneR\vCustomZones\x12(\n" +
	"\rForwarderPort\x18\x04 \x01(\x03B\x02\x18\x01R\rForwarderPort\"\xc2\x01\n" +
	"\n" +
	"CustomZone\x12\x16\n" +
	"\x06Domain\x18\x01 \x01(\tR\x06Domain\x12<\n" +
	"\aRecords\x18\x02 \x03(\v2\".managementnetfixture.SimpleRecordR\aRecords\x122\n" +
	"\x14SearchDomainDisabled\x18\x03 \x01(\bR\x14SearchDomainDisabled\x12*\n" +
	"\x10NonAuthoritative\x18\x04 \x01(\bR\x10NonAuthoritative\"t\n" +
	"\fSimpleRecord\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\x03R\x04Type\x12\x14\n" +
	"\x05Class\x18\x03 \x01(\tR\x05Class\x12\x10\n" +
	"\x03TTL\x18\x04 \x01(\x03R\x03TTL\x12\x14\n" +
	"\x05RData\x18\x05 \x01(\tR\x05RData\"\xbd\x01\n" +
	"\x0fNameServerGroup\x12B\n" +
	"\vNameServers\x18\x01 \x03(\v2 .managementnetfixture.NameServerR\vNameServers\x12\x18\n" +
	"\aPrimary\x18\x02 \x01(\bR\aPrimary\x12\x18\n" +
	"\aDomains\x18\x03 \x03(\tR\aDomains\x122\n" +
	"\x14SearchDomainsEnabled\x18\x04 \x01(\bR\x14SearchDomainsEnabled\"H\n" +
	"\n" +
	"NameServer\x12\x0e\n" +
	"\x02IP\x18\x01 \x01(\tR\x02IP\x12\x16\n" +
	"\x06NSType\x18\x02 \x01(\x03R\x06NSType\x12\x12\n" +
	"\x04Port\x18\x03 \x01(\x03R\x04Port\"\xa3\x03\n" +
	"\fFirewallRule\x12\x1a\n" +
	"\x06PeerIP\x18\x01 \x01(\tB\x02\x18\x01R\x06PeerIP\x12A\n" +
	"\tDirection\x18\x02 \x01(\x0e2#.managementnetfixture.RuleDirectionR\tDirection\x128\n" +
	"\x06Action\x18\x03 \x01(\x0e2 .managementnetfixture.RuleActionR\x06Action\x12>\n" +
	"\bProtocol\x18\x04 \x01(\x0e2\".managementnetfixture.RuleProtocolR\bProtocol\x12\x12\n" +
	"\x04Port\x18\x05 \x01(\tR\x04Port\x12:\n" +
	"\bPortInfo\x18\x06 \x01(\v2\x1e.managementnetfixture.PortInfoR\bPortInfo\x12\x1a\n" +
	"\bPolicyID\x18\a \x01(\fR\bPolicyID\x12&\n" +
	"\x0ecustomProtocol\x18\b \x01(\rR\x0ecustomProtocol\x12&\n" +
	"\x0esourcePrefixes\x18\t \x03(\fR\x0esourcePrefixes\"\xa0\x01\n" +
	"\bPortInfo\x12\x14\n" +
	"\x04port\x18\x01 \x01(\rH\x00R\x04port\x12<\n" +
	"\x05range\x18\x02 \x01(\v2$.managementnetfixture.PortInfo.RangeH\x00R\x05range\x1a/\n" +
	"\x05Range\x12\x14\n" +
	"\x05start\x18\x01 \x01(\rR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\rR\x03endB\x0f\n" +
	"\rportSelection\"\xa5\x03\n" +
	"\x11RouteFirewallRule\x12\"\n" +
	"\fsourceRanges\x18\x01 \x03(\tR\fsourceRanges\x128\n" +
	"\x06action\x18\x02 \x01(\x0e2 .managementnetfixture.RuleActionR\x06action\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12>\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\".managementnetfixture.RuleProtocolR\bprotocol\x12:\n" +
	"\bportInfo\x18\x05 \x01(\v2\x1e.managementnetfixture.PortInfoR\bportInfo\x12\x1c\n" +
	"\tisDynamic\x18\x06 \x01(\bR\tisDynamic\x12\x18\n" +
	"\adomains\x18\a \x03(\tR\adomains\x12&\n" +
	"\x0ecustomProtocol\x18\b \x01(\rR\x0ecustomProtocol\x12\x1a\n" +
	"\bPolicyID\x18\t \x01(\fR\bPolicyID\x12\x18\n" +
	"\aRouteID\x18\n" +
	" \x01(\tR\aRouteID\"\x90\x02\n" +
	"\x0eForwardingRule\x12>\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\".managementnetfixture.RuleProtocolR\bprotocol\x12H\n" +
	"\x0fdestinationPort\x18\x02 \x01(\v2\x1e.managementnetfixture.PortInfoR\x0fdestinationPort\x12,\n" +
	"\x11translatedAddress\x18\x03 \x01(\fR\x11translatedAddress\x12F\n" +
	"\x0etranslatedPort\x18\x04 \x01(\v2\x1e.managementnetfixture.PortInfoR\x0etranslatedPort\"8\n" +
	"\x0eNetworkAddress\x12\x14\n" +
	"\x05netIP\x18\x01 \x01(\tR\x05netIP\x12\x10\n" +
	"\x03mac\x18\x02 \x01(\tR\x03mac\"\x1e\n" +
	"\x06Checks\x12\x14\n" +
	"\x05Files\x18\x01 \x03(\tR\x05Files\"?\n" +
	"\vEnvironment\x12\x14\n" +
	"\x05cloud\x18\x01 \x01(\tR\x05cloud\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\"\\\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05exist\x18\x02 \x01(\bR\x05exist\x12*\n" +
	"\x10processIsRunning\x18\x03 \x01(\bR\x10processIsRunning\"\xe1\x05\n" +
	"\x05Flags\x12*\n" +
	"\x10rosenpassEnabled\x18\x01 \x01(\bR\x10rosenpassEnabled\x120\n" +
	"\x13rosenpassPermissive\x18\x02 \x01(\bR\x13rosenpassPermissive\x12*\n" +
	"\x10serverSSHAllowed\x18\x03 \x01(\bR\x10serverSSHAllowed\x120\n" +
	"\x13disableClientRoutes\x18\x04 \x01(\bR\x13disableClientRoutes\x120\n" +
	"\x13disableServerRoutes\x18\x05 \x01(\bR\x13disableServerRoutes\x12\x1e\n" +
	"\n" +
	"disableDNS\x18\x06 \x01(\bR\n" +
	"disableDNS\x12(\n" +
	"\x0fdisableFirewall\x18\a \x01(\bR\x0fdisableFirewall\x12&\n" +
	"\x0eblockLANAccess\x18\b \x01(\bR\x0eblockLANAccess\x12\"\n" +
	"\fblockInbound\x18\t \x01(\bR\fblockInbound\x124\n" +
	"\x15lazyConnectionEnabled\x18\n" +
	" \x01(\bR\x15lazyConnectionEnabled\x12$\n" +
	"\renableSSHRoot\x18\v \x01(\bR\renableSSHRoot\x12$\n" +
	"\renableSSHSFTP\x18\f \x01(\bR\renableSSHSFTP\x12B\n" +
	"\x1cenableSSHLocalPortForwarding\x18\r \x01(\bR\x1cenableSSHLocalPortForwarding\x12D\n" +
	"\x1denableSSHRemotePortForwarding\x18\x0e \x01(\bR\x1denableSSHRemotePortForwarding\x12&\n" +
	"\x0edisableSSHAuth\x18\x0f \x01(\bR\x0edisableSSHAuth\x12 \n" +
	"\vdisableIPv6\x18\x10 \x01(\bR\vdisableIPv6\"\xe4\x05\n" +
	"\x0ePeerSystemMeta\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04goOS\x18\x02 \x01(\tR\x04goOS\x12\x16\n" +
	"\x06kernel\x18\x03 \x01(\tR\x06kernel\x12\x12\n" +
	"\x04core\x18\x04 \x01(\tR\x04core\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x0e\n" +
	"\x02OS\x18\x06 \x01(\tR\x02OS\x12&\n" +
	"\x0enetbirdVersion\x18\a \x01(\tR\x0enetbirdVersion\x12\x1c\n" +
	"\tuiVersion\x18\b \x01(\tR\tuiVersion\x12$\n" +
	"\rkernelVersion\x18\t \x01(\tR\rkernelVersion\x12\x1c\n" +
	"\tOSVersion\x18\n" +
	" \x01(\tR\tOSVersion\x12P\n" +
	"\x10networkAddresses\x18\v \x03(\v2$.managementnetfixture.NetworkAddressR\x10networkAddresses\x12(\n" +
	"\x0fsysSerialNumber\x18\f \x01(\tR\x0fsysSerialNumber\x12&\n" +
	"\x0esysProductName\x18\r \x01(\tR\x0esysProductName\x12(\n" +
	"\x0fsysManufacturer\x18\x0e \x01(\tR\x0fsysManufacturer\x12C\n" +
	"\venvironment\x18\x0f \x01(\v2!.managementnetfixture.EnvironmentR\venvironment\x120\n" +
	"\x05files\x18\x10 \x03(\v2\x1a.managementnetfixture.FileR\x05files\x121\n" +
	"\x05flags\x18\x11 \x01(\v2\x1b.managementnetfixture.FlagsR\x05flags\x12H\n" +
	"\fcapabilities\x18\x12 \x03(\x0e2$.managementnetfixture.PeerCapabilityR\fcapabilities*L\n" +
	"\fRuleProtocol\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03ALL\x10\x01\x12\a\n" +
	"\x03TCP\x10\x02\x12\a\n" +
	"\x03UDP\x10\x03\x12\b\n" +
	"\x04ICMP\x10\x04\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x05* \n" +
	"\rRuleDirection\x12\x06\n" +
	"\x02IN\x10\x00\x12\a\n" +
	"\x03OUT\x10\x01*\"\n" +
	"\n" +
	"RuleAction\x12\n" +
	"\n" +
	"\x06ACCEPT\x10\x00\x12\b\n" +
	"\x04DROP\x10\x01*l\n" +
	"\x0ePeerCapability\x12\x19\n" +
	"\x15PeerCapabilityUnknown\x10\x00\x12 \n" +
	"\x1cPeerCapabilitySourcePrefixes\x10\x01\x12\x1d\n" +
	"\x19PeerCapabilityIPv6Overlay\x10\x02BOZMgithub.com/soypat/embedpb/internal/fixture/managementnetstock;managementnetpbb\x06proto3"

var (
	file_management_net_proto_rawDescOnce sync.Once
	file_management_net_proto_rawDescData []byte
)

func file_management_net_proto_rawDescGZIP() []byte {
	file_management_net_proto_rawDescOnce.Do(func() {
		file_management_net_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_net_proto_rawDesc), len(file_management_net_proto_rawDesc)))
	})
	return file_management_net_proto_rawDescData
}

var file_management_net_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_management_net_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_management_net_proto_goTypes = []any{
	(RuleProtocol)(0),             // 0: managementnetfixture.RuleProtocol
	(RuleDirection)(0),            // 1: managementnetfixture.RuleDirection
	(RuleAction)(0),               // 2: managementnetfixture.RuleAction
	(PeerCapability)(0),           // 3: managementnetfixture.PeerCapability
	(HostConfig_Protocol)(0),      // 4: managementnetfixture.HostConfig.Protocol
	(*SyncResponse)(nil),          // 5: managementnetfixture.SyncResponse
	(*NetbirdConfig)(nil),         // 6: managementnetfixture.NetbirdConfig
	(*HostConfig)(nil),            // 7: managementnetfixture.HostConfig
	(*ProtectedHostConfig)(nil),   // 8: managementnetfixture.ProtectedHostConfig
	(*RelayConfig)(nil),           // 9: managementnetfixture.RelayConfig
	(*FlowConfig)(nil),            // 10: managementnetfixture.FlowConfig
	(*NetworkMap)(nil),            // 11: managementnetfixture.NetworkMap
	(*PeerConfig)(nil),            // 12: managementnetfixture.PeerConfig
	(*AutoUpdateSettings)(nil),    // 13: managementnetfixture.AutoUpdateSettings
	(*RemotePeerConfig)(nil),      // 14: managementnetfixture.RemotePeerConfig
	(*SSHConfig)(nil),             // 15: managementnetfixture.SSHConfig
	(*JWTConfig)(nil),             // 16: managementnetfixture.JWTConfig
	(*SSHAuth)(nil),               // 17: managementnetfixture.SSHAuth
	(*MachineUserIndexes)(nil),    // 18: managementnetfixture.MachineUserIndexes
	(*Route)(nil),                 // 19: managementnetfixture.Route
	(*DNSConfig)(nil),             // 20: managementnetfixture.DNSConfig
	(*CustomZone)(nil),            // 21: managementnetfixture.CustomZone
	(*SimpleRecord)(nil),          // 22: managementnetfixture.SimpleRecord
	(*NameServerGroup)(nil),       // 23: managementnetfixture.NameServerGroup
	(*NameServer)(nil),            // 24: managementnetfixture.NameServer
	(*FirewallRule)(nil),          // 25: managementnetfixture.FirewallRule
	(*PortInfo)(nil),              // 26: managementnetfixture.PortInfo
	(*RouteFirewallRule)(nil),     // 27: managementnetfixture.RouteFirewallRule
	(*ForwardingRule)(nil),        // 28: managementnetfixture.ForwardingRule
	(*NetworkAddress)(nil),        // 29: managementnetfixture.NetworkAddress
	(*Checks)(nil),                // 30: managementnetfixture.Checks
	(*Environment)(nil),           // 31: managementnetfixture.Environment
	(*File)(nil),                  // 32: managementnetfixture.File
	(*Flags)(nil),                 // 33: managementnetfixture.Flags
	(*PeerSystemMeta)(nil),        // 34: managementnetfixture.PeerSystemMeta
	nil,                           // 35: managementnetfixture.SSHAuth.MachineUsersEntry
	(*PortInfo_Range)(nil),        // 36: managementnetfixture.PortInfo.Range
	(*timestamppb.Timestamp)(nil), // 37: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 38: google.protobuf.Duration
}
var file_management_net_proto_depIdxs = []int32{
	6,  // 0: managementnetfixture.SyncResponse.netbirdConfig:type_name -> managementnetfixture.NetbirdConfig
	11, // 1: managementnetfixture.SyncResponse.NetworkMap:type_name -> managementnetfixture.NetworkMap
	37, // 2: managementnetfixture.SyncResponse.sessionExpiresAt:type_name -> google.protobuf.Timestamp
	7,  // 3: managementnetfixture.NetbirdConfig.stuns:type_name -> managementnetfixture.HostConfig
	8,  // 4: managementnetfixture.NetbirdConfig.turns:type_name -> managementnetfixture.ProtectedHostConfig
	7,  // 5: managementnetfixture.NetbirdConfig.signal:type_name -> managementnetfixture.HostConfig
	9,  // 6: managementnetfixture.NetbirdConfig.relay:type_name -> managementnetfixture.RelayConfig
	10, // 7: managementnetfixture.NetbirdConfig.flow:type_name -> managementnetfixture.FlowConfig
	4,  // 8: managementnetfixture.HostConfig.protocol:type_name -> managementnetfixture.HostConfig.Protocol
	7,  // 9: managementnetfixture.ProtectedHostConfig.hostConfig:type_name -> managementnetfixture.HostConfig
	38, // 10: managementnetfixture.FlowConfig.interval:type_name -> google.protobuf.Duration
	12, // 11: managementnetfixture.NetworkMap.peerConfig:type_name -> managementnetfixture.PeerConfig
	14, // 12: managementnetfixture.NetworkMap.remotePeers:type_name -> managementnetfixture.RemotePeerConfig
	19, // 13: managementnetfixture.NetworkMap.Routes:type_name -> managementnetfixture.Route
	20, // 14: managementnetfixture.NetworkMap.DNSConfig:type_name -> managementnetfixture.DNSConfig
	14, // 15: managementnetfixture.NetworkMap.offlinePeers:type_name -> managementnetfixture.RemotePeerConfig
	25, // 16: managementnetfixture.NetworkMap.FirewallRules:type_name -> managementnetfixture.FirewallRule
	27, // 17: managementnetfixture.NetworkMap.routesFirewallRules:type_name -> managementnetfixture.RouteFirewallRule
	28, // 18: managementnetfixture.NetworkMap.forwardingRules:type_name -> managementnetfixture.ForwardingRule
	17, // 19: managementnetfixture.NetworkMap.sshAuth:type_name -> managementnetfixture.SSHAuth
	15, // 20: managementnetfixture.PeerConfig.sshConfig:type_name -> managementnetfixture.SSHConfig
	13, // 21: managementnetfixture.PeerConfig.autoUpdate:type_name -> managementnetfixture.AutoUpdateSettings
	15, // 22: managementnetfixture.RemotePeerConfig.sshConfig:type_name -> managementnetfixture.SSHConfig
	16, // 23: managementnetfixture.SSHConfig.jwtConfig:type_name -> managementnetfixture.JWTConfig
	35, // 24: managementnetfixture.SSHAuth.machine_users:type_name -> managementnetfixture.SSHAuth.MachineUsersEntry
	23, // 25: managementnetfixture.DNSConfig.NameServerGroups:type_name -> managementnetfixture.NameServerGroup
	21, // 26: managementnetfixture.DNSConfig.CustomZones:type_name -> managementnetfixture.CustomZone
	22, // 27: managementnetfixture.CustomZone.Records:type_name -> managementnetfixture.SimpleRecord
	24, // 28: managementnetfixture.NameServerGroup.NameServers:type_name -> managementnetfixture.NameServer
	1,  // 29: managementnetfixture.FirewallRule.Direction:type_name -> managementnetfixture.RuleDirection
	2,  // 30: managementnetfixture.FirewallRule.Action:type_name -> managementnetfixture.RuleAction
	0,  // 31: managementnetfixture.FirewallRule.Protocol:type_name -> managementnetfixture.RuleProtocol
	26, // 32: managementnetfixture.FirewallRule.PortInfo:type_name -> managementnetfixture.PortInfo
	36, // 33: managementnetfixture.PortInfo.range:type_name -> managementnetfixture.PortInfo.Range
	2,  // 34: managementnetfixture.RouteFirewallRule.action:type_name -> managementnetfixture.RuleAction
	0,  // 35: managementnetfixture.RouteFirewallRule.protocol:type_name -> managementnetfixture.RuleProtocol
	26, // 36: managementnetfixture.RouteFirewallRule.portInfo:type_name -> managementnetfixture.PortInfo
	0,  // 37: managementnetfixture.ForwardingRule.protocol:type_name -> managementnetfixture.RuleProtocol
	26, // 38: managementnetfixture.ForwardingRule.destinationPort:type_name -> managementnetfixture.PortInfo
	26, // 39: managementnetfixture.ForwardingRule.translatedPort:type_name -> managementnetfixture.PortInfo
	29, // 40: managementnetfixture.PeerSystemMeta.networkAddresses:type_name -> managementnetfixture.NetworkAddress
	31, // 41: managementnetfixture.PeerSystemMeta.environment:type_name -> managementnetfixture.Environment
	32, // 42: managementnetfixture.PeerSystemMeta.files:type_name -> managementnetfixture.File
	33, // 43: managementnetfixture.PeerSystemMeta.flags:type_name -> managementnetfixture.Flags
	3,  // 44: managementnetfixture.PeerSystemMeta.capabilities:type_name -> managementnetfixture.PeerCapability
	18, // 45: managementnetfixture.SSHAuth.MachineUsersEntry.value:type_name -> managementnetfixture.MachineUserIndexes
	46, // [46:46] is the sub-list for method output_type
	46, // [46:46] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_management_net_proto_init() }
func file_management_net_proto_init() {
	if File_management_net_proto != nil {
		return
	}
	file_management_net_proto_msgTypes[21].OneofWrappers = []any{
		(*PortInfo_Port)(nil),
		(*PortInfo_Range_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_net_proto_rawDesc), len(file_management_net_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_management_net_proto_goTypes,
		DependencyIndexes: file_management_net_proto_depIdxs,
		EnumInfos:         file_management_net_proto_enumTypes,
		MessageInfos:      file_management_net_proto_msgTypes,
	}.Build()
	File_management_net_proto = out.File
	file_management_net_proto_goTypes = nil
	file_management_net_proto_depIdxs = nil
}
