// Package pbruntime is the support code for files generated by embedpb with
// the -runtime flag. Without that flag the generator emits a private copy of
// everything here into the generated file, and generated packages depend on
// nothing but google.golang.org/protobuf.
//
// Nothing in this package uses reflect: Message satisfies
// protoreflect.Message with hand-written protoiface.Methods, which is what
// keeps the protobuf runtime off the coder it builds by reflecting over
// generated structs — the path TinyGo cannot run.
package pbruntime

import (
	"bytes"
	"encoding/base64"
	"fmt"

	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoiface"
)

// Message is the protoreflect.Message a generated message returns from
// ProtoReflect. It carries the message's hand-written codec as funcs, so the
// protobuf runtime can marshal, size, unmarshal, merge and compare without ever
// describing the message. Only the methods the fast path calls are implemented;
// the rest panic, which is how a caller learns it reached the reflective API on
// a type that has no descriptors.
type Message struct {
	MarshalFn    func([]byte) ([]byte, error)
	SizeFn       func() int
	UnmarshalFn  func([]byte) error
	Iface        protoreflect.ProtoMessage
	Valid        bool
	NewFn        func() protoreflect.Message
	GetUnknownFn func() protoreflect.RawFields
	SetUnknownFn func(protoreflect.RawFields)
}

var _ protoreflect.Message = Message{}

func (r Message) ProtoMethods() *protoiface.Methods    { return &Methods }
func (r Message) Interface() protoreflect.ProtoMessage { return r.Iface }
func (r Message) IsValid() bool                        { return r.Valid }
func (r Message) New() protoreflect.Message            { return r.NewFn() }
func (r Message) GetUnknown() protoreflect.RawFields   { return r.GetUnknownFn() }
func (r Message) SetUnknown(f protoreflect.RawFields)  { r.SetUnknownFn(f) }

func canary(m string) string {
	return "CANARY: protoreflect.Message." + m + " called on reflection-free message"
}

func (r Message) Descriptor() protoreflect.MessageDescriptor { panic(canary("Descriptor")) }
func (r Message) Type() protoreflect.MessageType             { panic(canary("Type")) }
func (r Message) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(canary("Range"))
}
func (r Message) Has(protoreflect.FieldDescriptor) bool               { panic(canary("Has")) }
func (r Message) Clear(protoreflect.FieldDescriptor)                  { panic(canary("Clear")) }
func (r Message) Get(protoreflect.FieldDescriptor) protoreflect.Value { panic(canary("Get")) }
func (r Message) Set(protoreflect.FieldDescriptor, protoreflect.Value) {
	panic(canary("Set"))
}
func (r Message) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(canary("Mutable"))
}
func (r Message) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(canary("NewField"))
}
func (r Message) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(canary("WhichOneof"))
}

// Methods is the fast path proto.Marshal and friends take instead of building a
// reflection coder. Merge and Equal go through the wire form, which is correct
// for messages without extensions or unknown-field merging subtleties.
var Methods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: in.Message.(Message).SizeFn()}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		b, err := in.Message.(Message).MarshalFn(in.Buf)
		return protoiface.MarshalOutput{Buf: b}, err
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := in.Message.(Message).UnmarshalFn(in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		src := in.Source.(Message)
		dst := in.Destination.(Message)
		sb, _ := src.MarshalFn(nil)
		if err := dst.UnmarshalFn(sb); err != nil {
			return protoiface.MergeOutput{}
		}
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(in protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		a, ok1 := in.MessageA.(Message)
		b, ok2 := in.MessageB.(Message)
		if !ok1 || !ok2 {
			return protoiface.EqualOutput{Equal: false}
		}
		ab, _ := a.MarshalFn(nil)
		bb, _ := b.MarshalFn(nil)
		return protoiface.EqualOutput{Equal: bytes.Equal(ab, bb)}
	},
}

// Bool is the wire encoding of a bool.
func Bool(v bool) uint64 {
	if v {
		return 1
	}
	return 0
}

// --- protojson-compatible JSON helpers ---

// JSONEndObj closes an object, replacing the trailing comma left by the last
// emitted field if there was one.
func JSONEndObj(dst []byte) []byte {
	if n := len(dst); n > 0 && dst[n-1] == ',' {
		dst[n-1] = '}'
		return dst
	}
	return append(dst, '}')
}

func jsonHexDigit(b byte) byte {
	if b < 10 {
		return '0' + b
	}
	return 'a' + b - 10
}

// JSONString appends s as a quoted JSON string.
func JSONString(dst []byte, s string) []byte {
	dst = append(dst, '"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch c {
		case '"':
			dst = append(dst, '\\', '"')
		case '\\':
			dst = append(dst, '\\', '\\')
		case '\n':
			dst = append(dst, '\\', 'n')
		case '\r':
			dst = append(dst, '\\', 'r')
		case '\t':
			dst = append(dst, '\\', 't')
		default:
			if c < 0x20 {
				dst = append(dst, '\\', 'u', '0', '0', jsonHexDigit(c>>4), jsonHexDigit(c&0xf))
			} else {
				dst = append(dst, c)
			}
		}
	}
	return append(dst, '"')
}

// JSONBytes appends b as a quoted standard-base64 JSON string.
func JSONBytes(dst []byte, b []byte) []byte {
	dst = append(dst, '"')
	dst = base64.StdEncoding.AppendEncode(dst, b)
	return append(dst, '"')
}

// JSONNanoFrac formats sub-second nanos as protojson does: trailing zero groups
// of three trimmed, leaving 3, 6, or 9 fractional digits.
func JSONNanoFrac(nanos int32) string {
	buf := fmt.Sprintf("%09d", nanos)
	n := 9
	for n > 3 && buf[n-1] == '0' && buf[n-2] == '0' && buf[n-3] == '0' {
		n -= 3
	}
	return buf[:n]
}
