// Code generated by embedpb. DO NOT EDIT.
// Reflection-free, TinyGo-safe proto codec: hand-written protoiface.Methods
// keep google.golang.org/protobuf on its fast path (no reflect coder).
package shapespb

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"math"
	"sort"
	"strconv"

	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/runtime/protoiface"
)

var _ = math.Float32bits
var _ = sort.Strings
var _ = fmt.Sprintf
var _ = bytes.Equal
var _ = strconv.AppendInt
var _ = base64.StdEncoding

type Kind int32

const (
	Kind_KIND_UNKNOWN Kind = 0
	Kind_KIND_A       Kind = 1
	Kind_KIND_B       Kind = 2
)

var Kind_name = map[int32]string{
	0: "KIND_UNKNOWN",
	1: "KIND_A",
	2: "KIND_B",
}

func (x Kind) String() string {
	if s, ok := Kind_name[int32(x)]; ok {
		return s
	}
	return fmt.Sprintf("Kind(%d)", int32(x))
}
func (x Kind) Enum() *Kind { p := new(Kind); *p = x; return p }

type isShapes_Choice interface{ isShapes_Choice() }
type Shapes_ChoiceMsg struct{ ChoiceMsg *Inner }

func (*Shapes_ChoiceMsg) isShapes_Choice() {}

type Shapes_ChoiceNum struct{ ChoiceNum uint32 }

func (*Shapes_ChoiceNum) isShapes_Choice() {}

type Inner struct {
	A             uint32
	B             string
	unknownFields protoreflect.RawFields
}

func (m *Inner) Reset()         { *m = Inner{} }
func (m *Inner) String() string { return fmt.Sprintf("Inner{}") }
func (m *Inner) ProtoMessage()  {}
func (m *Inner) GetA() uint32 {
	if m != nil {
		return m.A
	}
	return 0
}
func (m *Inner) GetB() string {
	if m != nil {
		return m.B
	}
	return ""
}

func (m *Inner) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&Inner{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *Inner) sizeField() int {
	n := 0
	if m.A != 0 {
		n += protowire.SizeTag(1) + protowire.SizeVarint(uint64(m.A))
	}
	if m.B != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.B))
	}
	n += len(m.unknownFields)
	return n
}

func (m *Inner) marshalAppend(b []byte) ([]byte, error) {
	if m.A != 0 {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.A))
	}
	if m.B != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.B)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *Inner) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.A = uint32(v)
		case 2:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.B = v
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *Inner) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *Inner) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"a\":"...)
	dst = strconv.AppendUint(dst, uint64(m.A), 10)
	dst = append(dst, ',')
	dst = append(dst, "\"b\":"...)
	dst = jsonString(dst, m.B)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type Shapes struct {
	I32           int32
	I64           int64
	U32           uint32
	U64           uint64
	S32           int32
	S64           int64
	F32           uint32
	F64           uint64
	Fl            float32
	Db            float64
	Flag          bool
	Str           string
	Blob          []byte
	Kind          Kind
	Inner         *Inner
	Nums          []uint32
	Names         []string
	Inners        []*Inner
	Choice        isShapes_Choice
	Entries       map[string]*Inner
	OptionalFlag  *bool
	OptionalName  *string
	OptionalBlob  []byte
	unknownFields protoreflect.RawFields
}

func (m *Shapes) Reset()         { *m = Shapes{} }
func (m *Shapes) String() string { return fmt.Sprintf("Shapes{}") }
func (m *Shapes) ProtoMessage()  {}
func (m *Shapes) GetI32() int32 {
	if m != nil {
		return m.I32
	}
	return 0
}
func (m *Shapes) GetI64() int64 {
	if m != nil {
		return m.I64
	}
	return 0
}
func (m *Shapes) GetU32() uint32 {
	if m != nil {
		return m.U32
	}
	return 0
}
func (m *Shapes) GetU64() uint64 {
	if m != nil {
		return m.U64
	}
	return 0
}
func (m *Shapes) GetS32() int32 {
	if m != nil {
		return m.S32
	}
	return 0
}
func (m *Shapes) GetS64() int64 {
	if m != nil {
		return m.S64
	}
	return 0
}
func (m *Shapes) GetF32() uint32 {
	if m != nil {
		return m.F32
	}
	return 0
}
func (m *Shapes) GetF64() uint64 {
	if m != nil {
		return m.F64
	}
	return 0
}
func (m *Shapes) GetFl() float32 {
	if m != nil {
		return m.Fl
	}
	return 0
}
func (m *Shapes) GetDb() float64 {
	if m != nil {
		return m.Db
	}
	return 0
}
func (m *Shapes) GetFlag() bool {
	if m != nil {
		return m.Flag
	}
	return false
}
func (m *Shapes) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}
func (m *Shapes) GetBlob() []byte {
	if m != nil {
		return m.Blob
	}
	return nil
}
func (m *Shapes) GetKind() Kind {
	if m != nil {
		return m.Kind
	}
	return Kind(0)
}
func (m *Shapes) GetInner() *Inner {
	if m != nil {
		return m.Inner
	}
	return nil
}
func (m *Shapes) GetNums() []uint32 {
	if m != nil {
		return m.Nums
	}
	return nil
}
func (m *Shapes) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}
func (m *Shapes) GetInners() []*Inner {
	if m != nil {
		return m.Inners
	}
	return nil
}
func (m *Shapes) GetChoice() isShapes_Choice {
	if m != nil {
		return m.Choice
	}
	return nil
}
func (m *Shapes) GetChoiceMsg() *Inner {
	if v, ok := m.GetChoice().(*Shapes_ChoiceMsg); ok {
		return v.ChoiceMsg
	}
	return nil
}
func (m *Shapes) GetChoiceNum() uint32 {
	if v, ok := m.GetChoice().(*Shapes_ChoiceNum); ok {
		return v.ChoiceNum
	}
	return 0
}
func (m *Shapes) GetEntries() map[string]*Inner {
	if m != nil {
		return m.Entries
	}
	return nil
}
func (m *Shapes) GetOptionalFlag() bool {
	if m != nil && m.OptionalFlag != nil {
		return *m.OptionalFlag
	}
	return false
}
func (m *Shapes) GetOptionalName() string {
	if m != nil && m.OptionalName != nil {
		return *m.OptionalName
	}
	return ""
}
func (m *Shapes) GetOptionalBlob() []byte {
	if m != nil {
		return m.OptionalBlob
	}
	return nil
}

func (m *Shapes) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&Shapes{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *Shapes) sizeField() int {
	n := 0
	if m.I32 != 0 {
		n += protowire.SizeTag(1) + protowire.SizeVarint(uint64(int64(m.I32)))
	}
	if m.I64 != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(m.I64))
	}
	if m.U32 != 0 {
		n += protowire.SizeTag(3) + protowire.SizeVarint(uint64(m.U32))
	}
	if m.U64 != 0 {
		n += protowire.SizeTag(4) + protowire.SizeVarint(m.U64)
	}
	if m.S32 != 0 {
		n += protowire.SizeTag(5) + protowire.SizeVarint(protowire.EncodeZigZag(int64(m.S32)))
	}
	if m.S64 != 0 {
		n += protowire.SizeTag(6) + protowire.SizeVarint(protowire.EncodeZigZag(m.S64))
	}
	if m.F32 != 0 {
		n += protowire.SizeTag(7) + protowire.SizeFixed32()
	}
	if m.F64 != 0 {
		n += protowire.SizeTag(8) + protowire.SizeFixed64()
	}
	if m.Fl != 0 {
		n += protowire.SizeTag(9) + protowire.SizeFixed32()
	}
	if m.Db != 0 {
		n += protowire.SizeTag(10) + protowire.SizeFixed64()
	}
	if m.Flag {
		n += protowire.SizeTag(11) + protowire.SizeVarint(embedBool(m.Flag))
	}
	if m.Str != "" {
		n += protowire.SizeTag(12) + protowire.SizeBytes(len(m.Str))
	}
	if len(m.Blob) > 0 {
		n += protowire.SizeTag(13) + protowire.SizeBytes(len(m.Blob))
	}
	if m.Kind != 0 {
		n += protowire.SizeTag(14) + protowire.SizeVarint(uint64(int64(m.Kind)))
	}
	if m.Inner != nil {
		n += protowire.SizeTag(15) + protowire.SizeBytes(m.Inner.sizeField())
	}
	if len(m.Nums) > 0 {
		pn := 0
		for _, v := range m.Nums {
			pn += protowire.SizeVarint(uint64(v))
		}
		n += protowire.SizeTag(16) + protowire.SizeBytes(pn)
	}
	for _, v := range m.Names {
		n += protowire.SizeTag(17) + protowire.SizeBytes(len(v))
	}
	for _, v := range m.Inners {
		n += protowire.SizeTag(18) + protowire.SizeBytes(v.sizeField())
	}
	switch c := m.Choice.(type) {
	case *Shapes_ChoiceMsg:
		_ = c
		n += protowire.SizeTag(19) + protowire.SizeBytes(c.ChoiceMsg.sizeField())
	case *Shapes_ChoiceNum:
		_ = c
		n += protowire.SizeTag(20) + protowire.SizeVarint(uint64(c.ChoiceNum))
	}
	for k, v := range m.Entries {
		n += protowire.SizeTag(21) + protowire.SizeBytes(mapEntry_Shapes_Entries(k, v))
	}
	if m.OptionalFlag != nil {
		n += protowire.SizeTag(22) + protowire.SizeVarint(embedBool(*m.OptionalFlag))
	}
	if m.OptionalName != nil {
		n += protowire.SizeTag(23) + protowire.SizeBytes(len(*m.OptionalName))
	}
	if m.OptionalBlob != nil {
		n += protowire.SizeTag(24) + protowire.SizeBytes(len(m.OptionalBlob))
	}
	n += len(m.unknownFields)
	return n
}

func (m *Shapes) marshalAppend(b []byte) ([]byte, error) {
	if m.I32 != 0 {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(int64(m.I32)))
	}
	if m.I64 != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.I64))
	}
	if m.U32 != 0 {
		b = protowire.AppendTag(b, 3, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.U32))
	}
	if m.U64 != 0 {
		b = protowire.AppendTag(b, 4, protowire.VarintType)
		b = protowire.AppendVarint(b, m.U64)
	}
	if m.S32 != 0 {
		b = protowire.AppendTag(b, 5, protowire.VarintType)
		b = protowire.AppendVarint(b, protowire.EncodeZigZag(int64(m.S32)))
	}
	if m.S64 != 0 {
		b = protowire.AppendTag(b, 6, protowire.VarintType)
		b = protowire.AppendVarint(b, protowire.EncodeZigZag(m.S64))
	}
	if m.F32 != 0 {
		b = protowire.AppendTag(b, 7, protowire.Fixed32Type)
		b = protowire.AppendFixed32(b, m.F32)
	}
	if m.F64 != 0 {
		b = protowire.AppendTag(b, 8, protowire.Fixed64Type)
		b = protowire.AppendFixed64(b, m.F64)
	}
	if m.Fl != 0 {
		b = protowire.AppendTag(b, 9, protowire.Fixed32Type)
		b = protowire.AppendFixed32(b, math.Float32bits(m.Fl))
	}
	if m.Db != 0 {
		b = protowire.AppendTag(b, 10, protowire.Fixed64Type)
		b = protowire.AppendFixed64(b, math.Float64bits(m.Db))
	}
	if m.Flag {
		b = protowire.AppendTag(b, 11, protowire.VarintType)
		b = protowire.AppendVarint(b, embedBool(m.Flag))
	}
	if m.Str != "" {
		b = protowire.AppendTag(b, 12, protowire.BytesType)
		b = protowire.AppendString(b, m.Str)
	}
	if len(m.Blob) > 0 {
		b = protowire.AppendTag(b, 13, protowire.BytesType)
		b = protowire.AppendBytes(b, m.Blob)
	}
	if m.Kind != 0 {
		b = protowire.AppendTag(b, 14, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(int64(m.Kind)))
	}
	if m.Inner != nil {
		sub, _ := m.Inner.marshalAppend(nil)
		b = protowire.AppendTag(b, 15, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	if len(m.Nums) > 0 {
		var packed []byte
		for _, v := range m.Nums {
			packed = protowire.AppendVarint(packed, uint64(v))
		}
		b = protowire.AppendTag(b, 16, protowire.BytesType)
		b = protowire.AppendBytes(b, packed)
	}
	for _, v := range m.Names {
		b = protowire.AppendTag(b, 17, protowire.BytesType)
		b = protowire.AppendString(b, v)
	}
	for _, v := range m.Inners {
		sub, _ := v.marshalAppend(nil)
		b = protowire.AppendTag(b, 18, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	switch c := m.Choice.(type) {
	case *Shapes_ChoiceMsg:
		sub, _ := c.ChoiceMsg.marshalAppend(nil)
		b = protowire.AppendTag(b, 19, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	case *Shapes_ChoiceNum:
		b = protowire.AppendTag(b, 20, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(c.ChoiceNum))
	}
	if len(m.Entries) > 0 {
		keys := make([]string, 0, len(m.Entries))
		for k := range m.Entries {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
		for _, k := range keys {
			b = protowire.AppendTag(b, 21, protowire.BytesType)
			b = protowire.AppendBytes(b, appendEntry_Shapes_Entries(nil, k, m.Entries[k]))
		}
	}
	if m.OptionalFlag != nil {
		b = protowire.AppendTag(b, 22, protowire.VarintType)
		b = protowire.AppendVarint(b, embedBool(*m.OptionalFlag))
	}
	if m.OptionalName != nil {
		b = protowire.AppendTag(b, 23, protowire.BytesType)
		b = protowire.AppendString(b, *m.OptionalName)
	}
	if m.OptionalBlob != nil {
		b = protowire.AppendTag(b, 24, protowire.BytesType)
		b = protowire.AppendBytes(b, m.OptionalBlob)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *Shapes) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.I32 = int32(v)
		case 2:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.I64 = int64(v)
		case 3:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.U32 = uint32(v)
		case 4:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.U64 = v
		case 5:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.S32 = int32(protowire.DecodeZigZag(v))
		case 6:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.S64 = protowire.DecodeZigZag(v)
		case 7:
			v, k := protowire.ConsumeFixed32(b)
			consumed = k
			m.F32 = v
		case 8:
			v, k := protowire.ConsumeFixed64(b)
			consumed = k
			m.F64 = v
		case 9:
			v, k := protowire.ConsumeFixed32(b)
			consumed = k
			m.Fl = math.Float32frombits(v)
		case 10:
			v, k := protowire.ConsumeFixed64(b)
			consumed = k
			m.Db = math.Float64frombits(v)
		case 11:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Flag = v != 0
		case 12:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.Str = v
		case 13:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.Blob = append([]byte(nil), v...)
		case 14:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Kind = Kind(v)
		case 15:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				mm := &Inner{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				m.Inner = mm
			}
		case 16:
			if typ == protowire.BytesType {
				pk, k := protowire.ConsumeBytes(b)
				consumed = k
				for len(pk) > 0 {
					v, kk := protowire.ConsumeVarint(pk)
					if kk < 0 {
						return protowire.ParseError(kk)
					}
					m.Nums = append(m.Nums, uint32(v))
					pk = pk[kk:]
				}
			} else {
				v, k := protowire.ConsumeVarint(b)
				consumed = k
				m.Nums = append(m.Nums, uint32(v))
			}
		case 17:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.Names = append(m.Names, v)
		case 18:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				var mv *Inner
				mm := &Inner{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				mv = mm
				m.Inners = append(m.Inners, mv)
			}
		case 19:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				var mv *Inner
				mm := &Inner{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				mv = mm
				m.Choice = &Shapes_ChoiceMsg{ChoiceMsg: mv}
			}
		case 20:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Choice = &Shapes_ChoiceNum{ChoiceNum: uint32(v)}
		case 21:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				if m.Entries == nil {
					m.Entries = make(map[string]*Inner)
				}
				mk, mv := decodeEntry_Shapes_Entries(v)
				m.Entries[mk] = mv
			}
		case 22:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			tmp := v != 0
			m.OptionalFlag = &tmp
		case 23:
			v, k := protowire.ConsumeString(b)
			consumed = k
			tmp := v
			m.OptionalName = &tmp
		case 24:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			m.OptionalBlob = append([]byte(nil), v...)
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func mapEntry_Shapes_Entries(k string, v *Inner) int {
	n := 0
	if k != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(k))
	}
	if v != nil {
		n += protowire.SizeTag(2) + protowire.SizeBytes(v.sizeField())
	}
	return n
}
func appendEntry_Shapes_Entries(b []byte, k string, v *Inner) []byte {
	if k != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, k)
	}
	if v != nil {
		sub, _ := v.marshalAppend(nil)
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	return b
}
func decodeEntry_Shapes_Entries(b []byte) (string, *Inner) {
	var k string
	var v *Inner
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			vv, kk := protowire.ConsumeString(b)
			consumed = kk
			k = vv
		case 2:
			vv, kk := protowire.ConsumeBytes(b)
			consumed = kk
			mm := &Inner{}
			_ = mm.unmarshalMsg(vv)
			v = mm
		default:
			consumed = protowire.ConsumeFieldValue(num, typ, b)
		}
		if consumed < 0 {
			break
		}
		b = b[consumed:]
	}
	if v == nil {
		v = &Inner{}
	}
	return k, v
}

func (m *Shapes) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *Shapes) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"i32\":"...)
	dst = strconv.AppendInt(dst, int64(m.I32), 10)
	dst = append(dst, ',')
	dst = append(dst, "\"i64\":"...)
	dst = append(dst, '"')
	dst = strconv.AppendInt(dst, int64(m.I64), 10)
	dst = append(dst, '"')
	dst = append(dst, ',')
	dst = append(dst, "\"u32\":"...)
	dst = strconv.AppendUint(dst, uint64(m.U32), 10)
	dst = append(dst, ',')
	dst = append(dst, "\"u64\":"...)
	dst = append(dst, '"')
	dst = strconv.AppendUint(dst, uint64(m.U64), 10)
	dst = append(dst, '"')
	dst = append(dst, ',')
	dst = append(dst, "\"s32\":"...)
	dst = strconv.AppendInt(dst, int64(m.S32), 10)
	dst = append(dst, ',')
	dst = append(dst, "\"s64\":"...)
	dst = append(dst, '"')
	dst = strconv.AppendInt(dst, int64(m.S64), 10)
	dst = append(dst, '"')
	dst = append(dst, ',')
	dst = append(dst, "\"f32\":"...)
	dst = strconv.AppendUint(dst, uint64(m.F32), 10)
	dst = append(dst, ',')
	dst = append(dst, "\"f64\":"...)
	dst = append(dst, '"')
	dst = strconv.AppendUint(dst, uint64(m.F64), 10)
	dst = append(dst, '"')
	dst = append(dst, ',')
	dst = append(dst, "\"fl\":"...)
	dst = strconv.AppendFloat(dst, float64(m.Fl), 'g', -1, 32)
	dst = append(dst, ',')
	dst = append(dst, "\"db\":"...)
	dst = strconv.AppendFloat(dst, m.Db, 'g', -1, 64)
	dst = append(dst, ',')
	dst = append(dst, "\"flag\":"...)
	dst = strconv.AppendBool(dst, m.Flag)
	dst = append(dst, ',')
	dst = append(dst, "\"str\":"...)
	dst = jsonString(dst, m.Str)
	dst = append(dst, ',')
	dst = append(dst, "\"blob\":"...)
	dst = jsonBytes(dst, m.Blob)
	dst = append(dst, ',')
	dst = append(dst, "\"kind\":"...)
	if s, ok := Kind_name[int32(m.Kind)]; ok {
		dst = jsonString(dst, s)
	} else {
		dst = strconv.AppendInt(dst, int64(m.Kind), 10)
	}
	dst = append(dst, ',')
	dst = append(dst, "\"inner\":"...)
	if m.Inner != nil {
		dst, err = m.Inner.AppendJSON(dst)
		if err != nil {
			return dst, err
		}
	} else {
		dst = append(dst, "null"...)
	}
	dst = append(dst, ',')
	dst = append(dst, "\"nums\":"...)
	dst = append(dst, '[')
	for i, v := range m.Nums {
		if i > 0 {
			dst = append(dst, ',')
		}
		dst = strconv.AppendUint(dst, uint64(v), 10)
	}
	dst = append(dst, ']')
	dst = append(dst, ',')
	dst = append(dst, "\"names\":"...)
	dst = append(dst, '[')
	for i, v := range m.Names {
		if i > 0 {
			dst = append(dst, ',')
		}
		dst = jsonString(dst, v)
	}
	dst = append(dst, ']')
	dst = append(dst, ',')
	dst = append(dst, "\"inners\":"...)
	dst = append(dst, '[')
	for i, v := range m.Inners {
		if i > 0 {
			dst = append(dst, ',')
		}
		if v != nil {
			dst, err = v.AppendJSON(dst)
			if err != nil {
				return dst, err
			}
		} else {
			dst = append(dst, "null"...)
		}
	}
	dst = append(dst, ']')
	dst = append(dst, ',')
	switch c := m.Choice.(type) {
	case *Shapes_ChoiceMsg:
		dst = append(dst, "\"choice_msg\":"...)
		if c.ChoiceMsg != nil {
			dst, err = c.ChoiceMsg.AppendJSON(dst)
			if err != nil {
				return dst, err
			}
		} else {
			dst = append(dst, "null"...)
		}
		dst = append(dst, ',')
	case *Shapes_ChoiceNum:
		dst = append(dst, "\"choice_num\":"...)
		dst = strconv.AppendUint(dst, uint64(c.ChoiceNum), 10)
		dst = append(dst, ',')
	}
	dst = append(dst, "\"entries\":"...)
	dst = append(dst, '{')
	{
		mk := make([]string, 0, len(m.Entries))
		for k := range m.Entries {
			mk = append(mk, k)
		}
		sort.Slice(mk, func(i, j int) bool { return mk[i] < mk[j] })
		for i, k := range mk {
			if i > 0 {
				dst = append(dst, ',')
			}
			dst = jsonString(dst, k)
			dst = append(dst, ':')
			v := m.Entries[k]
			if v != nil {
				dst, err = v.AppendJSON(dst)
				if err != nil {
					return dst, err
				}
			} else {
				dst = append(dst, "null"...)
			}
		}
	}
	dst = append(dst, '}')
	dst = append(dst, ',')
	if m.OptionalFlag != nil {
		dst = append(dst, "\"optional_flag\":"...)
		dst = strconv.AppendBool(dst, *m.OptionalFlag)
		dst = append(dst, ',')
	}
	if m.OptionalName != nil {
		dst = append(dst, "\"optional_name\":"...)
		dst = jsonString(dst, *m.OptionalName)
		dst = append(dst, ',')
	}
	if m.OptionalBlob != nil {
		dst = append(dst, "\"optional_blob\":"...)
		dst = jsonBytes(dst, m.OptionalBlob)
		dst = append(dst, ',')
	}
	dst = jsonEndObj(dst)
	return dst, nil
}

func embedBool(v bool) uint64 {
	if v {
		return 1
	}
	return 0
}

type msgReflect struct {
	MarshalFn    func([]byte) ([]byte, error)
	SizeFn       func() int
	UnmarshalFn  func([]byte) error
	Iface        protoreflect.ProtoMessage
	Valid        bool
	NewFn        func() protoreflect.Message
	GetUnknownFn func() protoreflect.RawFields
	SetUnknownFn func(protoreflect.RawFields)
}

var _ protoreflect.Message = msgReflect{}

func (r msgReflect) ProtoMethods() *protoiface.Methods    { return &embedMethods }
func (r msgReflect) Interface() protoreflect.ProtoMessage { return r.Iface }
func (r msgReflect) IsValid() bool                        { return r.Valid }
func (r msgReflect) New() protoreflect.Message            { return r.NewFn() }
func (r msgReflect) GetUnknown() protoreflect.RawFields   { return r.GetUnknownFn() }
func (r msgReflect) SetUnknown(f protoreflect.RawFields)  { r.SetUnknownFn(f) }

func embedCanary(m string) string {
	return "CANARY: protoreflect.Message." + m + " called on reflection-free message"
}

func (r msgReflect) Descriptor() protoreflect.MessageDescriptor { panic(embedCanary("Descriptor")) }
func (r msgReflect) Type() protoreflect.MessageType             { panic(embedCanary("Type")) }
func (r msgReflect) Range(func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	panic(embedCanary("Range"))
}
func (r msgReflect) Has(protoreflect.FieldDescriptor) bool               { panic(embedCanary("Has")) }
func (r msgReflect) Clear(protoreflect.FieldDescriptor)                  { panic(embedCanary("Clear")) }
func (r msgReflect) Get(protoreflect.FieldDescriptor) protoreflect.Value { panic(embedCanary("Get")) }
func (r msgReflect) Set(protoreflect.FieldDescriptor, protoreflect.Value) {
	panic(embedCanary("Set"))
}
func (r msgReflect) Mutable(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(embedCanary("Mutable"))
}
func (r msgReflect) NewField(protoreflect.FieldDescriptor) protoreflect.Value {
	panic(embedCanary("NewField"))
}
func (r msgReflect) WhichOneof(protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	panic(embedCanary("WhichOneof"))
}

var embedMethods = protoiface.Methods{
	Flags: protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
	Size: func(in protoiface.SizeInput) protoiface.SizeOutput {
		return protoiface.SizeOutput{Size: in.Message.(msgReflect).SizeFn()}
	},
	Marshal: func(in protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		b, err := in.Message.(msgReflect).MarshalFn(in.Buf)
		return protoiface.MarshalOutput{Buf: b}, err
	},
	Unmarshal: func(in protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		err := in.Message.(msgReflect).UnmarshalFn(in.Buf)
		return protoiface.UnmarshalOutput{Flags: protoiface.UnmarshalInitialized}, err
	},
	Merge: func(in protoiface.MergeInput) protoiface.MergeOutput {
		src := in.Source.(msgReflect)
		dst := in.Destination.(msgReflect)
		sb, _ := src.MarshalFn(nil)
		if err := dst.UnmarshalFn(sb); err != nil {
			return protoiface.MergeOutput{}
		}
		return protoiface.MergeOutput{Flags: protoiface.MergeComplete}
	},
	CheckInitialized: func(in protoiface.CheckInitializedInput) (protoiface.CheckInitializedOutput, error) {
		return protoiface.CheckInitializedOutput{}, nil
	},
	Equal: func(in protoiface.EqualInput) protoiface.EqualOutput {
		a, ok1 := in.MessageA.(msgReflect)
		b, ok2 := in.MessageB.(msgReflect)
		if !ok1 || !ok2 {
			return protoiface.EqualOutput{Equal: false}
		}
		ab, _ := a.MarshalFn(nil)
		bb, _ := b.MarshalFn(nil)
		return protoiface.EqualOutput{Equal: bytes.Equal(ab, bb)}
	},
}

// --- protojson-compatible JSON helpers ---

func jsonEndObj(dst []byte) []byte {
	if n := len(dst); n > 0 && dst[n-1] == ',' {
		dst[n-1] = '}'
		return dst
	}
	return append(dst, '}')
}

func jsonHexDigit(b byte) byte {
	if b < 10 {
		return '0' + b
	}
	return 'a' + b - 10
}

func jsonString(dst []byte, s string) []byte {
	dst = append(dst, '"')
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch c {
		case '"':
			dst = append(dst, '\\', '"')
		case '\\':
			dst = append(dst, '\\', '\\')
		case '\n':
			dst = append(dst, '\\', 'n')
		case '\r':
			dst = append(dst, '\\', 'r')
		case '\t':
			dst = append(dst, '\\', 't')
		default:
			if c < 0x20 {
				dst = append(dst, '\\', 'u', '0', '0', jsonHexDigit(c>>4), jsonHexDigit(c&0xf))
			} else {
				dst = append(dst, c)
			}
		}
	}
	return append(dst, '"')
}

func jsonBytes(dst []byte, b []byte) []byte {
	dst = append(dst, '"')
	dst = base64.StdEncoding.AppendEncode(dst, b)
	return append(dst, '"')
}

// jsonNanoFrac formats sub-second nanos as protojson does: trailing zero groups
// of three trimmed, leaving 3, 6, or 9 fractional digits.
func jsonNanoFrac(nanos int32) string {
	buf := fmt.Sprintf("%09d", nanos)
	n := 9
	for n > 3 && buf[n-1] == '0' && buf[n-2] == '0' && buf[n-3] == '0' {
		n -= 3
	}
	return buf[:n]
}
