// Code generated by embedpb. DO NOT EDIT.
// Reflection-free, TinyGo-safe proto codec: hand-written protoiface.Methods
// keep google.golang.org/protobuf on its fast path (no reflect coder).
package proxypb

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"math"
	"sort"
	"strconv"
	"time"

	"github.com/soypat/embedpb/pbruntime"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/reflect/protoreflect"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

var _ = math.Float32bits
var _ = sort.Strings
var _ = fmt.Sprintf
var _ = bytes.Equal
var _ = strconv.AppendInt
var _ = base64.StdEncoding
var _ = time.Unix

type PathRewriteMode int32

const (
	PathRewriteMode_PATH_REWRITE_DEFAULT  PathRewriteMode = 0
	PathRewriteMode_PATH_REWRITE_PRESERVE PathRewriteMode = 1
)

var PathRewriteMode_name = map[int32]string{
	0: "PATH_REWRITE_DEFAULT",
	1: "PATH_REWRITE_PRESERVE",
}

func (x PathRewriteMode) String() string {
	if s, ok := PathRewriteMode_name[int32(x)]; ok {
		return s
	}
	return fmt.Sprintf("PathRewriteMode(%d)", int32(x))
}
func (x PathRewriteMode) Enum() *PathRewriteMode { p := new(PathRewriteMode); *p = x; return p }

type ProxyStatus int32

const (
	ProxyStatus_PROXY_STATUS_PENDING ProxyStatus = 0
	ProxyStatus_PROXY_STATUS_ACTIVE  ProxyStatus = 1
	ProxyStatus_PROXY_STATUS_ERROR   ProxyStatus = 2
)

var ProxyStatus_name = map[int32]string{
	0: "PROXY_STATUS_PENDING",
	1: "PROXY_STATUS_ACTIVE",
	2: "PROXY_STATUS_ERROR",
}

func (x ProxyStatus) String() string {
	if s, ok := ProxyStatus_name[int32(x)]; ok {
		return s
	}
	return fmt.Sprintf("ProxyStatus(%d)", int32(x))
}
func (x ProxyStatus) Enum() *ProxyStatus { p := new(ProxyStatus); *p = x; return p }

type isAuthenticateRequest_Request interface{ isAuthenticateRequest_Request() }
type AuthenticateRequest_Password struct{ Password *PasswordRequest }

func (*AuthenticateRequest_Password) isAuthenticateRequest_Request() {}

type AuthenticateRequest_Pin struct{ Pin *PinRequest }

func (*AuthenticateRequest_Pin) isAuthenticateRequest_Request() {}

type AuthenticateRequest_HeaderAuth struct{ HeaderAuth *HeaderAuthRequest }

func (*AuthenticateRequest_HeaderAuth) isAuthenticateRequest_Request() {}

type isSyncMappingsRequest_Msg interface{ isSyncMappingsRequest_Msg() }
type SyncMappingsRequest_Init struct{ Init *SyncMappingsInit }

func (*SyncMappingsRequest_Init) isSyncMappingsRequest_Msg() {}

type SyncMappingsRequest_Ack struct{ Ack *SyncMappingsAck }

func (*SyncMappingsRequest_Ack) isSyncMappingsRequest_Msg() {}

type AccessLog struct {
	Timestamp     *timestamppb.Timestamp
	LogId         string
	ServiceId     string
	DurationMs    int64
	Metadata      map[string]string
	unknownFields protoreflect.RawFields
}

func (m *AccessLog) Reset()         { *m = AccessLog{} }
func (m *AccessLog) String() string { return fmt.Sprintf("AccessLog{}") }
func (m *AccessLog) ProtoMessage()  {}
func (m *AccessLog) GetTimestamp() *timestamppb.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}
func (m *AccessLog) GetLogId() string {
	if m != nil {
		return m.LogId
	}
	return ""
}
func (m *AccessLog) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}
func (m *AccessLog) GetDurationMs() int64 {
	if m != nil {
		return m.DurationMs
	}
	return 0
}
func (m *AccessLog) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *AccessLog) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&AccessLog{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *AccessLog) sizeField() int {
	n := 0
	if m.Timestamp != nil {
		n += protowire.SizeTag(1) + protowire.SizeBytes(extSize_timestamppb_Timestamp(m.Timestamp))
	}
	if m.LogId != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.LogId))
	}
	if m.ServiceId != "" {
		n += protowire.SizeTag(3) + protowire.SizeBytes(len(m.ServiceId))
	}
	if m.DurationMs != 0 {
		n += protowire.SizeTag(4) + protowire.SizeVarint(uint64(m.DurationMs))
	}
	for k, v := range m.Metadata {
		n += protowire.SizeTag(5) + protowire.SizeBytes(mapEntry_AccessLog_Metadata(k, v))
	}
	n += len(m.unknownFields)
	return n
}

func (m *AccessLog) marshalAppend(b []byte) ([]byte, error) {
	if m.Timestamp != nil {
		sub := extAppend_timestamppb_Timestamp(nil, m.Timestamp)
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	if m.LogId != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.LogId)
	}
	if m.ServiceId != "" {
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendString(b, m.ServiceId)
	}
	if m.DurationMs != 0 {
		b = protowire.AppendTag(b, 4, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.DurationMs))
	}
	if len(m.Metadata) > 0 {
		keys := make([]string, 0, len(m.Metadata))
		for k := range m.Metadata {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
		for _, k := range keys {
			b = protowire.AppendTag(b, 5, protowire.BytesType)
			b = protowire.AppendBytes(b, appendEntry_AccessLog_Metadata(nil, k, m.Metadata[k]))
		}
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *AccessLog) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				m.Timestamp = extDecode_timestamppb_Timestamp(v)
			}
		case 2:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.LogId = v
		case 3:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.ServiceId = v
		case 4:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.DurationMs = int64(v)
		case 5:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				if m.Metadata == nil {
					m.Metadata = make(map[string]string)
				}
				mk, mv := decodeEntry_AccessLog_Metadata(v)
				m.Metadata[mk] = mv
			}
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func mapEntry_AccessLog_Metadata(k string, v string) int {
	n := 0
	if k != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(k))
	}
	if v != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(v))
	}
	return n
}
func appendEntry_AccessLog_Metadata(b []byte, k string, v string) []byte {
	if k != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, k)
	}
	if v != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, v)
	}
	return b
}
func decodeEntry_AccessLog_Metadata(b []byte) (string, string) {
	var k string
	var v string
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			vv, kk := protowire.ConsumeString(b)
			consumed = kk
			k = vv
		case 2:
			vv, kk := protowire.ConsumeString(b)
			consumed = kk
			v = vv
		default:
			consumed = protowire.ConsumeFieldValue(num, typ, b)
		}
		if consumed < 0 {
			break
		}
		b = b[consumed:]
	}
	return k, v
}

func (m *AccessLog) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *AccessLog) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"timestamp\":"...)
	dst = extJSON_timestamppb_Timestamp(dst, m.Timestamp)
	dst = append(dst, ',')
	dst = append(dst, "\"log_id\":"...)
	dst = jsonString(dst, m.LogId)
	dst = append(dst, ',')
	dst = append(dst, "\"service_id\":"...)
	dst = jsonString(dst, m.ServiceId)
	dst = append(dst, ',')
	dst = append(dst, "\"duration_ms\":"...)
	dst = append(dst, '"')
	dst = strconv.AppendInt(dst, int64(m.DurationMs), 10)
	dst = append(dst, '"')
	dst = append(dst, ',')
	dst = append(dst, "\"metadata\":"...)
	dst = append(dst, '{')
	{
		mk := make([]string, 0, len(m.Metadata))
		for k := range m.Metadata {
			mk = append(mk, k)
		}
		sort.Slice(mk, func(i, j int) bool { return mk[i] < mk[j] })
		for i, k := range mk {
			if i > 0 {
				dst = append(dst, ',')
			}
			dst = jsonString(dst, k)
			dst = append(dst, ':')
			v := m.Metadata[k]
			dst = jsonString(dst, v)
		}
	}
	dst = append(dst, '}')
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type AuthenticateRequest struct {
	Id            string
	AccountId     string
	Request       isAuthenticateRequest_Request
	unknownFields protoreflect.RawFields
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return fmt.Sprintf("AuthenticateRequest{}") }
func (m *AuthenticateRequest) ProtoMessage()  {}
func (m *AuthenticateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}
func (m *AuthenticateRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}
func (m *AuthenticateRequest) GetRequest() isAuthenticateRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}
func (m *AuthenticateRequest) GetPassword() *PasswordRequest {
	if v, ok := m.GetRequest().(*AuthenticateRequest_Password); ok {
		return v.Password
	}
	return nil
}
func (m *AuthenticateRequest) GetPin() *PinRequest {
	if v, ok := m.GetRequest().(*AuthenticateRequest_Pin); ok {
		return v.Pin
	}
	return nil
}
func (m *AuthenticateRequest) GetHeaderAuth() *HeaderAuthRequest {
	if v, ok := m.GetRequest().(*AuthenticateRequest_HeaderAuth); ok {
		return v.HeaderAuth
	}
	return nil
}

func (m *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&AuthenticateRequest{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *AuthenticateRequest) sizeField() int {
	n := 0
	if m.Id != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.Id))
	}
	if m.AccountId != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.AccountId))
	}
	switch c := m.Request.(type) {
	case *AuthenticateRequest_Password:
		_ = c
		n += protowire.SizeTag(3) + protowire.SizeBytes(c.Password.sizeField())
	case *AuthenticateRequest_Pin:
		_ = c
		n += protowire.SizeTag(4) + protowire.SizeBytes(c.Pin.sizeField())
	case *AuthenticateRequest_HeaderAuth:
		_ = c
		n += protowire.SizeTag(5) + protowire.SizeBytes(c.HeaderAuth.sizeField())
	}
	n += len(m.unknownFields)
	return n
}

func (m *AuthenticateRequest) marshalAppend(b []byte) ([]byte, error) {
	if m.Id != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.Id)
	}
	if m.AccountId != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.AccountId)
	}
	switch c := m.Request.(type) {
	case *AuthenticateRequest_Password:
		sub, _ := c.Password.marshalAppend(nil)
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	case *AuthenticateRequest_Pin:
		sub, _ := c.Pin.marshalAppend(nil)
		b = protowire.AppendTag(b, 4, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	case *AuthenticateRequest_HeaderAuth:
		sub, _ := c.HeaderAuth.marshalAppend(nil)
		b = protowire.AppendTag(b, 5, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *AuthenticateRequest) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.Id = v
		case 2:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.AccountId = v
		case 3:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				var mv *PasswordRequest
				mm := &PasswordRequest{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				mv = mm
				m.Request = &AuthenticateRequest_Password{Password: mv}
			}
		case 4:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				var mv *PinRequest
				mm := &PinRequest{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				mv = mm
				m.Request = &AuthenticateRequest_Pin{Pin: mv}
			}
		case 5:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				var mv *HeaderAuthRequest
				mm := &HeaderAuthRequest{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				mv = mm
				m.Request = &AuthenticateRequest_HeaderAuth{HeaderAuth: mv}
			}
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *AuthenticateRequest) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *AuthenticateRequest) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"id\":"...)
	dst = jsonString(dst, m.Id)
	dst = append(dst, ',')
	dst = append(dst, "\"account_id\":"...)
	dst = jsonString(dst, m.AccountId)
	dst = append(dst, ',')
	switch c := m.Request.(type) {
	case *AuthenticateRequest_Password:
		dst = append(dst, "\"password\":"...)
		if c.Password != nil {
			dst, err = c.Password.AppendJSON(dst)
			if err != nil {
				return dst, err
			}
		} else {
			dst = append(dst, "null"...)
		}
		dst = append(dst, ',')
	case *AuthenticateRequest_Pin:
		dst = append(dst, "\"pin\":"...)
		if c.Pin != nil {
			dst, err = c.Pin.AppendJSON(dst)
			if err != nil {
				return dst, err
			}
		} else {
			dst = append(dst, "null"...)
		}
		dst = append(dst, ',')
	case *AuthenticateRequest_HeaderAuth:
		dst = append(dst, "\"header_auth\":"...)
		if c.HeaderAuth != nil {
			dst, err = c.HeaderAuth.AppendJSON(dst)
			if err != nil {
				return dst, err
			}
		} else {
			dst = append(dst, "null"...)
		}
		dst = append(dst, ',')
	}
	dst = jsonEndObj(dst)
	return dst, nil
}

type Authentication struct {
	SessionKey           string
	MaxSessionAgeSeconds int64
	Password             bool
	Pin                  bool
	HeaderAuths          []*HeaderAuth
	unknownFields        protoreflect.RawFields
}

func (m *Authentication) Reset()         { *m = Authentication{} }
func (m *Authentication) String() string { return fmt.Sprintf("Authentication{}") }
func (m *Authentication) ProtoMessage()  {}
func (m *Authentication) GetSessionKey() string {
	if m != nil {
		return m.SessionKey
	}
	return ""
}
func (m *Authentication) GetMaxSessionAgeSeconds() int64 {
	if m != nil {
		return m.MaxSessionAgeSeconds
	}
	return 0
}
func (m *Authentication) GetPassword() bool {
	if m != nil {
		return m.Password
	}
	return false
}
func (m *Authentication) GetPin() bool {
	if m != nil {
		return m.Pin
	}
	return false
}
func (m *Authentication) GetHeaderAuths() []*HeaderAuth {
	if m != nil {
		return m.HeaderAuths
	}
	return nil
}

func (m *Authentication) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&Authentication{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *Authentication) sizeField() int {
	n := 0
	if m.SessionKey != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.SessionKey))
	}
	if m.MaxSessionAgeSeconds != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(m.MaxSessionAgeSeconds))
	}
	if m.Password {
		n += protowire.SizeTag(3) + protowire.SizeVarint(embedBool(m.Password))
	}
	if m.Pin {
		n += protowire.SizeTag(4) + protowire.SizeVarint(embedBool(m.Pin))
	}
	for _, v := range m.HeaderAuths {
		n += protowire.SizeTag(5) + protowire.SizeBytes(v.sizeField())
	}
	n += len(m.unknownFields)
	return n
}

func (m *Authentication) marshalAppend(b []byte) ([]byte, error) {
	if m.SessionKey != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.SessionKey)
	}
	if m.MaxSessionAgeSeconds != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.MaxSessionAgeSeconds))
	}
	if m.Password {
		b = protowire.AppendTag(b, 3, protowire.VarintType)
		b = protowire.AppendVarint(b, embedBool(m.Password))
	}
	if m.Pin {
		b = protowire.AppendTag(b, 4, protowire.VarintType)
		b = protowire.AppendVarint(b, embedBool(m.Pin))
	}
	for _, v := range m.HeaderAuths {
		sub, _ := v.marshalAppend(nil)
		b = protowire.AppendTag(b, 5, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *Authentication) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.SessionKey = v
		case 2:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.MaxSessionAgeSeconds = int64(v)
		case 3:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Password = v != 0
		case 4:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Pin = v != 0
		case 5:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				var mv *HeaderAuth
				mm := &HeaderAuth{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				mv = mm
				m.HeaderAuths = append(m.HeaderAuths, mv)
			}
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *Authentication) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *Authentication) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"session_key\":"...)
	dst = jsonString(dst, m.SessionKey)
	dst = append(dst, ',')
	dst = append(dst, "\"max_session_age_seconds\":"...)
	dst = append(dst, '"')
	dst = strconv.AppendInt(dst, int64(m.MaxSessionAgeSeconds), 10)
	dst = append(dst, '"')
	dst = append(dst, ',')
	dst = append(dst, "\"password\":"...)
	dst = strconv.AppendBool(dst, m.Password)
	dst = append(dst, ',')
	dst = append(dst, "\"pin\":"...)
	dst = strconv.AppendBool(dst, m.Pin)
	dst = append(dst, ',')
	dst = append(dst, "\"header_auths\":"...)
	dst = append(dst, '[')
	for i, v := range m.HeaderAuths {
		if i > 0 {
			dst = append(dst, ',')
		}
		if v != nil {
			dst, err = v.AppendJSON(dst)
			if err != nil {
				return dst, err
			}
		} else {
			dst = append(dst, "null"...)
		}
	}
	dst = append(dst, ']')
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type HeaderAuth struct {
	Header        string
	HashedValue   string
	unknownFields protoreflect.RawFields
}

func (m *HeaderAuth) Reset()         { *m = HeaderAuth{} }
func (m *HeaderAuth) String() string { return fmt.Sprintf("HeaderAuth{}") }
func (m *HeaderAuth) ProtoMessage()  {}
func (m *HeaderAuth) GetHeader() string {
	if m != nil {
		return m.Header
	}
	return ""
}
func (m *HeaderAuth) GetHashedValue() string {
	if m != nil {
		return m.HashedValue
	}
	return ""
}

func (m *HeaderAuth) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&HeaderAuth{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *HeaderAuth) sizeField() int {
	n := 0
	if m.Header != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.Header))
	}
	if m.HashedValue != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.HashedValue))
	}
	n += len(m.unknownFields)
	return n
}

func (m *HeaderAuth) marshalAppend(b []byte) ([]byte, error) {
	if m.Header != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.Header)
	}
	if m.HashedValue != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.HashedValue)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *HeaderAuth) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.Header = v
		case 2:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.HashedValue = v
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *HeaderAuth) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *HeaderAuth) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"header\":"...)
	dst = jsonString(dst, m.Header)
	dst = append(dst, ',')
	dst = append(dst, "\"hashed_value\":"...)
	dst = jsonString(dst, m.HashedValue)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type HeaderAuthRequest struct {
	HeaderValue   string
	HeaderName    string
	unknownFields protoreflect.RawFields
}

func (m *HeaderAuthRequest) Reset()         { *m = HeaderAuthRequest{} }
func (m *HeaderAuthRequest) String() string { return fmt.Sprintf("HeaderAuthRequest{}") }
func (m *HeaderAuthRequest) ProtoMessage()  {}
func (m *HeaderAuthRequest) GetHeaderValue() string {
	if m != nil {
		return m.HeaderValue
	}
	return ""
}
func (m *HeaderAuthRequest) GetHeaderName() string {
	if m != nil {
		return m.HeaderName
	}
	return ""
}

func (m *HeaderAuthRequest) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&HeaderAuthRequest{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *HeaderAuthRequest) sizeField() int {
	n := 0
	if m.HeaderValue != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.HeaderValue))
	}
	if m.HeaderName != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.HeaderName))
	}
	n += len(m.unknownFields)
	return n
}

func (m *HeaderAuthRequest) marshalAppend(b []byte) ([]byte, error) {
	if m.HeaderValue != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.HeaderValue)
	}
	if m.HeaderName != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.HeaderName)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *HeaderAuthRequest) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.HeaderValue = v
		case 2:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.HeaderName = v
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *HeaderAuthRequest) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *HeaderAuthRequest) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"header_value\":"...)
	dst = jsonString(dst, m.HeaderValue)
	dst = append(dst, ',')
	dst = append(dst, "\"header_name\":"...)
	dst = jsonString(dst, m.HeaderName)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type PasswordRequest struct {
	Password      string
	unknownFields protoreflect.RawFields
}

func (m *PasswordRequest) Reset()         { *m = PasswordRequest{} }
func (m *PasswordRequest) String() string { return fmt.Sprintf("PasswordRequest{}") }
func (m *PasswordRequest) ProtoMessage()  {}
func (m *PasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *PasswordRequest) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&PasswordRequest{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *PasswordRequest) sizeField() int {
	n := 0
	if m.Password != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.Password))
	}
	n += len(m.unknownFields)
	return n
}

func (m *PasswordRequest) marshalAppend(b []byte) ([]byte, error) {
	if m.Password != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.Password)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *PasswordRequest) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.Password = v
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *PasswordRequest) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *PasswordRequest) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"password\":"...)
	dst = jsonString(dst, m.Password)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type PathMapping struct {
	Path          string
	Target        string
	Options       *PathTargetOptions
	unknownFields protoreflect.RawFields
}

func (m *PathMapping) Reset()         { *m = PathMapping{} }
func (m *PathMapping) String() string { return fmt.Sprintf("PathMapping{}") }
func (m *PathMapping) ProtoMessage()  {}
func (m *PathMapping) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}
func (m *PathMapping) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}
func (m *PathMapping) GetOptions() *PathTargetOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *PathMapping) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&PathMapping{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *PathMapping) sizeField() int {
	n := 0
	if m.Path != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.Path))
	}
	if m.Target != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.Target))
	}
	if m.Options != nil {
		n += protowire.SizeTag(3) + protowire.SizeBytes(m.Options.sizeField())
	}
	n += len(m.unknownFields)
	return n
}

func (m *PathMapping) marshalAppend(b []byte) ([]byte, error) {
	if m.Path != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.Path)
	}
	if m.Target != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.Target)
	}
	if m.Options != nil {
		sub, _ := m.Options.marshalAppend(nil)
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *PathMapping) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.Path = v
		case 2:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.Target = v
		case 3:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				mm := &PathTargetOptions{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				m.Options = mm
			}
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *PathMapping) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *PathMapping) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"path\":"...)
	dst = jsonString(dst, m.Path)
	dst = append(dst, ',')
	dst = append(dst, "\"target\":"...)
	dst = jsonString(dst, m.Target)
	dst = append(dst, ',')
	dst = append(dst, "\"options\":"...)
	if m.Options != nil {
		dst, err = m.Options.AppendJSON(dst)
		if err != nil {
			return dst, err
		}
	} else {
		dst = append(dst, "null"...)
	}
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type PathTargetOptions struct {
	SkipTlsVerify      bool
	RequestTimeout     *durationpb.Duration
	PathRewrite        PathRewriteMode
	CustomHeaders      map[string]string
	SessionIdleTimeout *durationpb.Duration
	unknownFields      protoreflect.RawFields
}

func (m *PathTargetOptions) Reset()         { *m = PathTargetOptions{} }
func (m *PathTargetOptions) String() string { return fmt.Sprintf("PathTargetOptions{}") }
func (m *PathTargetOptions) ProtoMessage()  {}
func (m *PathTargetOptions) GetSkipTlsVerify() bool {
	if m != nil {
		return m.SkipTlsVerify
	}
	return false
}
func (m *PathTargetOptions) GetRequestTimeout() *durationpb.Duration {
	if m != nil {
		return m.RequestTimeout
	}
	return nil
}
func (m *PathTargetOptions) GetPathRewrite() PathRewriteMode {
	if m != nil {
		return m.PathRewrite
	}
	return PathRewriteMode(0)
}
func (m *PathTargetOptions) GetCustomHeaders() map[string]string {
	if m != nil {
		return m.CustomHeaders
	}
	return nil
}
func (m *PathTargetOptions) GetSessionIdleTimeout() *durationpb.Duration {
	if m != nil {
		return m.SessionIdleTimeout
	}
	return nil
}

func (m *PathTargetOptions) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&PathTargetOptions{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *PathTargetOptions) sizeField() int {
	n := 0
	if m.SkipTlsVerify {
		n += protowire.SizeTag(1) + protowire.SizeVarint(embedBool(m.SkipTlsVerify))
	}
	if m.RequestTimeout != nil {
		n += protowire.SizeTag(2) + protowire.SizeBytes(extSize_durationpb_Duration(m.RequestTimeout))
	}
	if m.PathRewrite != 0 {
		n += protowire.SizeTag(3) + protowire.SizeVarint(uint64(int64(m.PathRewrite)))
	}
	for k, v := range m.CustomHeaders {
		n += protowire.SizeTag(4) + protowire.SizeBytes(mapEntry_PathTargetOptions_CustomHeaders(k, v))
	}
	if m.SessionIdleTimeout != nil {
		n += protowire.SizeTag(5) + protowire.SizeBytes(extSize_durationpb_Duration(m.SessionIdleTimeout))
	}
	n += len(m.unknownFields)
	return n
}

func (m *PathTargetOptions) marshalAppend(b []byte) ([]byte, error) {
	if m.SkipTlsVerify {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, embedBool(m.SkipTlsVerify))
	}
	if m.RequestTimeout != nil {
		sub := extAppend_durationpb_Duration(nil, m.RequestTimeout)
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	if m.PathRewrite != 0 {
		b = protowire.AppendTag(b, 3, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(int64(m.PathRewrite)))
	}
	if len(m.CustomHeaders) > 0 {
		keys := make([]string, 0, len(m.CustomHeaders))
		for k := range m.CustomHeaders {
			keys = append(keys, k)
		}
		sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
		for _, k := range keys {
			b = protowire.AppendTag(b, 4, protowire.BytesType)
			b = protowire.AppendBytes(b, appendEntry_PathTargetOptions_CustomHeaders(nil, k, m.CustomHeaders[k]))
		}
	}
	if m.SessionIdleTimeout != nil {
		sub := extAppend_durationpb_Duration(nil, m.SessionIdleTimeout)
		b = protowire.AppendTag(b, 5, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *PathTargetOptions) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.SkipTlsVerify = v != 0
		case 2:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				m.RequestTimeout = extDecode_durationpb_Duration(v)
			}
		case 3:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.PathRewrite = PathRewriteMode(v)
		case 4:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				if m.CustomHeaders == nil {
					m.CustomHeaders = make(map[string]string)
				}
				mk, mv := decodeEntry_PathTargetOptions_CustomHeaders(v)
				m.CustomHeaders[mk] = mv
			}
		case 5:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				m.SessionIdleTimeout = extDecode_durationpb_Duration(v)
			}
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func mapEntry_PathTargetOptions_CustomHeaders(k string, v string) int {
	n := 0
	if k != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(k))
	}
	if v != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(v))
	}
	return n
}
func appendEntry_PathTargetOptions_CustomHeaders(b []byte, k string, v string) []byte {
	if k != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, k)
	}
	if v != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, v)
	}
	return b
}
func decodeEntry_PathTargetOptions_CustomHeaders(b []byte) (string, string) {
	var k string
	var v string
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			vv, kk := protowire.ConsumeString(b)
			consumed = kk
			k = vv
		case 2:
			vv, kk := protowire.ConsumeString(b)
			consumed = kk
			v = vv
		default:
			consumed = protowire.ConsumeFieldValue(num, typ, b)
		}
		if consumed < 0 {
			break
		}
		b = b[consumed:]
	}
	return k, v
}

func (m *PathTargetOptions) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *PathTargetOptions) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"skip_tls_verify\":"...)
	dst = strconv.AppendBool(dst, m.SkipTlsVerify)
	dst = append(dst, ',')
	dst = append(dst, "\"request_timeout\":"...)
	dst = extJSON_durationpb_Duration(dst, m.RequestTimeout)
	dst = append(dst, ',')
	dst = append(dst, "\"path_rewrite\":"...)
	if s, ok := PathRewriteMode_name[int32(m.PathRewrite)]; ok {
		dst = jsonString(dst, s)
	} else {
		dst = strconv.AppendInt(dst, int64(m.PathRewrite), 10)
	}
	dst = append(dst, ',')
	dst = append(dst, "\"custom_headers\":"...)
	dst = append(dst, '{')
	{
		mk := make([]string, 0, len(m.CustomHeaders))
		for k := range m.CustomHeaders {
			mk = append(mk, k)
		}
		sort.Slice(mk, func(i, j int) bool { return mk[i] < mk[j] })
		for i, k := range mk {
			if i > 0 {
				dst = append(dst, ',')
			}
			dst = jsonString(dst, k)
			dst = append(dst, ':')
			v := m.CustomHeaders[k]
			dst = jsonString(dst, v)
		}
	}
	dst = append(dst, '}')
	dst = append(dst, ',')
	dst = append(dst, "\"session_idle_timeout\":"...)
	dst = extJSON_durationpb_Duration(dst, m.SessionIdleTimeout)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type PinRequest struct {
	Pin           string
	unknownFields protoreflect.RawFields
}

func (m *PinRequest) Reset()         { *m = PinRequest{} }
func (m *PinRequest) String() string { return fmt.Sprintf("PinRequest{}") }
func (m *PinRequest) ProtoMessage()  {}
func (m *PinRequest) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

func (m *PinRequest) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&PinRequest{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *PinRequest) sizeField() int {
	n := 0
	if m.Pin != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.Pin))
	}
	n += len(m.unknownFields)
	return n
}

func (m *PinRequest) marshalAppend(b []byte) ([]byte, error) {
	if m.Pin != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.Pin)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *PinRequest) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.Pin = v
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *PinRequest) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *PinRequest) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"pin\":"...)
	dst = jsonString(dst, m.Pin)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type ProxyCapabilities struct {
	SupportsCustomPorts *bool
	Private             *bool
	unknownFields       protoreflect.RawFields
}

func (m *ProxyCapabilities) Reset()         { *m = ProxyCapabilities{} }
func (m *ProxyCapabilities) String() string { return fmt.Sprintf("ProxyCapabilities{}") }
func (m *ProxyCapabilities) ProtoMessage()  {}
func (m *ProxyCapabilities) GetSupportsCustomPorts() bool {
	if m != nil && m.SupportsCustomPorts != nil {
		return *m.SupportsCustomPorts
	}
	return false
}
func (m *ProxyCapabilities) GetPrivate() bool {
	if m != nil && m.Private != nil {
		return *m.Private
	}
	return false
}

func (m *ProxyCapabilities) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&ProxyCapabilities{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *ProxyCapabilities) sizeField() int {
	n := 0
	if m.SupportsCustomPorts != nil {
		n += protowire.SizeTag(1) + protowire.SizeVarint(embedBool(*m.SupportsCustomPorts))
	}
	if m.Private != nil {
		n += protowire.SizeTag(2) + protowire.SizeVarint(embedBool(*m.Private))
	}
	n += len(m.unknownFields)
	return n
}

func (m *ProxyCapabilities) marshalAppend(b []byte) ([]byte, error) {
	if m.SupportsCustomPorts != nil {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, embedBool(*m.SupportsCustomPorts))
	}
	if m.Private != nil {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, embedBool(*m.Private))
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *ProxyCapabilities) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			tmp := v != 0
			m.SupportsCustomPorts = &tmp
		case 2:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			tmp := v != 0
			m.Private = &tmp
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *ProxyCapabilities) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *ProxyCapabilities) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	if m.SupportsCustomPorts != nil {
		dst = append(dst, "\"supports_custom_ports\":"...)
		dst = strconv.AppendBool(dst, *m.SupportsCustomPorts)
		dst = append(dst, ',')
	}
	if m.Private != nil {
		dst = append(dst, "\"private\":"...)
		dst = strconv.AppendBool(dst, *m.Private)
		dst = append(dst, ',')
	}
	dst = jsonEndObj(dst)
	return dst, nil
}

type ProxyInboundListener struct {
	TunnelIp      string
	HttpsPort     uint32
	HttpPort      uint32
	unknownFields protoreflect.RawFields
}

func (m *ProxyInboundListener) Reset()         { *m = ProxyInboundListener{} }
func (m *ProxyInboundListener) String() string { return fmt.Sprintf("ProxyInboundListener{}") }
func (m *ProxyInboundListener) ProtoMessage()  {}
func (m *ProxyInboundListener) GetTunnelIp() string {
	if m != nil {
		return m.TunnelIp
	}
	return ""
}
func (m *ProxyInboundListener) GetHttpsPort() uint32 {
	if m != nil {
		return m.HttpsPort
	}
	return 0
}
func (m *ProxyInboundListener) GetHttpPort() uint32 {
	if m != nil {
		return m.HttpPort
	}
	return 0
}

func (m *ProxyInboundListener) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&ProxyInboundListener{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *ProxyInboundListener) sizeField() int {
	n := 0
	if m.TunnelIp != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.TunnelIp))
	}
	if m.HttpsPort != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(m.HttpsPort))
	}
	if m.HttpPort != 0 {
		n += protowire.SizeTag(3) + protowire.SizeVarint(uint64(m.HttpPort))
	}
	n += len(m.unknownFields)
	return n
}

func (m *ProxyInboundListener) marshalAppend(b []byte) ([]byte, error) {
	if m.TunnelIp != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.TunnelIp)
	}
	if m.HttpsPort != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.HttpsPort))
	}
	if m.HttpPort != 0 {
		b = protowire.AppendTag(b, 3, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(m.HttpPort))
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *ProxyInboundListener) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.TunnelIp = v
		case 2:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.HttpsPort = uint32(v)
		case 3:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.HttpPort = uint32(v)
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *ProxyInboundListener) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *ProxyInboundListener) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"tunnel_ip\":"...)
	dst = jsonString(dst, m.TunnelIp)
	dst = append(dst, ',')
	dst = append(dst, "\"https_port\":"...)
	dst = strconv.AppendUint(dst, uint64(m.HttpsPort), 10)
	dst = append(dst, ',')
	dst = append(dst, "\"http_port\":"...)
	dst = strconv.AppendUint(dst, uint64(m.HttpPort), 10)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type ProxyMapping struct {
	Id             string
	AccountId      string
	Domain         string
	Path           []*PathMapping
	Auth           *Authentication
	PassHostHeader bool
	ListenPort     int32
	unknownFields  protoreflect.RawFields
}

func (m *ProxyMapping) Reset()         { *m = ProxyMapping{} }
func (m *ProxyMapping) String() string { return fmt.Sprintf("ProxyMapping{}") }
func (m *ProxyMapping) ProtoMessage()  {}
func (m *ProxyMapping) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}
func (m *ProxyMapping) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}
func (m *ProxyMapping) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}
func (m *ProxyMapping) GetPath() []*PathMapping {
	if m != nil {
		return m.Path
	}
	return nil
}
func (m *ProxyMapping) GetAuth() *Authentication {
	if m != nil {
		return m.Auth
	}
	return nil
}
func (m *ProxyMapping) GetPassHostHeader() bool {
	if m != nil {
		return m.PassHostHeader
	}
	return false
}
func (m *ProxyMapping) GetListenPort() int32 {
	if m != nil {
		return m.ListenPort
	}
	return 0
}

func (m *ProxyMapping) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&ProxyMapping{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *ProxyMapping) sizeField() int {
	n := 0
	if m.Id != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.Id))
	}
	if m.AccountId != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.AccountId))
	}
	if m.Domain != "" {
		n += protowire.SizeTag(3) + protowire.SizeBytes(len(m.Domain))
	}
	for _, v := range m.Path {
		n += protowire.SizeTag(4) + protowire.SizeBytes(v.sizeField())
	}
	if m.Auth != nil {
		n += protowire.SizeTag(5) + protowire.SizeBytes(m.Auth.sizeField())
	}
	if m.PassHostHeader {
		n += protowire.SizeTag(6) + protowire.SizeVarint(embedBool(m.PassHostHeader))
	}
	if m.ListenPort != 0 {
		n += protowire.SizeTag(7) + protowire.SizeVarint(uint64(int64(m.ListenPort)))
	}
	n += len(m.unknownFields)
	return n
}

func (m *ProxyMapping) marshalAppend(b []byte) ([]byte, error) {
	if m.Id != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.Id)
	}
	if m.AccountId != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.AccountId)
	}
	if m.Domain != "" {
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendString(b, m.Domain)
	}
	for _, v := range m.Path {
		sub, _ := v.marshalAppend(nil)
		b = protowire.AppendTag(b, 4, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	if m.Auth != nil {
		sub, _ := m.Auth.marshalAppend(nil)
		b = protowire.AppendTag(b, 5, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	if m.PassHostHeader {
		b = protowire.AppendTag(b, 6, protowire.VarintType)
		b = protowire.AppendVarint(b, embedBool(m.PassHostHeader))
	}
	if m.ListenPort != 0 {
		b = protowire.AppendTag(b, 7, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(int64(m.ListenPort)))
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *ProxyMapping) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.Id = v
		case 2:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.AccountId = v
		case 3:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.Domain = v
		case 4:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				var mv *PathMapping
				mm := &PathMapping{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				mv = mm
				m.Path = append(m.Path, mv)
			}
		case 5:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				mm := &Authentication{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				m.Auth = mm
			}
		case 6:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.PassHostHeader = v != 0
		case 7:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.ListenPort = int32(v)
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *ProxyMapping) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *ProxyMapping) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"id\":"...)
	dst = jsonString(dst, m.Id)
	dst = append(dst, ',')
	dst = append(dst, "\"account_id\":"...)
	dst = jsonString(dst, m.AccountId)
	dst = append(dst, ',')
	dst = append(dst, "\"domain\":"...)
	dst = jsonString(dst, m.Domain)
	dst = append(dst, ',')
	dst = append(dst, "\"path\":"...)
	dst = append(dst, '[')
	for i, v := range m.Path {
		if i > 0 {
			dst = append(dst, ',')
		}
		if v != nil {
			dst, err = v.AppendJSON(dst)
			if err != nil {
				return dst, err
			}
		} else {
			dst = append(dst, "null"...)
		}
	}
	dst = append(dst, ']')
	dst = append(dst, ',')
	dst = append(dst, "\"auth\":"...)
	if m.Auth != nil {
		dst, err = m.Auth.AppendJSON(dst)
		if err != nil {
			return dst, err
		}
	} else {
		dst = append(dst, "null"...)
	}
	dst = append(dst, ',')
	dst = append(dst, "\"pass_host_header\":"...)
	dst = strconv.AppendBool(dst, m.PassHostHeader)
	dst = append(dst, ',')
	dst = append(dst, "\"listen_port\":"...)
	dst = strconv.AppendInt(dst, int64(m.ListenPort), 10)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type SendStatusUpdateRequest struct {
	ServiceId       string
	AccountId       string
	Status          ProxyStatus
	ErrorMessage    *string
	InboundListener *ProxyInboundListener
	unknownFields   protoreflect.RawFields
}

func (m *SendStatusUpdateRequest) Reset()         { *m = SendStatusUpdateRequest{} }
func (m *SendStatusUpdateRequest) String() string { return fmt.Sprintf("SendStatusUpdateRequest{}") }
func (m *SendStatusUpdateRequest) ProtoMessage()  {}
func (m *SendStatusUpdateRequest) GetServiceId() string {
	if m != nil {
		return m.ServiceId
	}
	return ""
}
func (m *SendStatusUpdateRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}
func (m *SendStatusUpdateRequest) GetStatus() ProxyStatus {
	if m != nil {
		return m.Status
	}
	return ProxyStatus(0)
}
func (m *SendStatusUpdateRequest) GetErrorMessage() string {
	if m != nil && m.ErrorMessage != nil {
		return *m.ErrorMessage
	}
	return ""
}
func (m *SendStatusUpdateRequest) GetInboundListener() *ProxyInboundListener {
	if m != nil {
		return m.InboundListener
	}
	return nil
}

func (m *SendStatusUpdateRequest) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&SendStatusUpdateRequest{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *SendStatusUpdateRequest) sizeField() int {
	n := 0
	if m.ServiceId != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.ServiceId))
	}
	if m.AccountId != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.AccountId))
	}
	if m.Status != 0 {
		n += protowire.SizeTag(3) + protowire.SizeVarint(uint64(int64(m.Status)))
	}
	if m.ErrorMessage != nil {
		n += protowire.SizeTag(4) + protowire.SizeBytes(len(*m.ErrorMessage))
	}
	if m.InboundListener != nil {
		n += protowire.SizeTag(50) + protowire.SizeBytes(m.InboundListener.sizeField())
	}
	n += len(m.unknownFields)
	return n
}

func (m *SendStatusUpdateRequest) marshalAppend(b []byte) ([]byte, error) {
	if m.ServiceId != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.ServiceId)
	}
	if m.AccountId != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.AccountId)
	}
	if m.Status != 0 {
		b = protowire.AppendTag(b, 3, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(int64(m.Status)))
	}
	if m.ErrorMessage != nil {
		b = protowire.AppendTag(b, 4, protowire.BytesType)
		b = protowire.AppendString(b, *m.ErrorMessage)
	}
	if m.InboundListener != nil {
		sub, _ := m.InboundListener.marshalAppend(nil)
		b = protowire.AppendTag(b, 50, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *SendStatusUpdateRequest) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.ServiceId = v
		case 2:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.AccountId = v
		case 3:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Status = ProxyStatus(v)
		case 4:
			v, k := protowire.ConsumeString(b)
			consumed = k
			tmp := v
			m.ErrorMessage = &tmp
		case 50:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				mm := &ProxyInboundListener{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				m.InboundListener = mm
			}
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *SendStatusUpdateRequest) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *SendStatusUpdateRequest) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"service_id\":"...)
	dst = jsonString(dst, m.ServiceId)
	dst = append(dst, ',')
	dst = append(dst, "\"account_id\":"...)
	dst = jsonString(dst, m.AccountId)
	dst = append(dst, ',')
	dst = append(dst, "\"status\":"...)
	if s, ok := ProxyStatus_name[int32(m.Status)]; ok {
		dst = jsonString(dst, s)
	} else {
		dst = strconv.AppendInt(dst, int64(m.Status), 10)
	}
	dst = append(dst, ',')
	if m.ErrorMessage != nil {
		dst = append(dst, "\"error_message\":"...)
		dst = jsonString(dst, *m.ErrorMessage)
		dst = append(dst, ',')
	}
	if m.InboundListener != nil {
		dst = append(dst, "\"inbound_listener\":"...)
		if m.InboundListener != nil {
			dst, err = m.InboundListener.AppendJSON(dst)
			if err != nil {
				return dst, err
			}
		} else {
			dst = append(dst, "null"...)
		}
		dst = append(dst, ',')
	}
	dst = jsonEndObj(dst)
	return dst, nil
}

type SyncMappingsAck struct {
	BatchId       string
	unknownFields protoreflect.RawFields
}

func (m *SyncMappingsAck) Reset()         { *m = SyncMappingsAck{} }
func (m *SyncMappingsAck) String() string { return fmt.Sprintf("SyncMappingsAck{}") }
func (m *SyncMappingsAck) ProtoMessage()  {}
func (m *SyncMappingsAck) GetBatchId() string {
	if m != nil {
		return m.BatchId
	}
	return ""
}

func (m *SyncMappingsAck) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&SyncMappingsAck{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *SyncMappingsAck) sizeField() int {
	n := 0
	if m.BatchId != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.BatchId))
	}
	n += len(m.unknownFields)
	return n
}

func (m *SyncMappingsAck) marshalAppend(b []byte) ([]byte, error) {
	if m.BatchId != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.BatchId)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *SyncMappingsAck) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.BatchId = v
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *SyncMappingsAck) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *SyncMappingsAck) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"batch_id\":"...)
	dst = jsonString(dst, m.BatchId)
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type SyncMappingsInit struct {
	ProxyId       string
	Version       string
	StartedAt     *timestamppb.Timestamp
	Capabilities  *ProxyCapabilities
	unknownFields protoreflect.RawFields
}

func (m *SyncMappingsInit) Reset()         { *m = SyncMappingsInit{} }
func (m *SyncMappingsInit) String() string { return fmt.Sprintf("SyncMappingsInit{}") }
func (m *SyncMappingsInit) ProtoMessage()  {}
func (m *SyncMappingsInit) GetProxyId() string {
	if m != nil {
		return m.ProxyId
	}
	return ""
}
func (m *SyncMappingsInit) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}
func (m *SyncMappingsInit) GetStartedAt() *timestamppb.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}
func (m *SyncMappingsInit) GetCapabilities() *ProxyCapabilities {
	if m != nil {
		return m.Capabilities
	}
	return nil
}

func (m *SyncMappingsInit) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&SyncMappingsInit{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *SyncMappingsInit) sizeField() int {
	n := 0
	if m.ProxyId != "" {
		n += protowire.SizeTag(1) + protowire.SizeBytes(len(m.ProxyId))
	}
	if m.Version != "" {
		n += protowire.SizeTag(2) + protowire.SizeBytes(len(m.Version))
	}
	if m.StartedAt != nil {
		n += protowire.SizeTag(3) + protowire.SizeBytes(extSize_timestamppb_Timestamp(m.StartedAt))
	}
	if m.Capabilities != nil {
		n += protowire.SizeTag(4) + protowire.SizeBytes(m.Capabilities.sizeField())
	}
	n += len(m.unknownFields)
	return n
}

func (m *SyncMappingsInit) marshalAppend(b []byte) ([]byte, error) {
	if m.ProxyId != "" {
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendString(b, m.ProxyId)
	}
	if m.Version != "" {
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendString(b, m.Version)
	}
	if m.StartedAt != nil {
		sub := extAppend_timestamppb_Timestamp(nil, m.StartedAt)
		b = protowire.AppendTag(b, 3, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	if m.Capabilities != nil {
		sub, _ := m.Capabilities.marshalAppend(nil)
		b = protowire.AppendTag(b, 4, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *SyncMappingsInit) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.ProxyId = v
		case 2:
			v, k := protowire.ConsumeString(b)
			consumed = k
			m.Version = v
		case 3:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				m.StartedAt = extDecode_timestamppb_Timestamp(v)
			}
		case 4:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				mm := &ProxyCapabilities{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				m.Capabilities = mm
			}
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *SyncMappingsInit) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *SyncMappingsInit) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	dst = append(dst, "\"proxy_id\":"...)
	dst = jsonString(dst, m.ProxyId)
	dst = append(dst, ',')
	dst = append(dst, "\"version\":"...)
	dst = jsonString(dst, m.Version)
	dst = append(dst, ',')
	dst = append(dst, "\"started_at\":"...)
	dst = extJSON_timestamppb_Timestamp(dst, m.StartedAt)
	dst = append(dst, ',')
	dst = append(dst, "\"capabilities\":"...)
	if m.Capabilities != nil {
		dst, err = m.Capabilities.AppendJSON(dst)
		if err != nil {
			return dst, err
		}
	} else {
		dst = append(dst, "null"...)
	}
	dst = append(dst, ',')
	dst = jsonEndObj(dst)
	return dst, nil
}

type SyncMappingsRequest struct {
	Msg           isSyncMappingsRequest_Msg
	unknownFields protoreflect.RawFields
}

func (m *SyncMappingsRequest) Reset()         { *m = SyncMappingsRequest{} }
func (m *SyncMappingsRequest) String() string { return fmt.Sprintf("SyncMappingsRequest{}") }
func (m *SyncMappingsRequest) ProtoMessage()  {}
func (m *SyncMappingsRequest) GetMsg() isSyncMappingsRequest_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}
func (m *SyncMappingsRequest) GetInit() *SyncMappingsInit {
	if v, ok := m.GetMsg().(*SyncMappingsRequest_Init); ok {
		return v.Init
	}
	return nil
}
func (m *SyncMappingsRequest) GetAck() *SyncMappingsAck {
	if v, ok := m.GetMsg().(*SyncMappingsRequest_Ack); ok {
		return v.Ack
	}
	return nil
}

func (m *SyncMappingsRequest) ProtoReflect() protoreflect.Message {
	return msgReflect{MarshalFn: m.marshalAppend, SizeFn: m.sizeField, UnmarshalFn: m.unmarshalMsg, Iface: m, Valid: m != nil,
		NewFn:        func() protoreflect.Message { return (&SyncMappingsRequest{}).ProtoReflect() },
		GetUnknownFn: func() protoreflect.RawFields { return m.unknownFields },
		SetUnknownFn: func(f protoreflect.RawFields) { m.unknownFields = f }}
}

func (m *SyncMappingsRequest) sizeField() int {
	n := 0
	switch c := m.Msg.(type) {
	case *SyncMappingsRequest_Init:
		_ = c
		n += protowire.SizeTag(1) + protowire.SizeBytes(c.Init.sizeField())
	case *SyncMappingsRequest_Ack:
		_ = c
		n += protowire.SizeTag(2) + protowire.SizeBytes(c.Ack.sizeField())
	}
	n += len(m.unknownFields)
	return n
}

func (m *SyncMappingsRequest) marshalAppend(b []byte) ([]byte, error) {
	switch c := m.Msg.(type) {
	case *SyncMappingsRequest_Init:
		sub, _ := c.Init.marshalAppend(nil)
		b = protowire.AppendTag(b, 1, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	case *SyncMappingsRequest_Ack:
		sub, _ := c.Ack.marshalAppend(nil)
		b = protowire.AppendTag(b, 2, protowire.BytesType)
		b = protowire.AppendBytes(b, sub)
	}
	b = append(b, m.unknownFields...)
	return b, nil
}

func (m *SyncMappingsRequest) unmarshalMsg(b []byte) error {
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			return protowire.ParseError(n)
		}
		start := b
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				var mv *SyncMappingsInit
				mm := &SyncMappingsInit{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				mv = mm
				m.Msg = &SyncMappingsRequest_Init{Init: mv}
			}
		case 2:
			v, k := protowire.ConsumeBytes(b)
			consumed = k
			if consumed >= 0 {
				var mv *SyncMappingsAck
				mm := &SyncMappingsAck{}
				if err := mm.unmarshalMsg(v); err != nil {
					return err
				}
				mv = mm
				m.Msg = &SyncMappingsRequest_Ack{Ack: mv}
			}
		default:
			skip := protowire.ConsumeFieldValue(num, typ, b)
			if skip < 0 {
				return protowire.ParseError(skip)
			}
			m.unknownFields = append(m.unknownFields, start[:n+skip]...)
			b = b[skip:]
			continue
		}
		if consumed < 0 {
			return protowire.ParseError(consumed)
		}
		b = b[consumed:]
	}
	return nil
}

func (m *SyncMappingsRequest) MarshalJSON() ([]byte, error) { return m.AppendJSON(nil) }
func (m *SyncMappingsRequest) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	switch c := m.Msg.(type) {
	case *SyncMappingsRequest_Init:
		dst = append(dst, "\"init\":"...)
		if c.Init != nil {
			dst, err = c.Init.AppendJSON(dst)
			if err != nil {
				return dst, err
			}
		} else {
			dst = append(dst, "null"...)
		}
		dst = append(dst, ',')
	case *SyncMappingsRequest_Ack:
		dst = append(dst, "\"ack\":"...)
		if c.Ack != nil {
			dst, err = c.Ack.AppendJSON(dst)
			if err != nil {
				return dst, err
			}
		} else {
			dst = append(dst, "null"...)
		}
		dst = append(dst, ',')
	}
	dst = jsonEndObj(dst)
	return dst, nil
}

func extSize_durationpb_Duration(v *durationpb.Duration) int {
	if v == nil {
		return 0
	}
	n := 0
	if v.Seconds != 0 {
		n += protowire.SizeTag(1) + protowire.SizeVarint(uint64(v.Seconds))
	}
	if v.Nanos != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(int64(v.Nanos)))
	}
	return n
}
func extAppend_durationpb_Duration(b []byte, v *durationpb.Duration) []byte {
	if v == nil {
		return b
	}
	if v.Seconds != 0 {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(v.Seconds))
	}
	if v.Nanos != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(int64(v.Nanos)))
	}
	return b
}
func extDecode_durationpb_Duration(b []byte) *durationpb.Duration {
	m := &durationpb.Duration{}
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Seconds = int64(v)
		case 2:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Nanos = int32(v)
		default:
			consumed = protowire.ConsumeFieldValue(num, typ, b)
		}
		if consumed < 0 {
			break
		}
		b = b[consumed:]
	}
	return m
}
func extJSON_durationpb_Duration(dst []byte, v *durationpb.Duration) []byte {
	if v == nil {
		return append(dst, "null"...)
	}
	sec, nanos := v.Seconds, v.Nanos
	dst = append(dst, '"')
	if sec < 0 || nanos < 0 {
		dst = append(dst, '-')
		if sec < 0 {
			sec = -sec
		}
		if nanos < 0 {
			nanos = -nanos
		}
	}
	dst = strconv.AppendInt(dst, sec, 10)
	if nanos != 0 {
		dst = append(dst, '.')
		dst = append(dst, jsonNanoFrac(nanos)...)
	}
	dst = append(dst, 's', '"')
	return dst
}
func extSize_timestamppb_Timestamp(v *timestamppb.Timestamp) int {
	if v == nil {
		return 0
	}
	n := 0
	if v.Seconds != 0 {
		n += protowire.SizeTag(1) + protowire.SizeVarint(uint64(v.Seconds))
	}
	if v.Nanos != 0 {
		n += protowire.SizeTag(2) + protowire.SizeVarint(uint64(int64(v.Nanos)))
	}
	return n
}
func extAppend_timestamppb_Timestamp(b []byte, v *timestamppb.Timestamp) []byte {
	if v == nil {
		return b
	}
	if v.Seconds != 0 {
		b = protowire.AppendTag(b, 1, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(v.Seconds))
	}
	if v.Nanos != 0 {
		b = protowire.AppendTag(b, 2, protowire.VarintType)
		b = protowire.AppendVarint(b, uint64(int64(v.Nanos)))
	}
	return b
}
func extDecode_timestamppb_Timestamp(b []byte) *timestamppb.Timestamp {
	m := &timestamppb.Timestamp{}
	for len(b) > 0 {
		num, typ, n := protowire.ConsumeTag(b)
		if n < 0 {
			break
		}
		b = b[n:]
		var consumed int
		switch num {
		case 1:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Seconds = int64(v)
		case 2:
			v, k := protowire.ConsumeVarint(b)
			consumed = k
			m.Nanos = int32(v)
		default:
			consumed = protowire.ConsumeFieldValue(num, typ, b)
		}
		if consumed < 0 {
			break
		}
		b = b[consumed:]
	}
	return m
}
func extJSON_timestamppb_Timestamp(dst []byte, v *timestamppb.Timestamp) []byte {
	if v == nil {
		return append(dst, "null"...)
	}
	t := time.Unix(v.Seconds, int64(v.Nanos)).UTC()
	dst = append(dst, '"')
	dst = t.AppendFormat(dst, "2006-01-02T15:04:05")
	if v.Nanos != 0 {
		dst = append(dst, '.')
		dst = append(dst, jsonNanoFrac(v.Nanos)...)
	}
	dst = append(dst, 'Z', '"')
	return dst
}

type msgReflect = pbruntime.Message

var embedMethods = pbruntime.Methods

func embedBool(v bool) uint64                { return pbruntime.Bool(v) }
func jsonEndObj(dst []byte) []byte           { return pbruntime.JSONEndObj(dst) }
func jsonString(dst []byte, s string) []byte { return pbruntime.JSONString(dst, s) }
func jsonBytes(dst []byte, b []byte) []byte  { return pbruntime.JSONBytes(dst, b) }
func jsonNanoFrac(nanos int32) string        { return pbruntime.JSONNanoFrac(nanos) }
