// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proxy.proto

package proxypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProxyStatus int32

const (
	ProxyStatus_PROXY_STATUS_PENDING ProxyStatus = 0
	ProxyStatus_PROXY_STATUS_ACTIVE  ProxyStatus = 1
	ProxyStatus_PROXY_STATUS_ERROR   ProxyStatus = 2
)

// Enum value maps for ProxyStatus.
var (
	ProxyStatus_name = map[int32]string{
		0: "PROXY_STATUS_PENDING",
		1: "PROXY_STATUS_ACTIVE",
		2: "PROXY_STATUS_ERROR",
	}
	ProxyStatus_value = map[string]int32{
		"PROXY_STATUS_PENDING": 0,
		"PROXY_STATUS_ACTIVE":  1,
		"PROXY_STATUS_ERROR":   2,
	}
)

func (x ProxyStatus) Enum() *ProxyStatus {
	p := new(ProxyStatus)
	*p = x
	return p
}

func (x ProxyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proto_enumTypes[0].Descriptor()
}

func (ProxyStatus) Type() protoreflect.EnumType {
	return &file_proxy_proto_enumTypes[0]
}

func (x ProxyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyStatus.Descriptor instead.
func (ProxyStatus) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

type PathRewriteMode int32

const (
	PathRewriteMode_PATH_REWRITE_DEFAULT  PathRewriteMode = 0
	PathRewriteMode_PATH_REWRITE_PRESERVE PathRewriteMode = 1
)

// Enum value maps for PathRewriteMode.
var (
	PathRewriteMode_name = map[int32]string{
		0: "PATH_REWRITE_DEFAULT",
		1: "PATH_REWRITE_PRESERVE",
	}
	PathRewriteMode_value = map[string]int32{
		"PATH_REWRITE_DEFAULT":  0,
		"PATH_REWRITE_PRESERVE": 1,
	}
)

func (x PathRewriteMode) Enum() *PathRewriteMode {
	p := new(PathRewriteMode)
	*p = x
	return p
}

func (x PathRewriteMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PathRewriteMode) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_proto_enumTypes[1].Descriptor()
}

func (PathRewriteMode) Type() protoreflect.EnumType {
	return &file_proxy_proto_enumTypes[1]
}

func (x PathRewriteMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PathRewriteMode.Descriptor instead.
func (PathRewriteMode) EnumDescriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{1}
}

type ProxyCapabilities struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SupportsCustomPorts *bool                  `protobuf:"varint,1,opt,name=supports_custom_ports,json=supportsCustomPorts,proto3,oneof" json:"supports_custom_ports,omitempty"`
	Private             *bool                  `protobuf:"varint,2,opt,name=private,proto3,oneof" json:"private,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProxyCapabilities) Reset() {
	*x = ProxyCapabilities{}
	mi := &file_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyCapabilities) ProtoMessage() {}

func (x *ProxyCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyCapabilities.ProtoReflect.Descriptor instead.
func (*ProxyCapabilities) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *ProxyCapabilities) GetSupportsCustomPorts() bool {
	if x != nil && x.SupportsCustomPorts != nil {
		return *x.SupportsCustomPorts
	}
	return false
}

func (x *ProxyCapabilities) GetPrivate() bool {
	if x != nil && x.Private != nil {
		return *x.Private
	}
	return false
}

type PathTargetOptions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SkipTlsVerify      bool                   `protobuf:"varint,1,opt,name=skip_tls_verify,json=skipTlsVerify,proto3" json:"skip_tls_verify,omitempty"`
	RequestTimeout     *durationpb.Duration   `protobuf:"bytes,2,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	PathRewrite        PathRewriteMode        `protobuf:"varint,3,opt,name=path_rewrite,json=pathRewrite,proto3,enum=proxyfixture.PathRewriteMode" json:"path_rewrite,omitempty"`
	CustomHeaders      map[string]string      `protobuf:"bytes,4,rep,name=custom_headers,json=customHeaders,proto3" json:"custom_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SessionIdleTimeout *durationpb.Duration   `protobuf:"bytes,5,opt,name=session_idle_timeout,json=sessionIdleTimeout,proto3" json:"session_idle_timeout,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PathTargetOptions) Reset() {
	*x = PathTargetOptions{}
	mi := &file_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathTargetOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathTargetOptions) ProtoMessage() {}

func (x *PathTargetOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathTargetOptions.ProtoReflect.Descriptor instead.
func (*PathTargetOptions) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *PathTargetOptions) GetSkipTlsVerify() bool {
	if x != nil {
		return x.SkipTlsVerify
	}
	return false
}

func (x *PathTargetOptions) GetRequestTimeout() *durationpb.Duration {
	if x != nil {
		return x.RequestTimeout
	}
	return nil
}

func (x *PathTargetOptions) GetPathRewrite() PathRewriteMode {
	if x != nil {
		return x.PathRewrite
	}
	return PathRewriteMode_PATH_REWRITE_DEFAULT
}

func (x *PathTargetOptions) GetCustomHeaders() map[string]string {
	if x != nil {
		return x.CustomHeaders
	}
	return nil
}

func (x *PathTargetOptions) GetSessionIdleTimeout() *durationpb.Duration {
	if x != nil {
		return x.SessionIdleTimeout
	}
	return nil
}

type PathMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Options       *PathTargetOptions     `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PathMapping) Reset() {
	*x = PathMapping{}
	mi := &file_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PathMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PathMapping) ProtoMessage() {}

func (x *PathMapping) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PathMapping.ProtoReflect.Descriptor instead.
func (*PathMapping) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *PathMapping) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PathMapping) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PathMapping) GetOptions() *PathTargetOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

type HeaderAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        string                 `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	HashedValue   string                 `protobuf:"bytes,2,opt,name=hashed_value,json=hashedValue,proto3" json:"hashed_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderAuth) Reset() {
	*x = HeaderAuth{}
	mi := &file_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderAuth) ProtoMessage() {}

func (x *HeaderAuth) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderAuth.ProtoReflect.Descriptor instead.
func (*HeaderAuth) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *HeaderAuth) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *HeaderAuth) GetHashedValue() string {
	if x != nil {
		return x.HashedValue
	}
	return ""
}

type Authentication struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionKey           string                 `protobuf:"bytes,1,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	MaxSessionAgeSeconds int64                  `protobuf:"varint,2,opt,name=max_session_age_seconds,json=maxSessionAgeSeconds,proto3" json:"max_session_age_seconds,omitempty"`
	Password             bool                   `protobuf:"varint,3,opt,name=password,proto3" json:"password,omitempty"`
	Pin                  bool                   `protobuf:"varint,4,opt,name=pin,proto3" json:"pin,omitempty"`
	HeaderAuths          []*HeaderAuth          `protobuf:"bytes,5,rep,name=header_auths,json=headerAuths,proto3" json:"header_auths,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Authentication) Reset() {
	*x = Authentication{}
	mi := &file_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authentication) ProtoMessage() {}

func (x *Authentication) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authentication.ProtoReflect.Descriptor instead.
func (*Authentication) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *Authentication) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *Authentication) GetMaxSessionAgeSeconds() int64 {
	if x != nil {
		return x.MaxSessionAgeSeconds
	}
	return 0
}

func (x *Authentication) GetPassword() bool {
	if x != nil {
		return x.Password
	}
	return false
}

func (x *Authentication) GetPin() bool {
	if x != nil {
		return x.Pin
	}
	return false
}

func (x *Authentication) GetHeaderAuths() []*HeaderAuth {
	if x != nil {
		return x.HeaderAuths
	}
	return nil
}

type ProxyMapping struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId      string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Domain         string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Path           []*PathMapping         `protobuf:"bytes,4,rep,name=path,proto3" json:"path,omitempty"`
	Auth           *Authentication        `protobuf:"bytes,5,opt,name=auth,proto3" json:"auth,omitempty"`
	PassHostHeader bool                   `protobuf:"varint,6,opt,name=pass_host_header,json=passHostHeader,proto3" json:"pass_host_header,omitempty"`
	ListenPort     int32                  `protobuf:"varint,7,opt,name=listen_port,json=listenPort,proto3" json:"listen_port,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProxyMapping) Reset() {
	*x = ProxyMapping{}
	mi := &file_proxy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyMapping) ProtoMessage() {}

func (x *ProxyMapping) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyMapping.ProtoReflect.Descriptor instead.
func (*ProxyMapping) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *ProxyMapping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProxyMapping) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *ProxyMapping) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ProxyMapping) GetPath() []*PathMapping {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *ProxyMapping) GetAuth() *Authentication {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ProxyMapping) GetPassHostHeader() bool {
	if x != nil {
		return x.PassHostHeader
	}
	return false
}

func (x *ProxyMapping) GetListenPort() int32 {
	if x != nil {
		return x.ListenPort
	}
	return 0
}

type AccessLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	LogId         string                 `protobuf:"bytes,2,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,3,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessLog) Reset() {
	*x = AccessLog{}
	mi := &file_proxy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessLog) ProtoMessage() {}

func (x *AccessLog) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessLog.ProtoReflect.Descriptor instead.
func (*AccessLog) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *AccessLog) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AccessLog) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *AccessLog) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *AccessLog) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *AccessLog) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordRequest) Reset() {
	*x = PasswordRequest{}
	mi := &file_proxy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordRequest) ProtoMessage() {}

func (x *PasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordRequest.ProtoReflect.Descriptor instead.
func (*PasswordRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *PasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pin           string                 `protobuf:"bytes,1,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinRequest) Reset() {
	*x = PinRequest{}
	mi := &file_proxy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinRequest) ProtoMessage() {}

func (x *PinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinRequest.ProtoReflect.Descriptor instead.
func (*PinRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{8}
}

func (x *PinRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

type HeaderAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeaderValue   string                 `protobuf:"bytes,1,opt,name=header_value,json=headerValue,proto3" json:"header_value,omitempty"`
	HeaderName    string                 `protobuf:"bytes,2,opt,name=header_name,json=headerName,proto3" json:"header_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderAuthRequest) Reset() {
	*x = HeaderAuthRequest{}
	mi := &file_proxy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderAuthRequest) ProtoMessage() {}

func (x *HeaderAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderAuthRequest.ProtoReflect.Descriptor instead.
func (*HeaderAuthRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{9}
}

func (x *HeaderAuthRequest) GetHeaderValue() string {
	if x != nil {
		return x.HeaderValue
	}
	return ""
}

func (x *HeaderAuthRequest) GetHeaderName() string {
	if x != nil {
		return x.HeaderName
	}
	return ""
}

type AuthenticateRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Types that are valid to be assigned to Request:
	//
	//	*AuthenticateRequest_Password
	//	*AuthenticateRequest_Pin
	//	*AuthenticateRequest_HeaderAuth
	Request       isAuthenticateRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_proxy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{10}
}

func (x *AuthenticateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuthenticateRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AuthenticateRequest) GetRequest() isAuthenticateRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AuthenticateRequest) GetPassword() *PasswordRequest {
	if x != nil {
		if x, ok := x.Request.(*AuthenticateRequest_Password); ok {
			return x.Password
		}
	}
	return nil
}

func (x *AuthenticateRequest) GetPin() *PinRequest {
	if x != nil {
		if x, ok := x.Request.(*AuthenticateRequest_Pin); ok {
			return x.Pin
		}
	}
	return nil
}

func (x *AuthenticateRequest) GetHeaderAuth() *HeaderAuthRequest {
	if x != nil {
		if x, ok := x.Request.(*AuthenticateRequest_HeaderAuth); ok {
			return x.HeaderAuth
		}
	}
	return nil
}

type isAuthenticateRequest_Request interface {
	isAuthenticateRequest_Request()
}

type AuthenticateRequest_Password struct {
	Password *PasswordRequest `protobuf:"bytes,3,opt,name=password,proto3,oneof"`
}

type AuthenticateRequest_Pin struct {
	Pin *PinRequest `protobuf:"bytes,4,opt,name=pin,proto3,oneof"`
}

type AuthenticateRequest_HeaderAuth struct {
	HeaderAuth *HeaderAuthRequest `protobuf:"bytes,5,opt,name=header_auth,json=headerAuth,proto3,oneof"`
}

func (*AuthenticateRequest_Password) isAuthenticateRequest_Request() {}

func (*AuthenticateRequest_Pin) isAuthenticateRequest_Request() {}

func (*AuthenticateRequest_HeaderAuth) isAuthenticateRequest_Request() {}

type ProxyInboundListener struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelIp      string                 `protobuf:"bytes,1,opt,name=tunnel_ip,json=tunnelIp,proto3" json:"tunnel_ip,omitempty"`
	HttpsPort     uint32                 `protobuf:"varint,2,opt,name=https_port,json=httpsPort,proto3" json:"https_port,omitempty"`
	HttpPort      uint32                 `protobuf:"varint,3,opt,name=http_port,json=httpPort,proto3" json:"http_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyInboundListener) Reset() {
	*x = ProxyInboundListener{}
	mi := &file_proxy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyInboundListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyInboundListener) ProtoMessage() {}

func (x *ProxyInboundListener) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyInboundListener.ProtoReflect.Descriptor instead.
func (*ProxyInboundListener) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{11}
}

func (x *ProxyInboundListener) GetTunnelIp() string {
	if x != nil {
		return x.TunnelIp
	}
	return ""
}

func (x *ProxyInboundListener) GetHttpsPort() uint32 {
	if x != nil {
		return x.HttpsPort
	}
	return 0
}

func (x *ProxyInboundListener) GetHttpPort() uint32 {
	if x != nil {
		return x.HttpPort
	}
	return 0
}

type SendStatusUpdateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceId       string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	AccountId       string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status          ProxyStatus            `protobuf:"varint,3,opt,name=status,proto3,enum=proxyfixture.ProxyStatus" json:"status,omitempty"`
	ErrorMessage    *string                `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3,oneof" json:"error_message,omitempty"`
	InboundListener *ProxyInboundListener  `protobuf:"bytes,50,opt,name=inbound_listener,json=inboundListener,proto3,oneof" json:"inbound_listener,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SendStatusUpdateRequest) Reset() {
	*x = SendStatusUpdateRequest{}
	mi := &file_proxy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendStatusUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStatusUpdateRequest) ProtoMessage() {}

func (x *SendStatusUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStatusUpdateRequest.ProtoReflect.Descriptor instead.
func (*SendStatusUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{12}
}

func (x *SendStatusUpdateRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *SendStatusUpdateRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SendStatusUpdateRequest) GetStatus() ProxyStatus {
	if x != nil {
		return x.Status
	}
	return ProxyStatus_PROXY_STATUS_PENDING
}

func (x *SendStatusUpdateRequest) GetErrorMessage() string {
	if x != nil && x.ErrorMessage != nil {
		return *x.ErrorMessage
	}
	return ""
}

func (x *SendStatusUpdateRequest) GetInboundListener() *ProxyInboundListener {
	if x != nil {
		return x.InboundListener
	}
	return nil
}

type SyncMappingsInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProxyId       string                 `protobuf:"bytes,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Capabilities  *ProxyCapabilities     `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMappingsInit) Reset() {
	*x = SyncMappingsInit{}
	mi := &file_proxy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMappingsInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMappingsInit) ProtoMessage() {}

func (x *SyncMappingsInit) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMappingsInit.ProtoReflect.Descriptor instead.
func (*SyncMappingsInit) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{13}
}

func (x *SyncMappingsInit) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *SyncMappingsInit) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SyncMappingsInit) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SyncMappingsInit) GetCapabilities() *ProxyCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type SyncMappingsAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchId       string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMappingsAck) Reset() {
	*x = SyncMappingsAck{}
	mi := &file_proxy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMappingsAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMappingsAck) ProtoMessage() {}

func (x *SyncMappingsAck) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMappingsAck.ProtoReflect.Descriptor instead.
func (*SyncMappingsAck) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{14}
}

func (x *SyncMappingsAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

type SyncMappingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*SyncMappingsRequest_Init
	//	*SyncMappingsRequest_Ack
	Msg           isSyncMappingsRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMappingsRequest) Reset() {
	*x = SyncMappingsRequest{}
	mi := &file_proxy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMappingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMappingsRequest) ProtoMessage() {}

func (x *SyncMappingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMappingsRequest.ProtoReflect.Descriptor instead.
func (*SyncMappingsRequest) Descriptor() ([]byte, []int) {
	return file_proxy_proto_rawDescGZIP(), []int{15}
}

func (x *SyncMappingsRequest) GetMsg() isSyncMappingsRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SyncMappingsRequest) GetInit() *SyncMappingsInit {
	if x != nil {
		if x, ok := x.Msg.(*SyncMappingsRequest_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *SyncMappingsRequest) GetAck() *SyncMappingsAck {
	if x != nil {
		if x, ok := x.Msg.(*SyncMappingsRequest_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isSyncMappingsRequest_Msg interface {
	isSyncMappingsRequest_Msg()
}

type SyncMappingsRequest_Init struct {
	Init *SyncMappingsInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type SyncMappingsRequest_Ack struct {
	Ack *SyncMappingsAck `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*SyncMappingsRequest_Init) isSyncMappingsRequest_Msg() {}

func (*SyncMappingsRequest_Ack) isSyncMappingsRequest_Msg() {}

var File_proxy_proto protoreflect.FileDescriptor

const file_proxy_proto_rawDesc = "" +
	"\n" +
	"\vproxy.proto\x12\fproxyfixture\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x01\n" +
	"\x11ProxyCapabilities\x127\n" +
	"\x15supports_custom_ports\x18\x01 \x01(\bH\x00R\x13supportsCustomPorts\x88\x01\x01\x12\x1d\n" +
	"\aprivate\x18\x02 \x01(\bH\x01R\aprivate\x88\x01\x01B\x18\n" +
	"\x16_supports_custom_portsB\n" +
	"\n" +
	"\b_private\"\xab\x03\n" +
	"\x11PathTargetOptions\x12&\n" +
	"\x0fskip_tls_verify\x18\x01 \x01(\bR\rskipTlsVerify\x12B\n" +
	"\x0frequest_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0erequestTimeout\x12@\n" +
	"\fpath_rewrite\x18\x03 \x01(\x0e2\x1d.proxyfixture.PathRewriteModeR\vpathRewrite\x12Y\n" +
	"\x0ecustom_headers\x18\x04 \x03(\v22.proxyfixture.PathTargetOptions.CustomHeadersEntryR\rcustomHeaders\x12K\n" +
	"\x14session_idle_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x12sessionIdleTimeout\x1a@\n" +
	"\x12CustomHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\vPathMapping\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x129\n" +
	"\aoptions\x18\x03 \x01(\v2\x1f.proxyfixture.PathTargetOptionsR\aoptions\"G\n" +
	"\n" +
	"HeaderAuth\x12\x16\n" +
	"\x06header\x18\x01 \x01(\tR\x06header\x12!\n" +
	"\fhashed_value\x18\x02 \x01(\tR\vhashedValue\"\xd3\x01\n" +
	"\x0eAuthentication\x12\x1f\n" +
	"\vsession_key\x18\x01 \x01(\tR\n" +
	"sessionKey\x125\n" +
	"\x17max_session_age_seconds\x18\x02 \x01(\x03R\x14maxSessionAgeSeconds\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\bR\bpassword\x12\x10\n" +
	"\x03pin\x18\x04 \x01(\bR\x03pin\x12;\n" +
	"\fheader_auths\x18\x05 \x03(\v2\x18.proxyfixture.HeaderAuthR\vheaderAuths\"\x81\x02\n" +
	"\fProxyMapping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12-\n" +
	"\x04path\x18\x04 \x03(\v2\x19.proxyfixture.PathMappingR\x04path\x120\n" +
	"\x04auth\x18\x05 \x01(\v2\x1c.proxyfixture.AuthenticationR\x04auth\x12(\n" +
	"\x10pass_host_header\x18\x06 \x01(\bR\x0epassHostHeader\x12\x1f\n" +
	"\vlisten_port\x18\a \x01(\x05R\n" +
	"listenPort\"\x9c\x02\n" +
	"\tAccessLog\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x15\n" +
	"\x06log_id\x18\x02 \x01(\tR\x05logId\x12\x1d\n" +
	"\n" +
	"service_id\x18\x03 \x01(\tR\tserviceId\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.proxyfixture.AccessLog.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x0fPasswordRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"\x1e\n" +
	"\n" +
	"PinRequest\x12\x10\n" +
	"\x03pin\x18\x01 \x01(\tR\x03pin\"W\n" +
	"\x11HeaderAuthRequest\x12!\n" +
	"\fheader_value\x18\x01 \x01(\tR\vheaderValue\x12\x1f\n" +
	"\vheader_name\x18\x02 \x01(\tR\n" +
	"headerName\"\xfe\x01\n" +
	"\x13AuthenticateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12;\n" +
	"\bpassword\x18\x03 \x01(\v2\x1d.proxyfixture.PasswordRequestH\x00R\bpassword\x12,\n" +
	"\x03pin\x18\x04 \x01(\v2\x18.proxyfixture.PinRequestH\x00R\x03pin\x12B\n" +
	"\vheader_auth\x18\x05 \x01(\v2\x1f.proxyfixture.HeaderAuthRequestH\x00R\n" +
	"headerAuthB\t\n" +
	"\arequest\"o\n" +
	"\x14ProxyInboundListener\x12\x1b\n" +
	"\ttunnel_ip\x18\x01 \x01(\tR\btunnelIp\x12\x1d\n" +
	"\n" +
	"https_port\x18\x02 \x01(\rR\thttpsPort\x12\x1b\n" +
	"\thttp_port\x18\x03 \x01(\rR\bhttpPort\"\xaf\x02\n" +
	"\x17SendStatusUpdateRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x121\n" +
	"\x06status\x18\x03 \x01(\x0e2\x19.proxyfixture.ProxyStatusR\x06status\x12(\n" +
	"\rerror_message\x18\x04 \x01(\tH\x00R\ferrorMessage\x88\x01\x01\x12R\n" +
	"\x10inbound_listener\x182 \x01(\v2\".proxyfixture.ProxyInboundListenerH\x01R\x0finboundListener\x88\x01\x01B\x10\n" +
	"\x0e_error_messageB\x13\n" +
	"\x11_inbound_listener\"\xc7\x01\n" +
	"\x10SyncMappingsInit\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\tR\aproxyId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12C\n" +
	"\fcapabilities\x18\x04 \x01(\v2\x1f.proxyfixture.ProxyCapabilitiesR\fcapabilities\",\n" +
	"\x0fSyncMappingsAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\"\x85\x01\n" +
	"\x13SyncMappingsRequest\x124\n" +
	"\x04init\x18\x01 \x01(\v2\x1e.proxyfixture.SyncMappingsInitH\x00R\x04init\x121\n" +
	"\x03ack\x18\x02 \x01(\v2\x1d.proxyfixture.SyncMappingsAckH\x00R\x03ackB\x05\n" +
	"\x03msg*X\n" +
	"\vProxyStatus\x12\x18\n" +
	"\x14PROXY_STATUS_PENDING\x10\x00\x12\x17\n" +
	"\x13PROXY_STATUS_ACTIVE\x10\x01\x12\x16\n" +
	"\x12PROXY_STATUS_ERROR\x10\x02*F\n" +
	"\x0fPathRewriteMode\x12\x18\n" +
	"\x14PATH_REWRITE_DEFAULT\x10\x00\x12\x19\n" +
	"\x15PATH_REWRITE_PRESERVE\x10\x01B?Z=github.com/soypat/embedpb/internal/fixture/proxystock;proxypbb\x06proto3"

var (
	file_proxy_proto_rawDescOnce sync.Once
	file_proxy_proto_rawDescData []byte
)

func file_proxy_proto_rawDescGZIP() []byte {
	file_proxy_proto_rawDescOnce.Do(func() {
		file_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)))
	})
	return file_proxy_proto_rawDescData
}

var file_proxy_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proxy_proto_goTypes = []any{
	(ProxyStatus)(0),                // 0: proxyfixture.ProxyStatus
	(PathRewriteMode)(0),            // 1: proxyfixture.PathRewriteMode
	(*ProxyCapabilities)(nil),       // 2: proxyfixture.ProxyCapabilities
	(*PathTargetOptions)(nil),       // 3: proxyfixture.PathTargetOptions
	(*PathMapping)(nil),             // 4: proxyfixture.PathMapping
	(*HeaderAuth)(nil),              // 5: proxyfixture.HeaderAuth
	(*Authentication)(nil),          // 6: proxyfixture.Authentication
	(*ProxyMapping)(nil),            // 7: proxyfixture.ProxyMapping
	(*AccessLog)(nil),               // 8: proxyfixture.AccessLog
	(*PasswordRequest)(nil),         // 9: proxyfixture.PasswordRequest
	(*PinRequest)(nil),              // 10: proxyfixture.PinRequest
	(*HeaderAuthRequest)(nil),       // 11: proxyfixture.HeaderAuthRequest
	(*AuthenticateRequest)(nil),     // 12: proxyfixture.AuthenticateRequest
	(*ProxyInboundListener)(nil),    // 13: proxyfixture.ProxyInboundListener
	(*SendStatusUpdateRequest)(nil), // 14: proxyfixture.SendStatusUpdateRequest
	(*SyncMappingsInit)(nil),        // 15: proxyfixture.SyncMappingsInit
	(*SyncMappingsAck)(nil),         // 16: proxyfixture.SyncMappingsAck
	(*SyncMappingsRequest)(nil),     // 17: proxyfixture.SyncMappingsRequest
	nil,                             // 18: proxyfixture.PathTargetOptions.CustomHeadersEntry
	nil,                             // 19: proxyfixture.AccessLog.MetadataEntry
	(*durationpb.Duration)(nil),     // 20: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),   // 21: google.protobuf.Timestamp
}
var file_proxy_proto_depIdxs = []int32{
	20, // 0: proxyfixture.PathTargetOptions.request_timeout:type_name -> google.protobuf.Duration
	1,  // 1: proxyfixture.PathTargetOptions.path_rewrite:type_name -> proxyfixture.PathRewriteMode
	18, // 2: proxyfixture.PathTargetOptions.custom_headers:type_name -> proxyfixture.PathTargetOptions.CustomHeadersEntry
	20, // 3: proxyfixture.PathTargetOptions.session_idle_timeout:type_name -> google.protobuf.Duration
	3,  // 4: proxyfixture.PathMapping.options:type_name -> proxyfixture.PathTargetOptions
	5,  // 5: proxyfixture.Authentication.header_auths:type_name -> proxyfixture.HeaderAuth
	4,  // 6: proxyfixture.ProxyMapping.path:type_name -> proxyfixture.PathMapping
	6,  // 7: proxyfixture.ProxyMapping.auth:type_name -> proxyfixture.Authentication
	21, // 8: proxyfixture.AccessLog.timestamp:type_name -> google.protobuf.Timestamp
	19, // 9: proxyfixture.AccessLog.metadata:type_name -> proxyfixture.AccessLog.MetadataEntry
	9,  // 10: proxyfixture.AuthenticateRequest.password:type_name -> proxyfixture.PasswordRequest
	10, // 11: proxyfixture.AuthenticateRequest.pin:type_name -> proxyfixture.PinRequest
	11, // 12: proxyfixture.AuthenticateRequest.header_auth:type_name -> proxyfixture.HeaderAuthRequest
	0,  // 13: proxyfixture.SendStatusUpdateRequest.status:type_name -> proxyfixture.ProxyStatus
	13, // 14: proxyfixture.SendStatusUpdateRequest.inbound_listener:type_name -> proxyfixture.ProxyInboundListener
	21, // 15: proxyfixture.SyncMappingsInit.started_at:type_name -> google.protobuf.Timestamp
	2,  // 16: proxyfixture.SyncMappingsInit.capabilities:type_name -> proxyfixture.ProxyCapabilities
	15, // 17: proxyfixture.SyncMappingsRequest.init:type_name -> proxyfixture.SyncMappingsInit
	16, // 18: proxyfixture.SyncMappingsRequest.ack:type_name -> proxyfixture.SyncMappingsAck
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_proxy_proto_init() }
func file_proxy_proto_init() {
	if File_proxy_proto != nil {
		return
	}
	file_proxy_proto_msgTypes[0].OneofWrappers = []any{}
	file_proxy_proto_msgTypes[10].OneofWrappers = []any{
		(*AuthenticateRequest_Password)(nil),
		(*AuthenticateRequest_Pin)(nil),
		(*AuthenticateRequest_HeaderAuth)(nil),
	}
	file_proxy_proto_msgTypes[12].OneofWrappers = []any{}
	file_proxy_proto_msgTypes[15].OneofWrappers = []any{
		(*SyncMappingsRequest_Init)(nil),
		(*SyncMappingsRequest_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_proto_rawDesc), len(file_proxy_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_proto_goTypes,
		DependencyIndexes: file_proxy_proto_depIdxs,
		EnumInfos:         file_proxy_proto_enumTypes,
		MessageInfos:      file_proxy_proto_msgTypes,
	}.Build()
	File_proxy_proto = out.File
	file_proxy_proto_goTypes = nil
	file_proxy_proto_depIdxs = nil
}
