// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: shapes.proto

package shapespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kind mirrors a real netbird enum: int32 varint on the wire.
type Kind int32

const (
	Kind_KIND_UNKNOWN Kind = 0
	Kind_KIND_A       Kind = 1
	Kind_KIND_B       Kind = 2
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "KIND_UNKNOWN",
		1: "KIND_A",
		2: "KIND_B",
	}
	Kind_value = map[string]int32{
		"KIND_UNKNOWN": 0,
		"KIND_A":       1,
		"KIND_B":       2,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_shapes_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_shapes_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_shapes_proto_rawDescGZIP(), []int{0}
}

// Inner is a nested message (mirrors flow PortInfo / mgmt MachineUserIndexes value).
type Inner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             uint32                 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             string                 `protobuf:"bytes,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inner) Reset() {
	*x = Inner{}
	mi := &file_shapes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inner) ProtoMessage() {}

func (x *Inner) ProtoReflect() protoreflect.Message {
	mi := &file_shapes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inner.ProtoReflect.Descriptor instead.
func (*Inner) Descriptor() ([]byte, []int) {
	return file_shapes_proto_rawDescGZIP(), []int{0}
}

func (x *Inner) GetA() uint32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Inner) GetB() string {
	if x != nil {
		return x.B
	}
	return ""
}

// Shapes exercises every wire feature the generator must emit:
// scalars, enum, nested message, repeated (packed + unpacked), oneof, map.
type Shapes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scalars covering each protowire codec kind
	I32    int32    `protobuf:"varint,1,opt,name=i32,proto3" json:"i32,omitempty"`                     // varint
	I64    int64    `protobuf:"varint,2,opt,name=i64,proto3" json:"i64,omitempty"`                     // varint
	U32    uint32   `protobuf:"varint,3,opt,name=u32,proto3" json:"u32,omitempty"`                     // varint
	U64    uint64   `protobuf:"varint,4,opt,name=u64,proto3" json:"u64,omitempty"`                     // varint
	S32    int32    `protobuf:"zigzag32,5,opt,name=s32,proto3" json:"s32,omitempty"`                   // zigzag32
	S64    int64    `protobuf:"zigzag64,6,opt,name=s64,proto3" json:"s64,omitempty"`                   // zigzag64
	F32    uint32   `protobuf:"fixed32,7,opt,name=f32,proto3" json:"f32,omitempty"`                    // fixed32
	F64    uint64   `protobuf:"fixed64,8,opt,name=f64,proto3" json:"f64,omitempty"`                    // fixed64
	Fl     float32  `protobuf:"fixed32,9,opt,name=fl,proto3" json:"fl,omitempty"`                      // fixed32
	Db     float64  `protobuf:"fixed64,10,opt,name=db,proto3" json:"db,omitempty"`                     // fixed64
	Flag   bool     `protobuf:"varint,11,opt,name=flag,proto3" json:"flag,omitempty"`                  // varint
	Str    string   `protobuf:"bytes,12,opt,name=str,proto3" json:"str,omitempty"`                     // bytes
	Blob   []byte   `protobuf:"bytes,13,opt,name=blob,proto3" json:"blob,omitempty"`                   // bytes
	Kind   Kind     `protobuf:"varint,14,opt,name=kind,proto3,enum=shapes.Kind" json:"kind,omitempty"` // enum -> int32 varint
	Inner  *Inner   `protobuf:"bytes,15,opt,name=inner,proto3" json:"inner,omitempty"`                 // nested message
	Nums   []uint32 `protobuf:"varint,16,rep,packed,name=nums,proto3" json:"nums,omitempty"`           // packed repeated numeric
	Names  []string `protobuf:"bytes,17,rep,name=names,proto3" json:"names,omitempty"`                 // unpacked repeated string
	Inners []*Inner `protobuf:"bytes,18,rep,name=inners,proto3" json:"inners,omitempty"`               // unpacked repeated message
	// oneof: exactly the flow FlowFields.connection_info shape
	//
	// Types that are valid to be assigned to Choice:
	//
	//	*Shapes_ChoiceMsg
	//	*Shapes_ChoiceNum
	Choice isShapes_Choice `protobuf_oneof:"choice"`
	// map<string, message>: the mgmt machine_users shape
	Entries map[string]*Inner `protobuf:"bytes,21,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// proto3 optional fields mirror signal Body.relayServerAddress/sessionId and
	// Mode.direct: presence matters even when the scalar value is zero.
	OptionalFlag *bool   `protobuf:"varint,22,opt,name=optional_flag,json=optionalFlag,proto3,oneof" json:"optional_flag,omitempty"`
	OptionalName *string `protobuf:"bytes,23,opt,name=optional_name,json=optionalName,proto3,oneof" json:"optional_name,omitempty"`
	OptionalBlob []byte  `protobuf:"bytes,24,opt,name=optional_blob,json=optionalBlob,proto3,oneof" json:"optional_blob,omitempty"`
	// map<string, string>: mirrors proxy custom_headers / metadata.
	Labels map[string]string `protobuf:"bytes,25,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional numerics mirror daemon config fields like wireguardPort, mtu,
	// sshJWTCacheTTL, icmp_type and icmp_code.
	OptionalI32 *int32  `protobuf:"varint,26,opt,name=optional_i32,json=optionalI32,proto3,oneof" json:"optional_i32,omitempty"`
	OptionalI64 *int64  `protobuf:"varint,27,opt,name=optional_i64,json=optionalI64,proto3,oneof" json:"optional_i64,omitempty"`
	OptionalU32 *uint32 `protobuf:"varint,28,opt,name=optional_u32,json=optionalU32,proto3,oneof" json:"optional_u32,omitempty"`
	// Optional well-known type mirrors daemon dnsRouteInterval.
	OptionalDuration *durationpb.Duration `protobuf:"bytes,29,opt,name=optional_duration,json=optionalDuration,proto3,oneof" json:"optional_duration,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Shapes) Reset() {
	*x = Shapes{}
	mi := &file_shapes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Shapes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Shapes) ProtoMessage() {}

func (x *Shapes) ProtoReflect() protoreflect.Message {
	mi := &file_shapes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Shapes.ProtoReflect.Descriptor instead.
func (*Shapes) Descriptor() ([]byte, []int) {
	return file_shapes_proto_rawDescGZIP(), []int{1}
}

func (x *Shapes) GetI32() int32 {
	if x != nil {
		return x.I32
	}
	return 0
}

func (x *Shapes) GetI64() int64 {
	if x != nil {
		return x.I64
	}
	return 0
}

func (x *Shapes) GetU32() uint32 {
	if x != nil {
		return x.U32
	}
	return 0
}

func (x *Shapes) GetU64() uint64 {
	if x != nil {
		return x.U64
	}
	return 0
}

func (x *Shapes) GetS32() int32 {
	if x != nil {
		return x.S32
	}
	return 0
}

func (x *Shapes) GetS64() int64 {
	if x != nil {
		return x.S64
	}
	return 0
}

func (x *Shapes) GetF32() uint32 {
	if x != nil {
		return x.F32
	}
	return 0
}

func (x *Shapes) GetF64() uint64 {
	if x != nil {
		return x.F64
	}
	return 0
}

func (x *Shapes) GetFl() float32 {
	if x != nil {
		return x.Fl
	}
	return 0
}

func (x *Shapes) GetDb() float64 {
	if x != nil {
		return x.Db
	}
	return 0
}

func (x *Shapes) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *Shapes) GetStr() string {
	if x != nil {
		return x.Str
	}
	return ""
}

func (x *Shapes) GetBlob() []byte {
	if x != nil {
		return x.Blob
	}
	return nil
}

func (x *Shapes) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_KIND_UNKNOWN
}

func (x *Shapes) GetInner() *Inner {
	if x != nil {
		return x.Inner
	}
	return nil
}

func (x *Shapes) GetNums() []uint32 {
	if x != nil {
		return x.Nums
	}
	return nil
}

func (x *Shapes) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *Shapes) GetInners() []*Inner {
	if x != nil {
		return x.Inners
	}
	return nil
}

func (x *Shapes) GetChoice() isShapes_Choice {
	if x != nil {
		return x.Choice
	}
	return nil
}

func (x *Shapes) GetChoiceMsg() *Inner {
	if x != nil {
		if x, ok := x.Choice.(*Shapes_ChoiceMsg); ok {
			return x.ChoiceMsg
		}
	}
	return nil
}

func (x *Shapes) GetChoiceNum() uint32 {
	if x != nil {
		if x, ok := x.Choice.(*Shapes_ChoiceNum); ok {
			return x.ChoiceNum
		}
	}
	return 0
}

func (x *Shapes) GetEntries() map[string]*Inner {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *Shapes) GetOptionalFlag() bool {
	if x != nil && x.OptionalFlag != nil {
		return *x.OptionalFlag
	}
	return false
}

func (x *Shapes) GetOptionalName() string {
	if x != nil && x.OptionalName != nil {
		return *x.OptionalName
	}
	return ""
}

func (x *Shapes) GetOptionalBlob() []byte {
	if x != nil {
		return x.OptionalBlob
	}
	return nil
}

func (x *Shapes) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Shapes) GetOptionalI32() int32 {
	if x != nil && x.OptionalI32 != nil {
		return *x.OptionalI32
	}
	return 0
}

func (x *Shapes) GetOptionalI64() int64 {
	if x != nil && x.OptionalI64 != nil {
		return *x.OptionalI64
	}
	return 0
}

func (x *Shapes) GetOptionalU32() uint32 {
	if x != nil && x.OptionalU32 != nil {
		return *x.OptionalU32
	}
	return 0
}

func (x *Shapes) GetOptionalDuration() *durationpb.Duration {
	if x != nil {
		return x.OptionalDuration
	}
	return nil
}

type isShapes_Choice interface {
	isShapes_Choice()
}

type Shapes_ChoiceMsg struct {
	ChoiceMsg *Inner `protobuf:"bytes,19,opt,name=choice_msg,json=choiceMsg,proto3,oneof"`
}

type Shapes_ChoiceNum struct {
	ChoiceNum uint32 `protobuf:"varint,20,opt,name=choice_num,json=choiceNum,proto3,oneof"`
}

func (*Shapes_ChoiceMsg) isShapes_Choice() {}

func (*Shapes_ChoiceNum) isShapes_Choice() {}

var File_shapes_proto protoreflect.FileDescriptor

const file_shapes_proto_rawDesc = "" +
	"\n" +
	"\fshapes.proto\x12\x06shapes\x1a\x1egoogle/protobuf/duration.proto\"#\n" +
	"\x05Inner\x12\f\n" +
	"\x01a\x18\x01 \x01(\rR\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\tR\x01b\"\x98\t\n" +
	"\x06Shapes\x12\x10\n" +
	"\x03i32\x18\x01 \x01(\x05R\x03i32\x12\x10\n" +
	"\x03i64\x18\x02 \x01(\x03R\x03i64\x12\x10\n" +
	"\x03u32\x18\x03 \x01(\rR\x03u32\x12\x10\n" +
	"\x03u64\x18\x04 \x01(\x04R\x03u64\x12\x10\n" +
	"\x03s32\x18\x05 \x01(\x11R\x03s32\x12\x10\n" +
	"\x03s64\x18\x06 \x01(\x12R\x03s64\x12\x10\n" +
	"\x03f32\x18\a \x01(\aR\x03f32\x12\x10\n" +
	"\x03f64\x18\b \x01(\x06R\x03f64\x12\x0e\n" +
	"\x02fl\x18\t \x01(\x02R\x02fl\x12\x0e\n" +
	"\x02db\x18\n" +
	" \x01(\x01R\x02db\x12\x12\n" +
	"\x04flag\x18\v \x01(\bR\x04flag\x12\x10\n" +
	"\x03str\x18\f \x01(\tR\x03str\x12\x12\n" +
	"\x04blob\x18\r \x01(\fR\x04blob\x12 \n" +
	"\x04kind\x18\x0e \x01(\x0e2\f.shapes.KindR\x04kind\x12#\n" +
	"\x05inner\x18\x0f \x01(\v2\r.shapes.InnerR\x05inner\x12\x12\n" +
	"\x04nums\x18\x10 \x03(\rR\x04nums\x12\x14\n" +
	"\x05names\x18\x11 \x03(\tR\x05names\x12%\n" +
	"\x06inners\x18\x12 \x03(\v2\r.shapes.InnerR\x06inners\x12.\n" +
	"\n" +
	"choice_msg\x18\x13 \x01(\v2\r.shapes.InnerH\x00R\tchoiceMsg\x12\x1f\n" +
	"\n" +
	"choice_num\x18\x14 \x01(\rH\x00R\tchoiceNum\x125\n" +
	"\aentries\x18\x15 \x03(\v2\x1b.shapes.Shapes.EntriesEntryR\aentries\x12(\n" +
	"\roptional_flag\x18\x16 \x01(\bH\x01R\foptionalFlag\x88\x01\x01\x12(\n" +
	"\roptional_name\x18\x17 \x01(\tH\x02R\foptionalName\x88\x01\x01\x12(\n" +
	"\roptional_blob\x18\x18 \x01(\fH\x03R\foptionalBlob\x88\x01\x01\x122\n" +
	"\x06labels\x18\x19 \x03(\v2\x1a.shapes.Shapes.LabelsEntryR\x06labels\x12&\n" +
	"\foptional_i32\x18\x1a \x01(\x05H\x04R\voptionalI32\x88\x01\x01\x12&\n" +
	"\foptional_i64\x18\x1b \x01(\x03H\x05R\voptionalI64\x88\x01\x01\x12&\n" +
	"\foptional_u32\x18\x1c \x01(\rH\x06R\voptionalU32\x88\x01\x01\x12K\n" +
	"\x11optional_duration\x18\x1d \x01(\v2\x19.google.protobuf.DurationH\aR\x10optionalDuration\x88\x01\x01\x1aI\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.shapes.InnerR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06choiceB\x10\n" +
	"\x0e_optional_flagB\x10\n" +
	"\x0e_optional_nameB\x10\n" +
	"\x0e_optional_blobB\x0f\n" +
	"\r_optional_i32B\x0f\n" +
	"\r_optional_i64B\x0f\n" +
	"\r_optional_u32B\x14\n" +
	"\x12_optional_duration*0\n" +
	"\x04Kind\x12\x10\n" +
	"\fKIND_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06KIND_A\x10\x01\x12\n" +
	"\n" +
	"\x06KIND_B\x10\x02B;Z9github.com/soypat/embedpb/internal/fixture/stock;shapespbb\x06proto3"

var (
	file_shapes_proto_rawDescOnce sync.Once
	file_shapes_proto_rawDescData []byte
)

func file_shapes_proto_rawDescGZIP() []byte {
	file_shapes_proto_rawDescOnce.Do(func() {
		file_shapes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shapes_proto_rawDesc), len(file_shapes_proto_rawDesc)))
	})
	return file_shapes_proto_rawDescData
}

var file_shapes_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_shapes_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shapes_proto_goTypes = []any{
	(Kind)(0),                   // 0: shapes.Kind
	(*Inner)(nil),               // 1: shapes.Inner
	(*Shapes)(nil),              // 2: shapes.Shapes
	nil,                         // 3: shapes.Shapes.EntriesEntry
	nil,                         // 4: shapes.Shapes.LabelsEntry
	(*durationpb.Duration)(nil), // 5: google.protobuf.Duration
}
var file_shapes_proto_depIdxs = []int32{
	0, // 0: shapes.Shapes.kind:type_name -> shapes.Kind
	1, // 1: shapes.Shapes.inner:type_name -> shapes.Inner
	1, // 2: shapes.Shapes.inners:type_name -> shapes.Inner
	1, // 3: shapes.Shapes.choice_msg:type_name -> shapes.Inner
	3, // 4: shapes.Shapes.entries:type_name -> shapes.Shapes.EntriesEntry
	4, // 5: shapes.Shapes.labels:type_name -> shapes.Shapes.LabelsEntry
	5, // 6: shapes.Shapes.optional_duration:type_name -> google.protobuf.Duration
	1, // 7: shapes.Shapes.EntriesEntry.value:type_name -> shapes.Inner
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_shapes_proto_init() }
func file_shapes_proto_init() {
	if File_shapes_proto != nil {
		return
	}
	file_shapes_proto_msgTypes[1].OneofWrappers = []any{
		(*Shapes_ChoiceMsg)(nil),
		(*Shapes_ChoiceNum)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shapes_proto_rawDesc), len(file_shapes_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shapes_proto_goTypes,
		DependencyIndexes: file_shapes_proto_depIdxs,
		EnumInfos:         file_shapes_proto_enumTypes,
		MessageInfos:      file_shapes_proto_msgTypes,
	}.Build()
	File_shapes_proto = out.File
	file_shapes_proto_goTypes = nil
	file_shapes_proto_depIdxs = nil
}
