// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: management_job.proto

package managementjobpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_unknown_status JobStatus = 0
	JobStatus_succeeded      JobStatus = 1
	JobStatus_failed         JobStatus = 2
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "unknown_status",
		1: "succeeded",
		2: "failed",
	}
	JobStatus_value = map[string]int32{
		"unknown_status": 0,
		"succeeded":      1,
		"failed":         2,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_management_job_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_management_job_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_management_job_proto_rawDescGZIP(), []int{0}
}

type JobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ID    []byte                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	// Types that are valid to be assigned to WorkloadParameters:
	//
	//	*JobRequest_Bundle
	WorkloadParameters isJobRequest_WorkloadParameters `protobuf_oneof:"workload_parameters"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JobRequest) Reset() {
	*x = JobRequest{}
	mi := &file_management_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobRequest) ProtoMessage() {}

func (x *JobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_management_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobRequest.ProtoReflect.Descriptor instead.
func (*JobRequest) Descriptor() ([]byte, []int) {
	return file_management_job_proto_rawDescGZIP(), []int{0}
}

func (x *JobRequest) GetID() []byte {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *JobRequest) GetWorkloadParameters() isJobRequest_WorkloadParameters {
	if x != nil {
		return x.WorkloadParameters
	}
	return nil
}

func (x *JobRequest) GetBundle() *BundleParameters {
	if x != nil {
		if x, ok := x.WorkloadParameters.(*JobRequest_Bundle); ok {
			return x.Bundle
		}
	}
	return nil
}

type isJobRequest_WorkloadParameters interface {
	isJobRequest_WorkloadParameters()
}

type JobRequest_Bundle struct {
	Bundle *BundleParameters `protobuf:"bytes,10,opt,name=bundle,proto3,oneof"`
}

func (*JobRequest_Bundle) isJobRequest_WorkloadParameters() {}

type JobResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ID     []byte                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Status JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=managementjobfixture.JobStatus" json:"status,omitempty"`
	Reason []byte                 `protobuf:"bytes,3,opt,name=Reason,proto3" json:"Reason,omitempty"`
	// Types that are valid to be assigned to WorkloadResults:
	//
	//	*JobResponse_Bundle
	WorkloadResults isJobResponse_WorkloadResults `protobuf_oneof:"workload_results"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_management_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_management_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_management_job_proto_rawDescGZIP(), []int{1}
}

func (x *JobResponse) GetID() []byte {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *JobResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_unknown_status
}

func (x *JobResponse) GetReason() []byte {
	if x != nil {
		return x.Reason
	}
	return nil
}

func (x *JobResponse) GetWorkloadResults() isJobResponse_WorkloadResults {
	if x != nil {
		return x.WorkloadResults
	}
	return nil
}

func (x *JobResponse) GetBundle() *BundleResult {
	if x != nil {
		if x, ok := x.WorkloadResults.(*JobResponse_Bundle); ok {
			return x.Bundle
		}
	}
	return nil
}

type isJobResponse_WorkloadResults interface {
	isJobResponse_WorkloadResults()
}

type JobResponse_Bundle struct {
	Bundle *BundleResult `protobuf:"bytes,10,opt,name=bundle,proto3,oneof"`
}

func (*JobResponse_Bundle) isJobResponse_WorkloadResults() {}

type BundleParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleFor     bool                   `protobuf:"varint,1,opt,name=bundle_for,json=bundleFor,proto3" json:"bundle_for,omitempty"`
	BundleForTime int64                  `protobuf:"varint,2,opt,name=bundle_for_time,json=bundleForTime,proto3" json:"bundle_for_time,omitempty"`
	LogFileCount  int32                  `protobuf:"varint,3,opt,name=log_file_count,json=logFileCount,proto3" json:"log_file_count,omitempty"`
	Anonymize     bool                   `protobuf:"varint,4,opt,name=anonymize,proto3" json:"anonymize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleParameters) Reset() {
	*x = BundleParameters{}
	mi := &file_management_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleParameters) ProtoMessage() {}

func (x *BundleParameters) ProtoReflect() protoreflect.Message {
	mi := &file_management_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleParameters.ProtoReflect.Descriptor instead.
func (*BundleParameters) Descriptor() ([]byte, []int) {
	return file_management_job_proto_rawDescGZIP(), []int{2}
}

func (x *BundleParameters) GetBundleFor() bool {
	if x != nil {
		return x.BundleFor
	}
	return false
}

func (x *BundleParameters) GetBundleForTime() int64 {
	if x != nil {
		return x.BundleForTime
	}
	return 0
}

func (x *BundleParameters) GetLogFileCount() int32 {
	if x != nil {
		return x.LogFileCount
	}
	return 0
}

func (x *BundleParameters) GetAnonymize() bool {
	if x != nil {
		return x.Anonymize
	}
	return false
}

type BundleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadKey     string                 `protobuf:"bytes,1,opt,name=upload_key,json=uploadKey,proto3" json:"upload_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleResult) Reset() {
	*x = BundleResult{}
	mi := &file_management_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleResult) ProtoMessage() {}

func (x *BundleResult) ProtoReflect() protoreflect.Message {
	mi := &file_management_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleResult.ProtoReflect.Descriptor instead.
func (*BundleResult) Descriptor() ([]byte, []int) {
	return file_management_job_proto_rawDescGZIP(), []int{3}
}

func (x *BundleResult) GetUploadKey() string {
	if x != nil {
		return x.UploadKey
	}
	return ""
}

var File_management_job_proto protoreflect.FileDescriptor

const file_management_job_proto_rawDesc = "" +
	"\n" +
	"\x14management_job.proto\x12\x14managementjobfixture\"u\n" +
	"\n" +
	"JobRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\fR\x02ID\x12@\n" +
	"\x06bundle\x18\n" +
	" \x01(\v2&.managementjobfixture.BundleParametersH\x00R\x06bundleB\x15\n" +
	"\x13workload_parameters\"\xc0\x01\n" +
	"\vJobResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\fR\x02ID\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1f.managementjobfixture.JobStatusR\x06status\x12\x16\n" +
	"\x06Reason\x18\x03 \x01(\fR\x06Reason\x12<\n" +
	"\x06bundle\x18\n" +
	" \x01(\v2\".managementjobfixture.BundleResultH\x00R\x06bundleB\x12\n" +
	"\x10workload_results\"\x9d\x01\n" +
	"\x10BundleParameters\x12\x1d\n" +
	"\n" +
	"bundle_for\x18\x01 \x01(\bR\tbundleFor\x12&\n" +
	"\x0fbundle_for_time\x18\x02 \x01(\x03R\rbundleForTime\x12$\n" +
	"\x0elog_file_count\x18\x03 \x01(\x05R\flogFileCount\x12\x1c\n" +
	"\tanonymize\x18\x04 \x01(\bR\tanonymize\"-\n" +
	"\fBundleResult\x12\x1d\n" +
	"\n" +
	"upload_key\x18\x01 \x01(\tR\tuploadKey*:\n" +
	"\tJobStatus\x12\x12\n" +
	"\x0eunknown_status\x10\x00\x12\r\n" +
	"\tsucceeded\x10\x01\x12\n" +
	"\n" +
	"\x06failed\x10\x02BOZMgithub.com/soypat/embedpb/internal/fixture/managementjobstock;managementjobpbb\x06proto3"

var (
	file_management_job_proto_rawDescOnce sync.Once
	file_management_job_proto_rawDescData []byte
)

func file_management_job_proto_rawDescGZIP() []byte {
	file_management_job_proto_rawDescOnce.Do(func() {
		file_management_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_management_job_proto_rawDesc), len(file_management_job_proto_rawDesc)))
	})
	return file_management_job_proto_rawDescData
}

var file_management_job_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_management_job_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_management_job_proto_goTypes = []any{
	(JobStatus)(0),           // 0: managementjobfixture.JobStatus
	(*JobRequest)(nil),       // 1: managementjobfixture.JobRequest
	(*JobResponse)(nil),      // 2: managementjobfixture.JobResponse
	(*BundleParameters)(nil), // 3: managementjobfixture.BundleParameters
	(*BundleResult)(nil),     // 4: managementjobfixture.BundleResult
}
var file_management_job_proto_depIdxs = []int32{
	3, // 0: managementjobfixture.JobRequest.bundle:type_name -> managementjobfixture.BundleParameters
	0, // 1: managementjobfixture.JobResponse.status:type_name -> managementjobfixture.JobStatus
	4, // 2: managementjobfixture.JobResponse.bundle:type_name -> managementjobfixture.BundleResult
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_management_job_proto_init() }
func file_management_job_proto_init() {
	if File_management_job_proto != nil {
		return
	}
	file_management_job_proto_msgTypes[0].OneofWrappers = []any{
		(*JobRequest_Bundle)(nil),
	}
	file_management_job_proto_msgTypes[1].OneofWrappers = []any{
		(*JobResponse_Bundle)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_management_job_proto_rawDesc), len(file_management_job_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_management_job_proto_goTypes,
		DependencyIndexes: file_management_job_proto_depIdxs,
		EnumInfos:         file_management_job_proto_enumTypes,
		MessageInfos:      file_management_job_proto_msgTypes,
	}.Build()
	File_management_job_proto = out.File
	file_management_job_proto_goTypes = nil
	file_management_job_proto_depIdxs = nil
}
