syntax = "proto3";

package managementjobfixture;

option go_package = "github.com/soypat/embedpb/internal/fixture/managementjobstock;managementjobpb";

message JobRequest {
  bytes ID = 1;

  oneof workload_parameters {
    BundleParameters bundle = 10;
  }
}

enum JobStatus {
  unknown_status = 0;
  succeeded = 1;
  failed = 2;
}

message JobResponse {
  bytes ID = 1;
  JobStatus status = 2;
  bytes Reason = 3;

  oneof workload_results {
    BundleResult bundle = 10;
  }
}

message BundleParameters {
  bool bundle_for = 1;
  int64 bundle_for_time = 2;
  int32 log_file_count = 3;
  bool anonymize = 4;
}

message BundleResult {
  string upload_key = 1;
}
