// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: flow.proto

package flowpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_TYPE_UNKNOWN Type = 0
	Type_TYPE_ALLOWED Type = 1
	Type_TYPE_DENIED  Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNKNOWN",
		1: "TYPE_ALLOWED",
		2: "TYPE_DENIED",
	}
	Type_value = map[string]int32{
		"TYPE_UNKNOWN": 0,
		"TYPE_ALLOWED": 1,
		"TYPE_DENIED":  2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_flow_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_flow_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_flow_proto_rawDescGZIP(), []int{0}
}

type Direction int32

const (
	Direction_DIRECTION_UNKNOWN Direction = 0
	Direction_DIRECTION_INGRESS Direction = 1
	Direction_DIRECTION_EGRESS  Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNKNOWN",
		1: "DIRECTION_INGRESS",
		2: "DIRECTION_EGRESS",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNKNOWN": 0,
		"DIRECTION_INGRESS": 1,
		"DIRECTION_EGRESS":  2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_flow_proto_enumTypes[1].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_flow_proto_enumTypes[1]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_flow_proto_rawDescGZIP(), []int{1}
}

type FlowEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       []byte                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	FlowFields    *FlowFields            `protobuf:"bytes,4,opt,name=flow_fields,json=flowFields,proto3" json:"flow_fields,omitempty"`
	IsInitiator   bool                   `protobuf:"varint,5,opt,name=isInitiator,proto3" json:"isInitiator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowEvent) Reset() {
	*x = FlowEvent{}
	mi := &file_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowEvent) ProtoMessage() {}

func (x *FlowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowEvent.ProtoReflect.Descriptor instead.
func (*FlowEvent) Descriptor() ([]byte, []int) {
	return file_flow_proto_rawDescGZIP(), []int{0}
}

func (x *FlowEvent) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

func (x *FlowEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *FlowEvent) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *FlowEvent) GetFlowFields() *FlowFields {
	if x != nil {
		return x.FlowFields
	}
	return nil
}

func (x *FlowEvent) GetIsInitiator() bool {
	if x != nil {
		return x.IsInitiator
	}
	return false
}

type FlowEventAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       []byte                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	IsInitiator   bool                   `protobuf:"varint,2,opt,name=isInitiator,proto3" json:"isInitiator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowEventAck) Reset() {
	*x = FlowEventAck{}
	mi := &file_flow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowEventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowEventAck) ProtoMessage() {}

func (x *FlowEventAck) ProtoReflect() protoreflect.Message {
	mi := &file_flow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowEventAck.ProtoReflect.Descriptor instead.
func (*FlowEventAck) Descriptor() ([]byte, []int) {
	return file_flow_proto_rawDescGZIP(), []int{1}
}

func (x *FlowEventAck) GetEventId() []byte {
	if x != nil {
		return x.EventId
	}
	return nil
}

func (x *FlowEventAck) GetIsInitiator() bool {
	if x != nil {
		return x.IsInitiator
	}
	return false
}

type FlowFields struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	FlowId    []byte                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	Type      Type                   `protobuf:"varint,2,opt,name=type,proto3,enum=flowfixture.Type" json:"type,omitempty"`
	RuleId    []byte                 `protobuf:"bytes,3,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Direction Direction              `protobuf:"varint,4,opt,name=direction,proto3,enum=flowfixture.Direction" json:"direction,omitempty"`
	Protocol  uint32                 `protobuf:"varint,5,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SourceIp  []byte                 `protobuf:"bytes,6,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	DestIp    []byte                 `protobuf:"bytes,7,opt,name=dest_ip,json=destIp,proto3" json:"dest_ip,omitempty"`
	// Types that are valid to be assigned to ConnectionInfo:
	//
	//	*FlowFields_PortInfo
	//	*FlowFields_IcmpInfo
	ConnectionInfo   isFlowFields_ConnectionInfo `protobuf_oneof:"connection_info"`
	RxPackets        uint64                      `protobuf:"varint,10,opt,name=rx_packets,json=rxPackets,proto3" json:"rx_packets,omitempty"`
	TxPackets        uint64                      `protobuf:"varint,11,opt,name=tx_packets,json=txPackets,proto3" json:"tx_packets,omitempty"`
	RxBytes          uint64                      `protobuf:"varint,12,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes          uint64                      `protobuf:"varint,13,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	SourceResourceId []byte                      `protobuf:"bytes,14,opt,name=source_resource_id,json=sourceResourceId,proto3" json:"source_resource_id,omitempty"`
	DestResourceId   []byte                      `protobuf:"bytes,15,opt,name=dest_resource_id,json=destResourceId,proto3" json:"dest_resource_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FlowFields) Reset() {
	*x = FlowFields{}
	mi := &file_flow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowFields) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowFields) ProtoMessage() {}

func (x *FlowFields) ProtoReflect() protoreflect.Message {
	mi := &file_flow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowFields.ProtoReflect.Descriptor instead.
func (*FlowFields) Descriptor() ([]byte, []int) {
	return file_flow_proto_rawDescGZIP(), []int{2}
}

func (x *FlowFields) GetFlowId() []byte {
	if x != nil {
		return x.FlowId
	}
	return nil
}

func (x *FlowFields) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNKNOWN
}

func (x *FlowFields) GetRuleId() []byte {
	if x != nil {
		return x.RuleId
	}
	return nil
}

func (x *FlowFields) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIRECTION_UNKNOWN
}

func (x *FlowFields) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *FlowFields) GetSourceIp() []byte {
	if x != nil {
		return x.SourceIp
	}
	return nil
}

func (x *FlowFields) GetDestIp() []byte {
	if x != nil {
		return x.DestIp
	}
	return nil
}

func (x *FlowFields) GetConnectionInfo() isFlowFields_ConnectionInfo {
	if x != nil {
		return x.ConnectionInfo
	}
	return nil
}

func (x *FlowFields) GetPortInfo() *PortInfo {
	if x != nil {
		if x, ok := x.ConnectionInfo.(*FlowFields_PortInfo); ok {
			return x.PortInfo
		}
	}
	return nil
}

func (x *FlowFields) GetIcmpInfo() *ICMPInfo {
	if x != nil {
		if x, ok := x.ConnectionInfo.(*FlowFields_IcmpInfo); ok {
			return x.IcmpInfo
		}
	}
	return nil
}

func (x *FlowFields) GetRxPackets() uint64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *FlowFields) GetTxPackets() uint64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

func (x *FlowFields) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *FlowFields) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *FlowFields) GetSourceResourceId() []byte {
	if x != nil {
		return x.SourceResourceId
	}
	return nil
}

func (x *FlowFields) GetDestResourceId() []byte {
	if x != nil {
		return x.DestResourceId
	}
	return nil
}

type isFlowFields_ConnectionInfo interface {
	isFlowFields_ConnectionInfo()
}

type FlowFields_PortInfo struct {
	PortInfo *PortInfo `protobuf:"bytes,8,opt,name=port_info,json=portInfo,proto3,oneof"`
}

type FlowFields_IcmpInfo struct {
	IcmpInfo *ICMPInfo `protobuf:"bytes,9,opt,name=icmp_info,json=icmpInfo,proto3,oneof"`
}

func (*FlowFields_PortInfo) isFlowFields_ConnectionInfo() {}

func (*FlowFields_IcmpInfo) isFlowFields_ConnectionInfo() {}

type PortInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePort    uint32                 `protobuf:"varint,1,opt,name=source_port,json=sourcePort,proto3" json:"source_port,omitempty"`
	DestPort      uint32                 `protobuf:"varint,2,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortInfo) Reset() {
	*x = PortInfo{}
	mi := &file_flow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortInfo) ProtoMessage() {}

func (x *PortInfo) ProtoReflect() protoreflect.Message {
	mi := &file_flow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortInfo.ProtoReflect.Descriptor instead.
func (*PortInfo) Descriptor() ([]byte, []int) {
	return file_flow_proto_rawDescGZIP(), []int{3}
}

func (x *PortInfo) GetSourcePort() uint32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *PortInfo) GetDestPort() uint32 {
	if x != nil {
		return x.DestPort
	}
	return 0
}

type ICMPInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IcmpType      uint32                 `protobuf:"varint,1,opt,name=icmp_type,json=icmpType,proto3" json:"icmp_type,omitempty"`
	IcmpCode      uint32                 `protobuf:"varint,2,opt,name=icmp_code,json=icmpCode,proto3" json:"icmp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICMPInfo) Reset() {
	*x = ICMPInfo{}
	mi := &file_flow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICMPInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICMPInfo) ProtoMessage() {}

func (x *ICMPInfo) ProtoReflect() protoreflect.Message {
	mi := &file_flow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICMPInfo.ProtoReflect.Descriptor instead.
func (*ICMPInfo) Descriptor() ([]byte, []int) {
	return file_flow_proto_rawDescGZIP(), []int{4}
}

func (x *ICMPInfo) GetIcmpType() uint32 {
	if x != nil {
		return x.IcmpType
	}
	return 0
}

func (x *ICMPInfo) GetIcmpCode() uint32 {
	if x != nil {
		return x.IcmpCode
	}
	return 0
}

var File_flow_proto protoreflect.FileDescriptor

const file_flow_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"flow.proto\x12\vflowfixture\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x01\n" +
	"\tFlowEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\fR\aeventId\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x128\n" +
	"\vflow_fields\x18\x04 \x01(\v2\x17.flowfixture.FlowFieldsR\n" +
	"flowFields\x12 \n" +
	"\visInitiator\x18\x05 \x01(\bR\visInitiator\"K\n" +
	"\fFlowEventAck\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\fR\aeventId\x12 \n" +
	"\visInitiator\x18\x02 \x01(\bR\visInitiator\"\xb8\x04\n" +
	"\n" +
	"FlowFields\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\fR\x06flowId\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.flowfixture.TypeR\x04type\x12\x17\n" +
	"\arule_id\x18\x03 \x01(\fR\x06ruleId\x124\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x16.flowfixture.DirectionR\tdirection\x12\x1a\n" +
	"\bprotocol\x18\x05 \x01(\rR\bprotocol\x12\x1b\n" +
	"\tsource_ip\x18\x06 \x01(\fR\bsourceIp\x12\x17\n" +
	"\adest_ip\x18\a \x01(\fR\x06destIp\x124\n" +
	"\tport_info\x18\b \x01(\v2\x15.flowfixture.PortInfoH\x00R\bportInfo\x124\n" +
	"\ticmp_info\x18\t \x01(\v2\x15.flowfixture.ICMPInfoH\x00R\bicmpInfo\x12\x1d\n" +
	"\n" +
	"rx_packets\x18\n" +
	" \x01(\x04R\trxPackets\x12\x1d\n" +
	"\n" +
	"tx_packets\x18\v \x01(\x04R\ttxPackets\x12\x19\n" +
	"\brx_bytes\x18\f \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\r \x01(\x04R\atxBytes\x12,\n" +
	"\x12source_resource_id\x18\x0e \x01(\fR\x10sourceResourceId\x12(\n" +
	"\x10dest_resource_id\x18\x0f \x01(\fR\x0edestResourceIdB\x11\n" +
	"\x0fconnection_info\"H\n" +
	"\bPortInfo\x12\x1f\n" +
	"\vsource_port\x18\x01 \x01(\rR\n" +
	"sourcePort\x12\x1b\n" +
	"\tdest_port\x18\x02 \x01(\rR\bdestPort\"D\n" +
	"\bICMPInfo\x12\x1b\n" +
	"\ticmp_type\x18\x01 \x01(\rR\bicmpType\x12\x1b\n" +
	"\ticmp_code\x18\x02 \x01(\rR\bicmpCode*;\n" +
	"\x04Type\x12\x10\n" +
	"\fTYPE_UNKNOWN\x10\x00\x12\x10\n" +
	"\fTYPE_ALLOWED\x10\x01\x12\x0f\n" +
	"\vTYPE_DENIED\x10\x02*O\n" +
	"\tDirection\x12\x15\n" +
	"\x11DIRECTION_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11DIRECTION_INGRESS\x10\x01\x12\x14\n" +
	"\x10DIRECTION_EGRESS\x10\x02B=Z;github.com/soypat/embedpb/internal/fixture/flowstock;flowpbb\x06proto3"

var (
	file_flow_proto_rawDescOnce sync.Once
	file_flow_proto_rawDescData []byte
)

func file_flow_proto_rawDescGZIP() []byte {
	file_flow_proto_rawDescOnce.Do(func() {
		file_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flow_proto_rawDesc), len(file_flow_proto_rawDesc)))
	})
	return file_flow_proto_rawDescData
}

var file_flow_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_flow_proto_goTypes = []any{
	(Type)(0),                     // 0: flowfixture.Type
	(Direction)(0),                // 1: flowfixture.Direction
	(*FlowEvent)(nil),             // 2: flowfixture.FlowEvent
	(*FlowEventAck)(nil),          // 3: flowfixture.FlowEventAck
	(*FlowFields)(nil),            // 4: flowfixture.FlowFields
	(*PortInfo)(nil),              // 5: flowfixture.PortInfo
	(*ICMPInfo)(nil),              // 6: flowfixture.ICMPInfo
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_flow_proto_depIdxs = []int32{
	7, // 0: flowfixture.FlowEvent.timestamp:type_name -> google.protobuf.Timestamp
	4, // 1: flowfixture.FlowEvent.flow_fields:type_name -> flowfixture.FlowFields
	0, // 2: flowfixture.FlowFields.type:type_name -> flowfixture.Type
	1, // 3: flowfixture.FlowFields.direction:type_name -> flowfixture.Direction
	5, // 4: flowfixture.FlowFields.port_info:type_name -> flowfixture.PortInfo
	6, // 5: flowfixture.FlowFields.icmp_info:type_name -> flowfixture.ICMPInfo
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_flow_proto_init() }
func file_flow_proto_init() {
	if File_flow_proto != nil {
		return
	}
	file_flow_proto_msgTypes[2].OneofWrappers = []any{
		(*FlowFields_PortInfo)(nil),
		(*FlowFields_IcmpInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flow_proto_rawDesc), len(file_flow_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flow_proto_goTypes,
		DependencyIndexes: file_flow_proto_depIdxs,
		EnumInfos:         file_flow_proto_enumTypes,
		MessageInfos:      file_flow_proto_msgTypes,
	}.Build()
	File_flow_proto = out.File
	file_flow_proto_goTypes = nil
	file_flow_proto_depIdxs = nil
}
