syntax = "proto3";

import "google/protobuf/timestamp.proto";

package flowfixture;

option go_package = "github.com/soypat/embedpb/internal/fixture/flowstock;flowpb";

message FlowEvent {
  bytes event_id = 1;
  google.protobuf.Timestamp timestamp = 2;
  bytes public_key = 3;
  FlowFields flow_fields = 4;
  bool isInitiator = 5;
}

message FlowEventAck {
  bytes event_id = 1;
  bool isInitiator = 2;
}

message FlowFields {
  bytes flow_id = 1;
  Type type = 2;
  bytes rule_id = 3;
  Direction direction = 4;
  uint32 protocol = 5;
  bytes source_ip = 6;
  bytes dest_ip = 7;
  oneof connection_info {
    PortInfo port_info = 8;
    ICMPInfo icmp_info = 9;
  }
  uint64 rx_packets = 10;
  uint64 tx_packets = 11;
  uint64 rx_bytes = 12;
  uint64 tx_bytes = 13;
  bytes source_resource_id = 14;
  bytes dest_resource_id = 15;
}

enum Type {
  TYPE_UNKNOWN = 0;
  TYPE_ALLOWED = 1;
  TYPE_DENIED = 2;
}

enum Direction {
  DIRECTION_UNKNOWN = 0;
  DIRECTION_INGRESS = 1;
  DIRECTION_EGRESS = 2;
}

message PortInfo {
  uint32 source_port = 1;
  uint32 dest_port = 2;
}

message ICMPInfo {
  uint32 icmp_type = 1;
  uint32 icmp_code = 2;
}
